# @$-r area                         # request name
# This program begins process of generating 4km grids of
# area emissions from NEI-2014 emissions McKeen 5/29/19
# ISCCMX is number of SCCs in emissn file - must
# supply these SCCs in fort.2 before program works now.
# Version uses OSD emissions, if available, or takes annual 
# emissions & converts to OSD using temporal allocation factors
# Revised to generate grids for all chemical species
# 10/30/08 - This version does old (2004) hydrocarbon splits
# from SAPRC-99 mechanism. This is meant to be an "interim"
# update to original WRF/Chem inventories until SAPRC-07T is
# used for VOC splits.
# 11/5/08 - PM2.5 speciation from Speciate4.0 and SMOKE 2.5 gsref
# SCC to simplified profile assignment added to program

#
#               ********************************************
#               *******      C shell for plot        *******
#               ********************************************
#
#       this is INTERACTIVE or BATCH
#
if ( $?ENVIRONMENT ) then
   echo "environment variable defined as $ENVIRONMENT"
else
   setenv ENVIRONMENT INTERACTIVE
   echo "environment variable defined as $ENVIRONMENT"
endif
#
#       have the temporary disk as default
#
set ExpD = /wrk/d2/bmcdonald/NEI17/area/Month01/COMM_Coal
#set ExpD = /wrk/d2/stu/nei17/area_txtwrt
#set ExpName = weekdy
#set ExpName = satdy
set ExpName = sundy
#
#       have the temporary disk as default
if (   -d ${ExpD}/${ExpName} ) then
   chdir  ${ExpD}/${ExpName}
else
   mkdir  ${ExpD}/${ExpName}
   chmod 755 ${ExpD}/${ExpName}
   chdir  ${ExpD}/${ExpName}
endif
#
#       set up input units:
if ( -e area17v1.f ) rm area17v1.f
# echo "if ( -e area17v1.f ) rm area17v1.f"
if ( -e fort.5 ) rm fort.5
cat >fort.5<< EOFA
3  # IDYoWK, day of week emission, 0=average,1=weekday,2=Saturday,3=Sunday
1  # IMONTH, month of year (1=January, 6=June, 12=December)
'/wrk/d2/stu/nei17/nonpoint_dat/SmokeFlatFile_NONPOINT_20200507.csv'  7/8/20 SMOKE ready file of area emission
2103001000 2103002000    #Commercial Coal
EOFA
#'/wrk/d2/stu/nei14/nonpoint_dat/nonpt/2014NEIv2_NONPOINT_final_20180119_25jan2018_v2.csv'  5/29/19 SMOKE ready file of area emission
#'/wrk/d2/stu/nei14/nonpoint_dat/nonpt/pfc_2014NEIv2_NONPOINT_final_20180119_22jan2018_v0.csv'  5/29/19 SMOKE ready file of area emission
#'/wrk/d2/stu/nei14/nonpoint_dat/np_oilgas/np_oilgas_2014NEIv2_NONPOINT_final_20180119_22jan2018_v0.csv'  5/29/19 SMOKE ready file of area emission
#'/wrk/d2/stu/nei14/nonpoint_dat/cmv_c1c2/c1c2_onshore_2014NEIv2_NONPOINT_final_20180119_30jan2018_v3.csv'  5/29/19 SMOKE ready file of area emission
#'/wrk/d2/stu/nei14/nonpoint_dat/cmv_c1c2/c1c2_offshore_2014NEIv2_NONPOINT_final_20180119_22jan2018_v0.csv'  5/29/19 SMOKE ready file of area emission
#'/wrk/d2/stu/nei14/nonpoint_dat/ag/ag_nh3_2014NEIv2_NONPOINT_final_20180119_monthly_25jan2018_v0.csv'  5/29/19 SMOKE ready file of area emission
#'/wrk/d2/stu/nei14/nonpoint_dat/ag/ag_not_nh3_2014NEIv2_NONPOINT_final_20180119_monthly_25jan2018_v0.csv'  5/29/19 SMOKE ready file of area emission
#'/wrk/d2/stu/nei14/nonpoint_dat/afdust/afdust_pm_2014NEIv2_NONPOINT_penultimate_20171228_22jan2018_nf_v2.csv'  5/29/19 SMOKE ready file of area emission
#'/wrk/d1/stu/nei11/nonpoint_dat/SmokeFlatFile_NONPOINT_20130911.csv'  SMOKE ready file of area emission
#2000000000 2862000000    #Total Area Sources
#2401001000 2461900000    #Total VCPs
#2294000000 2296019999    #Total Fugitive Dust (paved + unpaved)
#
#2102001000 2102002000    #Industrial Coal
#2102004000 2102005000    #Industrial Oil
#2102011000 2102011000    #Industrial Oil2
#2102006000 2102007000    #Industrial NG
#2102010000 2102010000    #Industrial NG2
#2102008000 2102008000    #Industrial Wood
#2103001000 2103002000    #Commercial Coal
#2103004000 2103005000    #Commercial Oil
#2103011000 2103011000    #Commercial Oil2
#2103006000 2103007000    #Commercial NG
#2103008000 2103008000    #Commercial Wood
#2104001000 2104002000    #Residential Coal
#2104004000 2104004000    #Residential Oil
#2104011000 2104011000    #Residential Oil2
#2104006000 2104007000    #Residential NG
#2104008100 2104009000    #Residential Wood
#
#2301000000 2301030000    #CHEM
#2308000000 2308000000    #CHEM2
#2302000000 2302080002    #FOOD
#2304000000 2305000000    #METAL
#2309000000 2309000000    #METAL2
#2325000000 2325060000    #METAL3
#2306010000 2306010100    #REFINE
#2307000000 2307000000    #PULP
#2311010000 2311030000    #CONST
#2312000000 2312000000    #MACHINE
#2399000000 2399010000    #OTH
#2310000220 2310001000    #OnG
#2310010100 2310011600    #OnG2
#2310020000 2310021803    #OnG3
#2310023000 2310111701    #OnG4
#2310121100 2310121700    #OnG5
#2310300220 2310421603    #OnG6
#2310002000 2310002421    #OffG
#2310012000 2310012526    #OffG2
#2310022000 2310022506    #OffG3
#2310112401 2310112401    #OffG4
#2310122100 2310122100    #OffG5
#
#2275087000 2275087000    #AVIATION
#2280002101 2280002204    #CMV_DSL
#2280003103 2280003204    #CMV_OGV
#2285002006 2285002010    #RAIL
#
#2401001000 2401001000    #ArchCoat
#2401005000 2401200000    #IndCoat
#2460400000 2460500000    #ConsCoat
#2415000000 2415000000    #Degreasing
#2420000000 2420000999    #Cleaning 1
#2460200000 2460200000    #Cleaning 2
#2425000000 2425040000    #Printing Inks
#2440020000 2440020000    #IndAdhesives
#2460100000 2460100000    #Personal
#2460600000 2460600000    #Consumer Adhesives
#2460800000 2460800000    #Consumer Pesticides
#2461800001 2461850000    #Agricultural Pesticides
#
#2302002000 2302003299    #Commercial Cooking
#2501011011 2501995120    #Evaporative Gasoline 
#2505010000 2525000000    #Storage 
#2601000000 2680003000    #WASTE
#2801000000 2801000008    #CROP
#2801520000 2801700099    #CROP2
#2801500000 2801500600    #AgBURN
#2805001000 2807030000    #LIVESTOCK
#2294000000 2296000000    #DUST
#2810003000 2862000000    #MISC
#
if (   -d ./commons ) then
   chdir  ./commons
else
   mkdir  ./commons
   chmod 755 ./commons
   chdir  ./commons
endif
if ( -e parame.h ) rm parame.h
cat >parame.h<< EOFA
C-----------------------------------------------------------------------
      PARAMETER(ISCCMX=455,NRECMX=9124863)
      PARAMETER(IX=1332,JX=1008,IP=IX+1,JP=JX+1,IM=IX-1,JM=JX-1)
C     PARAMETER(ICONTY=3141)
      PARAMETER(IZLEV=12,IZLVM=IZLEV-1)
C Parameters for surrogate, lat/lon, SCC indexing for spatial allocation
      PARAMETER(ISURMX=890,ISTCMX=99999)
C 11/18/13 There are 4 extra profiles that are secondary assignments, and not in primary -
C (110,340,710,810) Make sure they are included in  ISRGREN,ISRGRBG
      PARAMETER(ISURNMX=72+4,ISUGRMX=21328424)
C Parameters for indexing month, week, & day allocation profiles
      PARAMETER(IMNMX=3082,IWKMX=111,IDYMX=13666)
C Number of distinct U.S. IFIPS in tref file = IFIPMX
      PARAMETER(IFIPMX=3460+1)  ! Add extra 56075 county not in FIPS file
C Number of SCCs to be ignored
      PARAMETER(NSCCSKIP=8)
C Number of VOC species in SAPRAC99 mechanism and Speciate3.2 Profile assignments
C     PARAMETER(IVOCSAP=30,IVOCEX=12,IVOC=IVOCSAP+IVOCEX,IVOCPMX=1775)
C     PARAMETER(IVOCSAP=30,IVOCEX=12,IVOC=IVOCSAP+IVOCEX,IVOCPMX=1793) ! 12/15/13 with 18 extra VOC profs for OnG
C     PARAMETER(IVOCSAP=35,IVOCEX=15,IVOC=IVOCSAP+IVOCEX,IVOCPMX=1793) ! 3/12/14 SAPRC-11,14 xtra, with 18 extra VOC profs for OnG
C     PARAMETER(IVOCSAP=35,IVOCEX=15,IVOC=IVOCSAP+IVOCEX,IVOCPMX=2175) ! 6/29/19 SAPRC-11, for Speciate4.5 and NEI-2014
      PARAMETER(IVOCSAP=35,IVOCEX=15,IVOC=IVOCSAP+IVOCEX,IVOCPMX=2550) ! 711/20 SAPRC-11, for Speciate5.0 and NEI-2017
C Number of PM2.5 species in EPA PM speciation file
C     PARAMETER(IPM25=6,IPM2PMX=87)  ! NEI-2011
C     PARAMETER(IPM25=19,IPM2PMX=87)  ! NEI-2011 v1platform
      PARAMETER(IPM25=19,IPM2PMX=728)  ! NEI-2017 v1platform
C  ITIMVAR: 1= hourly emis output,0= not; IDYoWK: 0=average,1=weekday,2=Saturday,3=Sunday
      PARAMETER(ITIMVAR=1)
C 5/22/12  IPRI needed for EMIS_FIX subroutine
      PARAMETER(IPRI=8)
      PARAMETER(MxSCClim=7)
C-----------------------------------------------------------------------
C
EOFA
if ( -e mappar.h ) rm mappar.h
cat >mappar.h<< EOFA
C-----------------------------------------------------------------------
      COMMON /MAPPAR/ DX,XLATC,XLONC,IL,JL,PLM1,PLM2,PLM3,PLM4,IPROJ,
     -CLAT1,CLAT2
      COMMON /MAPNES1/ INEST1,XNESSTR,YNESSTR,DXBIGDO
C
EOFA
if ( -e suridex.h ) rm suridex.h
cat >suridex.h<< EOFA
C-----------------------------------------------------------------------
      COMMON /SCCS/SCCNUM(ISCCMX),SURFIL(ISURNMX)
      COMMON /SC2SUR/ISURSCC(ISCCMX),ISURGID(ISURMX)
C     COMMON /IGRSUR/IGRDSR(ISUGRMX),JGRDSR(ISUGRMX),SURFRC(ISUGRMX)
      COMMON /ISRGRL/ISRGRBG(ISURNMX,IFIPMX),ISRGREN(ISURNMX,IFIPMX)
      COMMON /SC2S23/ISUSECN(ISURNMX),ISUTERT(ISURNMX),ISUQUAD(ISURNMX)
     -,ISURNM(ISURNMX),ISUR100
      COMMON /SCCLIM/N_SCClim,ISCCLo(MxSCClim),ISCCHi(MxSCClim)
      CHARACTER*10 SCCNUM
      CHARACTER*120 SURFIL
      INTEGER*8 ISCCLo,ISCCHi
C
EOFA
if ( -e tafidex.h ) rm tafidex.h
cat >tafidex.h<< EOFA
C-----------------------------------------------------------------------
      COMMON /SC2TAF/IFIPNM(IFIPMX),IFIPID(ISTCMX),IDMN(ISCCMX,IFIPMX),
     -IDWK(ISCCMX,IFIPMX),IDDY(ISCCMX,IFIPMX),FSCMN(IMNMX),
     -FSCWK(IWKMX,7),FSCDY(IDYMX,24)
      COMMON/DYOWK/IDYoWK,IMONTH
C
EOFA
if ( -e vocidex.h ) rm vocidex.h
cat >vocidex.h<< EOFA
C-----------------------------------------------------------------------
      COMMON/VOC1/ ISCCVOC(ISCCMX,IFIPMX),PRFLUMP(IVOC,IVOCPMX)
     -,FACSCC2T(ISCCMX)
C
EOFA
if ( -e pm2idex.h ) rm pm2idex.h
cat >pm2idex.h<< EOFA
C-----------------------------------------------------------------------
      COMMON/PM25/ ISCCPM2(ISCCMX),PRFLPM2(IPM25,IPM2PMX)
     -,FACSCC2T(ISCCMX)
C
EOFA
if ( -e names.h ) rm names.h
cat >names.h<< EOFA
C-----------------------------------------------------------------------
C
      COMMON/NAMER/NAM,INARG,NAMVOC(IVOC),NAMPM2(IPM25),SPECNAM(IPRI)
      COMMON/ZLEV/ ZLEV(IZLEV)
      COMMON/DIRECTS/INDIR,OUFIL
      COMMON/INTGR1/LLET
      CHARACTER*9 NAM
      CHARACTER*120 INDIR,OUFIL
      CHARACTER*9 INARG
      CHARACTER*10 NAMVOC
      CHARACTER*10 NAMPM2
      CHARACTER*8 SPECNAM
      INTEGER LLET
EOFA
if ( -e timvari.h ) rm timvari.h
cat >timvari.h<< EOFA
C-----------------------------------------------------------------------
C
      COMMON/TVREAL/EM(24,IX,JX)
      COMMON/TVCHAR/TVDIRNM
      CHARACTER*5 TVDIRNM
EOFA
cd ..
rm -f area17v1.f
cat >area17v1.f<< EOFB
      PROGRAM SHADEFL
C===============================================================================
C
C  This program plots EPA 1996 (NET V.5) emissions for selected Lambert map,
C  for first cut,
C===============================================================================
      include 'commons/parame.h'
      include 'commons/mappar.h'
      include 'commons/names.h'
      include 'commons/suridex.h'
      include 'commons/tafidex.h'
C     COMMON/PLOTR/PLB1(2),PLT1(2),PRB1(2),PRT1(2),WTMOLC(4),ISP
      INTEGER*8 ISCCIN
      CHARACTER*1 DSGN
      CHARACTER*10 SCCIN
      DATA DSGN /' '/
      DATA XP1,XP2/1.,1./
C Nesting Corner of 3km (99 x 99 cross points) in 27km domain is 107. 75.66667
C go 27 points (81km in 3km grid= 3 grids in 27 km res.) farther on boundaries
C dimension should now be 27+36+99 (east-west) by 27+36+129 (north-south) cross points
C To make sure NCAR MAP routine includes complete counties near boundaries.
C     DATA DX,INEST1,XNESSTR,YNESSTR/4.E3,1,-18.,-18./
C     DATA DXBIGDO,XLATC,XLONC,IL,JL/4.E3,40.,-97.,1333,1009/
C     DATA CLAT1,CLAT2/45.,33./
      DATA DX,INEST1,XNESSTR,YNESSTR/4.E3,0,0.,0./
      DATA DXBIGDO,XLATC,XLONC,IL,JL/4.E3,40.,-97.,1369,1045/
      DATA CLAT1,CLAT2/45.,33./
C IPROJ=3 is Mercator (lat, lon) projection
C     DATA IPROJ / 3 /
C IPROJ=1 is Lambert Conformal (standard MM4) projection
      DATA IPROJ / 1 /
C     DATA WTMOLC/68.,138.,148.,30./
      DATA (NAMVOC(I),I=1,IVOCSAP)/
     -' METHANE  ',' ALKANE1  ',' ALKANE2  ',' ALKANE3  ',' ALKANE4  ',
     -' ALKANE5  ',' ETHYLENE ',' OLEFIN1  ',' OLEFIN2  ',' ISOPRENE ',
     -' TERPENES ','AROMATIC1 ','AROMATIC2 ','   CH2O   ',' CH3CHO   ',
     -'HI_ALDEHY ','BENZALDHY ',' ACETONE  ','   MEK    ','  PRD2    ',
     -'   MEOH   ',' GLYOXAL  ','METHGLYOX ','   BACL   ',' PHENOLS  ',
     -' CRESOLS  ','  MACR    ','  MVK     ','   IPRD   ',' HCOOH    ',
     -' CH3COOH  ',' RCOOH    ',' XYLENEOLS',' CATECHOLS',' NONVOLATL'/
C    -' CRESOLS  ','  MACR    ','  MVK     ','   IPRD   ','UNREACTIV '/
      DATA (NAMVOC(I),I=IVOCSAP+1,IVOCSAP+IVOCEX)/
     -' PROPYLENE',' ACETYLENE',' BENZENE  ',' BUTANES  ',' PENTANES ',
     -' TOLUENE  ',' m-XYLENE ',' o-XYLENE ',' p-XYLENE ',' PROPANE  ',
     -'  DIENES  ',' STYRENES ',' ETHANOL  ','ETHE_GLYC ',' UNKNOWN  '/
C    -' TOLUENE  ',' XYLENES  ',' PROPANE  ','  DIENES  ',' STYRENES ',
C    -' ORGACIDS ',' ETHANOL  '/
      DATA (NAMPM2(I),I=1,IPM25)/'PMFINE','PSO4','PNO3','POC','PEC',
     -'PNCOM','PNH4','PAL','PCA','PFE','PH2O','PMG','PMOTHR','PK','PMN'
     -,'PCL','PNA','PTI','PSI'/
C    -'PNCOM'/
      DATA SPECNAM/'VOC','NOX','CO','SO2','PM10-PRI','PM25-PRI','NH3',
     -'CO2'/
      CALL GETARG(1,INARG)
      LLET=LNBLNK(INARG)
      NAM=INARG 
      OUFIL='area.'//INARG(1:LLET)//'.outp'
      OPEN(7,FILE=OUFIL)
      OPEN(2,FILE='fort.2')
      REWIND(2)
      II=0
 9    CONTINUE
      READ(2,*,END=10)SCCIN
      II=II+1
      SCCNUM(II)=SCCIN
      GOTO 9
 10   CONTINUE
      IF(II.NE.ISCCMX)THEN
      WRITE(*,*)' ISCCMX= ',ISCCMX, ' not input II= ',II 
      WRITE(*,*)' Stopping'
      STOP888
      ENDIF
      CLOSE(2)
      CALL USFIPS  ! Load up state/county FIP codes for county-specific VOC,TAF, and spatial parititioning
C     ISTOP=1
C     IF(ISTOP.EQ.1)STOP999
      OPEN(5,FILE='fort.5')
      READ(5,*)IDYoWK
      READ(5,*)IMONTH
      READ(5,'(1x)') ! Only one input file, will read in SUBROUTINE EMIS 12/10/20
      N_SCClim=0
 5    CONTINUE
      READ(5,*,END=12)ISCCLo(N_SCClim+1),ISCCHi(N_SCClim+1)  ! SCC limits (inclusive) for sector limited Emission output
      N_SCClim=N_SCClim+1
      GOTO 5
 12   CONTINUE
      CLOSE(5)
      WRITE(7,*)N_SCClim,' SCC limits in this emission filter'
      WRITE(*,*)N_SCClim,' SCC limits in this emission filter'
      IF(N_SCClim.GT.0)THEN
       DO I=1,N_SCClim
       WRITE(7,*),I,ISCCLo(I),'-',ISCCHi(I)
       WRITE(*,*),I,ISCCLo(I),'-',ISCCHi(I)
       ENDDO
      ENDIF
      WRITE(7,*)'IDYoWK,IMONTH= ',IDYoWK,IMONTH
C     WRITE(7,*)'Removing VCP and OnG SCCs='
C     WRITE(*,*)'Removing VCP and OnG SCCs='
C     WRITE(7,*)'No removal of any SCC'
C     WRITE(*,*)'No removal of any SCC'
      IF(INARG(1:LLET).EQ.'VOC')CALL VOCPRFC
      IF(INARG(1:LLET).EQ.'PM25-PRI')CALL PM2PRFC
      CALL SCC2SUR
      CALL SUR2GRD
C     ISTOP=1
C     IF(ISTOP.EQ.1)STOP'999'
      CALL EMIS
 99   CONTINUE
      CLOSE(7)
      STOP9999
       END
      SUBROUTINE EMIS
      include 'commons/parame.h'
      include 'commons/names.h'
      include 'commons/suridex.h'
      include 'commons/tafidex.h'
      DIMENSION EMTRX(IX,JX),ECNTSC(ISTCMX,ISCCMX),THRPSV(ISTCMX,ISCCMX)
      DIMENSION ECOUN(ISTCMX),ESTATE(99)
      INTEGER IPRNT(ISTCMX)
      INTEGER IFLGE(ISTCMX,ISCCMX)
      INTEGER ITYPE(6) !counts records for each type of emission: OSD, annual, etc
C ITYPE: 1=OSD, 2=annual, 3=OS avg wkdy, 4=annual avg day, 5=June-Sept avg day
C  6=OtherOSDperiod:total over time period (IPER=30)
      INTEGER*8 I8PN1,I8PN2,ISCC
      CHARACTER*10 SCC,SCCSKIP(NSCCSKIP)
      CHARACTER*1 CHAR1
      CHARACTER*20 CDUM
      CHARACTER NAMIN*9
      CHARACTER*120 TRIBENM
      CHARACTER*3 CHNUM
      CHARACTER*5 CCOUN
      PARAMETER(IZERO=ISTCMX*ISCCMX)
      DATA ICAPT,II/0,0/
      DATA ITYPE/6*0/
      DATA ECNTSC/IZERO*0./
      DATA ECOUN/ISTCMX*0./
      DATA ESTATE/99*0./
      DATA ETOT/0./
      DATA IPRNT/ISTCMX*0/
      DATA IFLGE/IZERO*0/
      DATA IOTP,IOTHER/0,0/
      DATA EMAX,EMIN/0.,1.E25/
      DATA IMAX,JMAX,I2NUMT/-999,-999,500/
C ISCCSKIP contains list of SCCs to ignore in emissions file read
C  Skip SCC list includes Forest Wildfires, Managed Burning/Slash (Logging Debris),
C  Prescribed Burning for Forest Management, & Prescribed Burning for Rangeland, Biogenic veg. and ag.
C 5/29/19 Take all area sources, prescribed burning SCCs in 2014-v2 are all "unspecified burn.."
C     DATA SCCSKIP/'2810001000','2810005000','2810015000','2810020000',
C    -'2701200000','2701220000'/
      DATA SCCSKIP/'2701200000','2701220000','2280003204','2280003203',
     -'2280002201','2280002202','2280002203','2280002204'/
      ICOUD=0
C LSP needed in EMIS_FIX subroutine - to modify emissions according to CARB-10, LA county 5/22/12
      LSP=0
      DO I=1,IPRI
C     WRITE(7,'(A,A1)')NAM(1:LLET),'x'
      IF(trim(SPECNAM(I)).EQ.trim(NAM))LSP=I
      ENDDO
      IF(LSP.EQ.0)THEN
      WRITE(7,*)'LSP UNDEFINED, STOPPING'
      WRITE(*,*)'LSP UNDEFINED, STOPPING'
      CALL FLUSH(7)
      STOP
      ENDIF
C End LSP determination
      CALL SCC2TAF  ! Need variables IMONTH,IDYoWK, NAM in SCC2TAF
      OPEN(5,FILE='fort.5')
      REWIND(5)
      READ(5,'(1x)')
      READ(5,'(1x)')
C     READ(5,'(1x)')
      DO 1037 IFIL=1,1  ! just do one file 
C     DO 1037 IFIL=1,8  ! 5/29/19
      READ(5,*)INDIR
      WRITE(7,*)INDIR
      CALL FLUSH(7)
      OPEN(8,FILE=INDIR)
C Determine number of header lines, rewind file, read to first line of data
      IHEAD=0
 98   CONTINUE
      READ(8,'(1A)')CHAR1
      IF(CHAR1.NE.'#')GOTO 99
      IHEAD=IHEAD+1
      GOTO 98
 99   CONTINUE
      IHEAD=IHEAD+1  ! Title line has no # character
      REWIND(8)
      WRITE(7,*)'IHEAD= ',IHEAD
      CALL FLUSH(7)
      DO I=1,IHEAD
      READ(8,'(1X)')
      ENDDO
C You are now at beginning of first line.
 9    CONTINUE
      SUMTHRU=-999.
      WINTHRU=-999.
      SPRTHRU=-999.
      FALTHRU=-999.
C     READ(8,5,END=10,ERR=11)ICOUN,SCC,NAMIN,ISTRMNDY,IENDMNDY,
C    -EMISN,UNITS,IPER
C5    FORMAT(2X,I5,A10,A9,15X,I4,4X,I4,10X,F20,A10,I2)
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
C     READ(8,*,END=10,ERR=11)ICOUN,SCC,CDUM,CDUM,IDUM,CDUM,NAMIN,ANN_EMS
C    -,ADUM,ADUM,ADUM,ADUM,IDUM,IDUM,CDUM,IYEAR,IDUM,CDUM,IDUM,ISTRMNDY,
C    -IENDMNDY,WINTHRU,SPRTHRU,SUMTHRU,FALTHRU
C
C     READ(8,*,END=10,ERR=11)CDUM,ICOUN,IDUM,IDUM,IDUM,SCC,CDUM,NAMIN,
C    -ANN_EMS
      READ(8,*,END=10,ERR=11)CDUM,CCOUN,CDUM,CDUM,CDUM,SCC,CDUM,NAMIN,
     -ANN_EMS ! 5/29/19 2014-v2 format
      READ(CCOUN,'(I)')ICOUN
      II=II+1
      IF(II.LE.100)THEN
C     IF(II.GT.60520.AND.II.LT.60570)THEN
      WRITE(7,*)'ICOUN= ',ICOUN
      WRITE(7,*)'SCC= ',SCC
      WRITE(7,*)'ISTRMNDY= ',ISTRMNDY
      WRITE(7,*)'IENDMNDY= ',IENDMNDY
      WRITE(7,*)'NAMIN= ',NAMIN
      WRITE(7,*)'EMIS= ',ANN_EMS
      WRITE(7,*)'WIN,SPR,SUM,FALTHRU=',WINTHRU,SPRTHRU,SUMTHRU,FALTHRU
      CALL FLUSH(7)
      ENDIF
      IF(ANN_EMS.LE.0.)GOTO 9
C     IF(NAMIN(1:5).EQ.'PM2_5')NAMIN='PM25-PRI'
C     IF(NAMIN(1:4).EQ.'PM10')NAMIN='PM10-PRI'
C     IF(NAMIN(1:LLET).NE.NAM(1:LLET))GOTO 9
      IF(trim(NAMIN).NE.trim(NAM))GOTO 9
C 7/9/20 Take out all biogenic, and commercial vessel underway emissions
      DO N=1,NSCCSKIP
      IF(SCC.EQ.SCCSKIP(N))GOTO 9
      ENDDO
C Window for Livestock only - SCCs from 2805000000 to 2805053100
C     IF(SCC(1:5).NE.'28050')GOTO 9
      READ(SCC,'(I10)')ISCC
C     IF(ISCC.LT.ISCCLo.OR.ISCC.GT.ISCCHi)GOTO 9 ! Only include SCC limits
C     IF(ISCC.GE.ISCCLo.AND.ISCC.LE.ISCCHi)GOTO 9 ! Exlude SCC limits
      IKEEP=1 ! For default, keep all SCCs if no SCC limits in input file 12/8/20
      IF(N_SCClim.GT.0)THEN
      IKEEP=0
       DO I=1,N_SCClim
       IF(ISCC.GE.ISCCLo(I).AND.ISCC.LE.ISCCHi(I))IKEEP=1
       ENDDO
      ENDIF
C     IF(ISCC.GE.2310000000.AND.ISCC.LE.2310499999)IKEEP=0 ! Oil and Gas Explor and Prod
C     IF(ISCC.GE.2401001000.AND.ISCC.LE.2470000000)IKEEP=0 ! Solvent Utilization|Surface Coating|Architectural Coatings|Total: All Solvent Types
C     IF(ISCC.GE.2500000000.AND.ISCC.LE.2505999999)IKEEP=0 ! Evap/Spill area sources
C     IF(ISCC.GE.2280002000.AND.ISCC.LE.2280002999)IKEEP=0 ! OGV Diesel (Underway)
C     IF(ISCC.GE.2280003203.AND.ISCC.LE.2280003204)IKEEP=0 ! OGV Fuel Oil (Underway)
      IF(IKEEP.EQ.0)GOTO 9
      ISTATE=ICOUN/1000
C Skip over Alaska, Hawaii, Puerto Rico and Virgin Islands
      IF(ISTATE.EQ.2.OR.ISTATE.EQ.15.OR.ISTATE.EQ.72.OR.ISTATE.EQ.78)
     -GOTO 9
C 11/20/13 Kick out Hawaii and Alaska shipping lanes - no data for these in spatial surrogates files
      IF(ICOUN.EQ.85005.OR.ICOUN.EQ.85006)GOTO 9
      ICAPT=ICAPT+1
C Index SCC
      DO 100 I=1,ISCCMX
      IF(SCC.EQ.SCCNUM(I))THEN
       GOTO 188
       ENDIF
 100  CONTINUE
      WRITE(7,*)'No SCC found on first pass,SCC= ',SCC
      WRITE(7,*)'II,ICOUN,ICAPT= ',II,ICOUN,ICAPT
      STOP777
 188  CONTINUE
C Load emission into (county,SCC) matrix and set IFLGE with data type
C if IFLGE=0: no data loaded
C if IFLGE=1: OSD (= Ozone season average day) data, always use if available
C**  OSD data found: always use if available
C     IF(ISTRMNDY.EQ.601.AND.IENDMNDY.EQ.831.AND.IPER.EQ.29)THEN
      IF(IFLGE(ICOUN,I).EQ.1)THEN !Check for multiple records
C 11/18/13 Railroad and Port emissions need shapefiles, and uses shape_id
C Variable in emission file to partition.  But 4km spatial surrogates are
C available. Simply partition according to county spatial surrogates, without shape files.
C     WRITE(*,*)'ERROR: Multiple records for this county,SCC'
C     WRITE(*,'(A,I6,A,A10)')'ICOUN=',ICOUN,' SCC=',SCCNUM(I)
C     WRITE(*,*)' ECNTSC=',ECNTSC(ICOUN,I)
C     WRITE(*,*)' EMISN=',ANN_EMS
C     WRITE(7,*)'ERROR: Multiple records for this county,SCC'
C     WRITE(7,'(A,I6,A,A10)')'ICOUN=',ICOUN,' SCC=',SCCNUM(I)
C     WRITE(7,*)' ECNTSC=',ECNTSC(ICOUN,I)
C     WRITE(7,*)' EMISN=',ANN_EMS
C     CALL FLUSH(7)
      ANN_EMS=ECNTSC(ICOUN,I)+ANN_EMS
C 12/29/08 Force addition of tribal code 88206 emissions from alm file into Roosevelt (30085) county
C     IF(ICOUN.EQ.30085.AND.SCC.EQ.'2285002006')THEN
C     ANN_EMS=ECNTSC(ICOUN,I)+ANN_EMS
C     ELSE
C     STOP777
C     ENDIF
      ENDIF !IFLGE(ICOUN,I)=1 test
      ECNTSC(ICOUN,I)=ANN_EMS
      IFLGE(ICOUN,I)=1
C Do Temporal partitioning into daily average in second pass, save thruput
      THRPSV(ICOUN,I)=SUMTHRU
      GOTO 9
C Error on file read, if it is just the last record (NRECMX), ignore error
 11   CONTINUE
C     IF(II.LT.NRECMX)THEN
      WRITE(*,*)'Error reading file, stopping, II= ',II
      WRITE(7,*)'Error reading file, stopping, II= ',II
      WRITE(7,*)'Total records captured for ',NAM,' = ',ICAPT
      CLOSE(8)
      STOP
C     ENDIF
 10   CONTINUE
      WRITE(7,*)'End of file readin, II,ICAPT= ',II,ICAPT
C     WRITE(7,*)'Duchesne County /SCC emissions - ton/yr'
C     DO J=1,ISCCMX
C     IF(ECNTSC(49013,J).GT.0)THEN
C     WRITE(7,*)I,SCCNUM(J),ECNTSC(49013,J)
C     ENDIF
C     ENDDO
C     WRITE(7,*)'Uintah County /SCC emissions - ton/yr'
C     DO J=1,ISCCMX
C     IF(ECNTSC(49047,J).GT.0)THEN
C     WRITE(7,*)I,SCCNUM(J),ECNTSC(49047,J)
C     ENDIF
C     ENDDO
C     WRITE(7,*)'Eastern Cherokee Tribal Lnd Count/SCC emissions-ton/yr'
C     DO J=1,ISCCMX
C     IF(ECNTSC(88001,J).GT.0)THEN
C     WRITE(7,*)I,SCCNUM(J),ECNTSC(88001,J)
C     ENDIF
C     ENDDO
      IF(IFIL.EQ.1)THEN
      WRITE(7,*)'Following Tribal Data not Included: ton/yr'
      CLOSE(14)
      OPEN(14,FILE='/wrk/d1/stu/nei11/EPAdata/Tribal_Code.txt')
 1123 CONTINUE
      READ(14,*,END=1124)CHNUM,TRIBENM
      LSTN=LNBLNK(TRIBENM)
      READ(CHNUM,'(I3)')I
      I=88000+I  ! FIP index for Tribal lands
      SUM=0.
      DO J=1,ISCCMX
      SUM=SUM+ECNTSC(I,J)
      ENDDO
      IF(SUM.GT.0.)THEN
      WRITE(7,*)TRIBENM(1:LSTN)
      DO J=1,ISCCMX
      IF(ECNTSC(I,J).GT.0)THEN
      WRITE(7,*)I,SCCNUM(J),ECNTSC(I,J)
      ENDIF
      ENDDO
      ENDIF
      GOTO 1123
 1124 CONTINUE
      CLOSE(14)
C     ISTOP=1
C     IF(ISTOP.EQ.1)STOP'999'
      CALL FLUSH(7)
      ENDIF !End of IF(IFIL.EQ.1)THEN
 1037 CONTINUE  ! endof IFIL=1,5 loop
      WRITE(*,*)' Done loading ',NAM
      WRITE(*,*)' Totl records= ',II,' Totl captured= ',ICAPT
      WRITE(7,*)' Done loading ',NAM
      WRITE(7,*)' Totl records= ',II,' Totl captured= ',ICAPT
      CALL FLUSH(7)
      CLOSE(8)
C 4/15/12 Force TIMVAR call to make sure matrices are filled with zeroes
      IF(ITIMVAR.EQ.1)THEN
      CALL TIMVAR(1,1001,1,1,0.,0)
      ENDIF
C Grid the emissions
      II=0
C     DO 50 ICOUN=1001,ISTCMX
C     DO 50 ICOUN=1001,86000  ! Don't include Tribal Lands - No surrogate spatial profiles available
      DO 50 ICOUN=1001,85004  ! 5/30/19 - 2014 has 85007 (???) stop at 85004 (East Coast US)
C     DO 50 ICOUN=8001,8001
      ISTATE=ICOUN/1000
C Skip over Alaska, Hawaii, Puerto Rico and Virgin Islands
      IF(ISTATE.EQ.2.OR.ISTATE.EQ.15.OR.ISTATE.EQ.72.OR.ISTATE.EQ.78)
     -GOTO 50
C     IF(ISTATE.EQ.2.OR.ISTATE.EQ.15.OR.ISTATE.GT.56)GOTO 50
C 7/9/20 Kick out South Dakota county 46102 (Ogalala Nation) in NEI-17 area file - no 4km spatial surrongates
      IF(ICOUN.EQ.46102)goto 50
      DO 40 ISC=1,ISCCMX
C Skip ICOUN,ISC pairs that don't have data
      IF(IFLGE(ICOUN,ISC).EQ.0)GOTO 40
      IPRNT(ICOUN)=1
      II=II+1
C 12/22/08 - Time allocation depends on IFIP (state,county) as well as SCC
C IFIPNM is list of IFIPS from SCC2TAF, could be 0 (defalt), 1 thru 56 (statewide) or 1001 to 56999 (per county)
      ISTFIP=-999
      ICOFIP=-999
      XMONFC=1./365.   ! conversion factor from ton/yr to ton/dy - default for itimvar=0
      IF(ITIMVAR.EQ.1)THEN
      ISTATES=1000*ISTATE
      DO JJ=1,IFIPMX
      IF(IDMN(ISC,JJ).GT.0)THEN
      IF(ICOUN.EQ.IFIPNM(JJ))ICOFIP=JJ
      IF(ISTATES.EQ.IFIPNM(JJ))ISTFIP=JJ
      ENDIF
      ENDDO
      IF(ICOFIP.GT.0)THEN
      IFIPTV=ICOFIP  ! IFIPTV is the FIP to use for Time Variation (Nation, State, or County)
      ELSEIF(ISTFIP.GT.0)THEN
      IFIPTV=ISTFIP
      ELSE
      IFIPTV=1
      ENDIF
      IF(IDWK(ISC,IFIPTV).LE.0.OR.IDDY(ISC,IFIPTV).LE.0)THEN
      WRITE(7,'(A,2I11,A11,I7)')'No TAFF,ISC,IFIP,SCC,ICOUN=',ISC,IFIPTV
     -,SCCNUM(ISC),ICOUN
      WRITE(*,'(A,2I11,A11,I7)')'No TAFF,ISC,IFIP,SCC,ICOUN=',ISC,IFIPTV
     -,SCCNUM(ISC),ICOUN
      STOP777
      ENDIF
C Units of annual emissions are ton/yr - convert to average ton/dy for processing 12/19/08
C Use thruput from arinv file if it exists, otherwise use monthly alloc. from tref file.
      IF(THRPSV(ICOUN,ISC).GT.0.)THEN
      XMONFC=THRPSV(ICOUN,ISC)/100./91.25
C     IF(II.LE.1000)THEN
      IF(ICOUN.EQ.20015)THEN
      WRITE(7,*)'Thrpt mnthly,II,SCC,ICOUN=',II,SCCNUM(ISC),ICOUN,XMONFC
      CALL FLUSH(7)
      ENDIF
      ELSEIF(IDMN(ISC,IFIPTV).GT.0)THEN
      IMNDX=IDMN(ISC,IFIPTV)
      XMONFC=FSCMN(IMNDX)*12./365.
C     ICOUD=ICOUD+1
C     IF(ICOUD.LE.200)THEN
      IF(ICOUN.EQ.20015)THEN
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
      WRITE(7,*)'Thrpttrf,II,SCC,COU=',II,SCCNUM(ISC),ICOUN,XMONFC,IMNDX
      CALL FLUSH(7)
      ENDIF
      ELSE
      WRITE(7,'(A,2I11,A11,I7)')'No monthly TAFF,ISC,IFIP,SCC,ICOUN=',
     -ISC,IFIPTV,SCCNUM(ISC),ICOUN
      WRITE(*,'(A,2I11,A11,I7)')'No monthly TAFF,ISC,IFIP,SCC,ICOUN=',
     -ISC,IFIPTV,SCCNUM(ISC),ICOUN
      STOP777
      ENDIF
      ENDIF ! Endof ITIMVAR=1 test
      ECNTSC(ICOUN,ISC)= ECNTSC(ICOUN,ISC)*XMONFC
C 11/18/13 ISURDX depends on county and SCC, saved in direct access file - unit 12
      IRECIN=IFIPID(ICOUN)
      IF(IRECIN.LT.1.OR.IRECIN.GT.IFIPMX)THEN
      WRITE(7,*)'Bad IRECIN for surr dir access read, stopping'
      WRITE(7,*)'ICOUN,ISC,SCC,IRECIN=',ICOUN,ISC,SCCNUM(ISC),IRECIN
      CALL FLUSH(7)
      WRITE(*,*)'Bad IRECIN for surr dir access read, stopping'
      WRITE(*,*)'ICOUN,ISC,SCC,IRECIN=',ICOUN,ISC,SCCNUM(ISC),IRECIN
      CALL FLUSH(6)
      STOP777
      ENDIF
      READ(12,REC=IRECIN)ISURSCC
      ISURDX=ISURSCC(ISC)
C     WRITE(7,*)'First try,ISC,IRECIN,ISURDX=',ISC,IRECIN,ISURDX
      IF(ISURDX.LE.0)THEN
      ISTATES=1000*ISTATE
      IRECIN=IFIPID(ISTATES)
      READ(12,REC=IRECIN)ISURSCC
      ISURDX=ISURSCC(ISC)
C     WRITE(7,*)'Second try,ISC,IRECIN,ISURDX=',ISC,IRECIN,ISURDX
      IF(ISURDX.LE.0)THEN
      READ(12,REC=1)ISURSCC
      ISURDX=ISURSCC(ISC)
C     WRITE(7,*)'Third try,ISC,IRECIN,ISURDX=',ISC,IRECIN,ISURDX
      ENDIF
      ENDIF
C     WRITE(7,*)'ISC,COUN,IFIPID,ISURDX=',ISC,ICOUN,IFIPID(ICOUN),ISURDX
      JCOU=0
 121  CONTINUE
      JCOU=JCOU+1
      IF(ISURDX.LE.0)THEN
      WRITE(7,*)' No surrogate/county pair for SCC= ',SCCNUM(ISC),
     -' and state/county= ',ICOUN,' Stopping'
C     WRITE(7,*)' Use default surrogate code = 100 (Population)'
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
C     ISURDX=ISUR100 !Use surrogate code = 100 (Population) when no gridded surrogate exists
       STOP'777'
      ENDIF
C 6/15/08 Broomfield, CO county not in 4km surrogate partitioning file, put in Boulder County
      ICOUDO=ICOUN
C     IF(ICOUN.EQ.8014)ICOUDO=8013
      INUM=IFIPID(ICOUDO)
      IF(ISRGRBG(ISURDX,INUM).EQ.0)THEN
      WRITE(7,'(A,A10,A,I5,A,I1)')' No surrogate/county pair for SCC= '
     -,SCCNUM(ISC),'State/county= ',ICOUDO,' try=',JCOU
C     WRITE(7,*)'ISURDX,INUM=',ISURDX,INUM
C     STOP'777'
      IF(JCOU.EQ.1)THEN
      ISURPRI=ISURDX
      ISURDX=ISUSECN(ISURDX)
      GOTO 121
      ELSEIF(JCOU.EQ.2)THEN
      ISURDX=ISUTERT(ISURPRI)
      GOTO 121
      ELSEIF(JCOU.EQ.3)THEN
      ISURDX=ISUQUAD(ISURPRI)
      GOTO 121
      ELSEIF(JCOU.EQ.4)THEN
      ISURDX=0
      GOTO 121
      ENDIF
      ENDIF
      IBEG=ISRGRBG(ISURDX,INUM)
      IEND=ISRGREN(ISURDX,INUM)
C 11/17/13 Read directly from surrougate files supplied by EPA, indices are line numbers in file
      IF(IBEG.GT.1)THEN
      CLOSE(13)
      OPEN(13,FILE=SURFIL(ISURDX))
      DO III=1,IBEG-1
      READ(13,*)
      ENDDO
      DO 7 III=IBEG,IEND
      READ(13,*,END=10)ISURG,ICNTY,I,J,SURFRC
      IF(SURFRC*ECNTSC(ICOUN,ISC).GT.5..AND.ISTATE.EQ.1)THEN
      WRITE(7,*)'ICOUN= ',ICOUN
      WRITE(7,*)'ISC= ',ISC
      WRITE(7,*)'SCCNUM(ISC)= ',SCCNUM(ISC)
      WRITE(7,*)'ECNTSC(ICOUN,ISC)= ',ECNTSC(ICOUN,ISC)
      WRITE(7,*)'ICNTY,I,J,FRC= ',ICNTY,I,J,SURFRC
      ENDIF
      ELEMADD=SURFRC*ECNTSC(ICOUN,ISC)
      EMTRX(I,J)=EMTRX(I,J)+ELEMADD
      IF(ITIMVAR.EQ.1)THEN
      CALL TIMZON(ICOUN,IHRDIF)
C Time allocation factors are for local time, daylight savings handled in TIMZON,
      CALL TIMVAR(ISC,IFIPTV,I,J,ELEMADD,IHRDIF)
      ENDIF
      IFIP=IFIPID(ICOUN)
      IF(NAM(1:3).EQ.'VOC')CALL VOCSPEC(ISC,IFIP,IFIPTV,I,J,ELEMADD,
     -IHRDIF)
      IF(NAM(1:8).EQ.'PM25-PRI')CALL PM2SPEC(ISC,IFIP,IFIPTV,I,J,ELEMADD
     -,IHRDIF)
      IF(EMTRX(I,J).GT.EMAX)THEN
       EMAX=EMTRX(I,J)
       IMAX=I
       JMAX=J
      ENDIF
      IF(EMTRX(I,J).LT.EMIN.AND.EMTRX(I,J).GT.0.) EMIN=EMTRX(I,J)
 7    CONTINUE
      ECOUN(ICOUN)=ECOUN(ICOUN)+ECNTSC(ICOUN,ISC)
      ELSE  ! Else of IF(IBEG.GT.1)THEN - IBEG = 0 or 1
      WRITE(*,*)'No surrogate file found for county/scc, Stopping'
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
      WRITE(*,*)'ICOUN,ISC,SCCNUM(ISC),ISURDX= ',ICOUN,ISC,SCCNUM(ISC),ISURDX
      CALL FLUSH(6)
      STOP'777'
      ENDIF  ! End of IF(IBEG.GT.1)THEN
C Output how many points done - just to get idea of when job will finish
      IF(II.EQ.I2NUMT)THEN
      WRITE(*,*)I2NUMT,' county/scc pairs done'
      WRITE(7,*)I2NUMT,' county/scc pairs done'
      CALL FLUSH(6)
      CALL FLUSH(7)
      I2NUMT=MIN(50000+I2NUMT,2*I2NUMT)
C     IF(II.GT.8000)THEN
C     ISTOP=1
C     IF(ISTOP.EQ.1)STOP999
C     ENDIF
      ENDIF
 40   CONTINUE
      ESTATE(ISTATE)=ESTATE(ISTATE)+ECOUN(ICOUN)
      ETOT=ETOT+ECOUN(ICOUN)
 50   CONTINUE
      OUFIL='area_'//INARG(1:LLET)//'_sums.txt'
      OPEN(8,FILE=OUFIL)
      WRITE(8,200)
 200  FORMAT('US_TOTAL_EMIS')
      WRITE(8,201)ETOT
 201  FORMAT(1PE10.3)
      WRITE(8,*)
      WRITE(8,202)
 202  FORMAT('ISTATE STATE_EMIS')
      DO ISTATE=1,99
      IF(ESTATE(ISTATE).NE.0.)WRITE(8,203)ISTATE,ESTATE(ISTATE)
 203  FORMAT(2X,I2,3X,1PE10.3)
      ENDDO
      WRITE(8,*)
      WRITE(8,204)
 204  FORMAT('ICOUN COUNTY_EMIS')
      DO ICOUN=1001,ISTCMX
      IF(IPRNT(ICOUN).EQ.1)WRITE(8,205)ICOUN,ECOUN(ICOUN)
 205  FORMAT(I5,1X,1PE10.3)
C Check to see what SCCs are emiting so much CO is Kansas county=20015
      IF(ICOUN.EQ.20015)THEN
      DO ISC=1,ISCCMX
      IF(ECNTSC(ICOUN,ISC).GT.0.)THEN
      WRITE(8,*)SCCNUM(ISC),ECNTSC(ICOUN,ISC)
      ENDIF
      ENDDO
      ENDIF
      ENDDO
      CLOSE(8)
      WRITE(*,*)' Done processing ',NAM
      WRITE(*,*)' Totl county,SCC pairs with data= ',II
      WRITE(*,*)'Min nonzero Ton/dy em= ',EMIN,' Max emission= ',EMAX
      WRITE(*,*)' Max emission I,J= ',IMAX,JMAX,',Tot Ems= ',ETOT
      WRITE(7,*)' Done processing ',NAM
      WRITE(7,*)' Totl county,SCC pairs with data= ',II
      WRITE(7,*)'Min nonzero Ton/dy em= ',EMIN,' Max emission= ',EMAX
      WRITE(7,*)' Max emission I,J= ',IMAX,JMAX,',Tot Ems= ',ETOT
      CALL FLUSH(7)
      OUFIL='area.'//INARG(1:LLET)//'.emis'
      OPEN(8,FILE=OUFIL,FORM='UNFORMATTED')
      WRITE(8)EMTRX
      CLOSE(8)
C     OUFIL='area_'//INARG(1:LLET)//'_emis.txt'
C     OPEN(8,FILE=OUFIL)
C     DO J=JX,1,-1
C     DO I=1,IX
C     WRITE(8,'(1PE10.3)')EMTRX(I,J)
C     ENDDO
C     ENDDO
C     CLOSE(8)
      IF(ITIMVAR.EQ.1)CALL TIMVAR(-99,-99,1,1,0.,0)
      IF(NAM(1:3).EQ.'VOC')CALL VOCSPEC(-99,-99,-99,1,1,0.,0)
      IF(NAM(1:8).EQ.'PM25-PRI')CALL PM2SPEC(-99,-99,-99,1,1,0.,0)
      RETURN
      END
C ******************************************************************* 
      SUBROUTINE SCC2SUR
C 11/15/13 Surrogate index code now saved in Direct access file
C so county and SCC specific indexing can be handled without too much memory
      include 'commons/parame.h'
      PARAMETER(ISC2MX=1395)
      PARAMETER(ISURECL=4*ISCCMX)
      include 'commons/names.h'
      include 'commons/suridex.h'
      include 'commons/tafidex.h'
      DIMENSION ISROFSUR(ISC2MX)
      DIMENSION ISURCHK(ISURMX)  ! Diagnostic variable, to track missing surrogate profiles in secondary,tertiary.. assign file
      INTEGER STATUS,SYSTEM
      CHARACTER*10 SCCOFSUR(ISC2MX),SCC
      LOGICAL EXISTS
      DATA INSR,II/0,0/
      WRITE(*,*)'Processing spatial surrogates, SPECIES= ',NAM
      WRITE(7,*)'Processing spatial surrogates, SPECIES= ',NAM
      INQUIRE(FILE='SURbyFIP'//NAM(1:LLET)//'.da',EXIST=EXISTS)
      IF(.NOT.EXISTS)THEN
      WRITE(*,*)'directaccess surrogate file  DOESNT EXIST, making it'
      WRITE(7,*)'directaccess surrogate file  DOESNT EXIST, making it'
      ELSE  ! Use existing spatial surrogate assign by FIP file
C     WRITE(*,*)'directaccess surrogate file EXISTS, using it'
C     WRITE(7,*)'directaccess surrogate file EXISTS, using it'
      WRITE(*,*)'directaccess surrogate file EXISTS, remove/overwrite'
      WRITE(7,*)'directaccess surrogate file EXISTS, remove/overwrite'
      STATUS=SYSTEM('rm -f SURbyFIP'//NAM(1:LLET)//'.da')
      ENDIF
      IUN=12
      OPEN(UNIT=IUN,FILE='SURbyFIP'//NAM(1:LLET)//'.da',ACCESS='DIRECT',
     -RECL=ISURECL,FORM='UNFORMATTED')
      ISURSCC=-999
      N0=0
      DO 2 I=1,IFIPMX
      N0=N0+1
      WRITE(IUN,REC=N0)ISURSCC
 2    CONTINUE
C Onroad file has 10 character SCC, first 3 characters are 220 or 223,
C all but last character is relevant for surrogate number assignment,
C use only 1st 9 characters of SCC in variables SCC, SCCOFSUR
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
      OPEN(8,FILE='/wrk/d1/stu/nei11/EPAdata/v1platform/ge_dat/amgref_us
     -_can_mex_revised_17jul2012_v20.txt')
      DO I=1,77
      READ(8,*)
      ENDDO
 9    CONTINUE
      READ(8,*,END=10)IFIP,SCC,ISURG
C     WRITE(*,'(I6,1X,A10,1X,I3)')IFIP,SCC,ISURG
C     CALL FLUSH(6)
C     WRITE(7,'(I6,1X,A10,1X,I3)')IFIP,SCC,ISURG
C Kick out Canadian profiles 12/19/08
      IF(IFIP.GT.100000)GOTO 9
      IF(ISURGID(ISURG).EQ.0)THEN
      INSR=INSR+1
C Keep track of SCC to surogate mapping for reprocessing of SCCs later
C that don't have an SCC mapping for version 99-3  to surrogate code 1/12/04
      IF(INSR.GT.ISURNMX)THEN
      WRITE(*,*)'More surrogate codes than expected, stopping'
      STOP'888'
      ENDIF
      ISURGID(ISURG)=INSR
      ISURNM(INSR)=ISURG
      IF(ISURG.EQ.100)THEN
      ISUR100=INSR !Get index of surrogate code 100, Population
c     WRITE(7,*)' ISUR100=',ISUR100
      ENDIF
      ENDIF
C Window SCCOFSUR and ISROFSUR for US profile only
      IF(IFIP.EQ.0)THEN
      II=II+1
      IF(II.GT.ISC2MX)THEN
      WRITE(*,*)'More SCC to surrogate pairs than expected, stopping'
      STOP'888'
      ENDIF
      SCCOFSUR(II)=SCC
      ISROFSUR(II)=ISURG
      ENDIF
      DO I=1,ISCCMX
C  A match to emission file SCC was found; ignore 10th character of SCC
      IF(SCC(1:9).EQ.SCCNUM(I)(1:9))THEN
      DO J=1,IFIPMX
      IF(IFIP.EQ.IFIPNM(J))THEN
      READ(12,REC=J)ISURSCC
      ISURSCC(I)=ISURGID(ISURG)
      WRITE(12,REC=J)ISURSCC
C     IF(IFIP.EQ.8001)THEN
C     WRITE(7,*)'Unit12 write,IFIP,J,SCC,I,ISURG,ISURGID=',IFIP,J,SCC,I,
C    -ISURG,ISURGID(ISURG)
C     ENDIF
      GOTO 11
      ENDIF
      ENDDO
C No Wyoming County number 75 in costcy_for_2007platform_10may2013_v8.txt file, Ignore for now
C     IF(IFIP.EQ.56075)GOTO 9
      WRITE(*,*)' No find of IFIP name= ',IFIP
      WRITE(7,*)' No find of IFIP name= ',IFIP
      STOP'777'
      ENDIF
      ENDDO
 11   CONTINUE
      GOTO 9
 10   CONTINUE
      CLOSE(8)
C 11/18/13 There are 4 extra profiles that are secondary assignments, and not in primary -
C (110,340,710,810) Make sure they are included in  ISRGREN,ISRGRBG
      ISURGID(110)=73
      ISURGID(340)=74
      ISURGID(710)=75
      ISURGID(810)=76
      ISURNM(73)=110
      ISURNM(74)=340
      ISURNM(75)=710
      ISURNM(76)=810
      ISCCTOT=II
      WRITE(*,*)' Done with SCC to surrogate indexing, num= ',ISCCTOT
      WRITE(*,*)' Different surrogate numbers = ',INSR
      WRITE(7,*)' Different surrogate numbers = ',INSR
      DO I=1,ISURMX
      IF(ISURGID(I).NE.0)THEN
      WRITE(7,*)' I, ISURGID= ',I,ISURGID(I)
      WRITE(*,*)' I, ISURGID= ',I,ISURGID(I)
      CALL FLUSH(6)
      ENDIF
      ENDDO
C 9/29/03 open file with secondary and tertiary surrogate information
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
       OPEN(9,FILE='/home/stu/emis/em11/EPAdata/surrogate_codes_110413_m
     -od.txt')
      ISURCHK=0  ! Diagnostic variable, to track missing surrogate profiles in secondary,tertiary.. assign file
      READ(9,'(1x)')
 90   CONTINUE
      READ(9,*,END=100)ISUPRI,ISUSEC,ISUTER,ISUQUA
      DO J=1,ISURMX
      IF(ISUPRI.EQ.J)ISURCHK(J)=1
      ENDDO
      IDX=ISURGID(ISUPRI)
      IF(IDX.NE.0)THEN
      IF(ISUSEC.NE.0)ISUSECN(IDX)=ISURGID(ISUSEC)
      IF(ISUTER.NE.0)ISUTERT(IDX)=ISURGID(ISUTER)
      IF(ISUQUA.NE.0)ISUQUAD(IDX)=ISURGID(ISUQUA)
C Test to see if secondary,tertiary and quad profiles are missing in primary profiles
C and need to be assigned 11/18/13
      ITESS=0
      ITEST=0
      ITESQ=0
      DO J=1,ISURNMX
      IF(ISUSECN(IDX).EQ.J)ITESS=1
      IF(ISUTERT(IDX).EQ.J)ITEST=1
      IF(ISUQUAD(IDX).EQ.J)ITESQ=1
      ENDDO
      IF(ITESS.EQ.0.AND.ISUSEC.NE.0)THEN
      WRITE(*,*)'Secondary profile not a primary,= ',ISUSEC
      WRITE(7,*)'Secondary profile not a primary,= ',ISUSEC
      ENDIF
      IF(ITEST.EQ.0.AND.ISUTER.NE.0)THEN
      WRITE(*,*)'Tertiary profile not a primary,= ',ISUTER
      WRITE(7,*)'Tertiary profile not a primary,= ',ISUTER
      ENDIF
      IF(ITESQ.EQ.0.AND.ISUQUA.NE.0)THEN
      WRITE(*,*)'Quartinary profile not a primary,= ',ISUQUA
      WRITE(7,*)'Quartinary profile not a primary,= ',ISUQUA
      ENDIF
      ENDIF
      GOTO 90
 100  CONTINUE
      CLOSE(9)
      DO I=1,ISURMX
      IF(ISURGID(I).GT.0.AND.ISURCHK(I).EQ.0)THEN
      WRITE(*,*)'Missing primary Surrogate assigns for codel= ',I
      ENDIF
      ENDDO
      WRITE(7,*)II,' different SCC codes indexed'
      WRITE(7,*)'SCC        PRIM SECN TERT QUAD'
      READ(12,REC=1)ISURSCC
      DO I=1,ISCCMX
      IF(ISURSCC(I).GT.0)THEN
      J=ISURSCC(I)
      NSEC=0
      IF(ISUSECN(J).GT.0)NSEC=ISURNM(ISUSECN(J))
      NTER=0
      IF(ISUTERT(J).GT.0)NTER=ISURNM(ISUTERT(J))
      NQUA=0
      IF(ISUQUAD(J).GT.0)NQUA=ISURNM(ISUQUAD(J))
C     JJ=ISUSECN(I)
C     JJJ=ISUTERT(I)
C     JJJJ=ISUQUAD(I)
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
      WRITE(7,'(A10,4(1X,I4))')SCCNUM(I),ISURNM(J),NSEC,NTER,NQUA
C     WRITE(7,'(A10,4(1X,I4))')SCCNUM(I),ISURNM(J),ISURNM(JJ),ISURNM(JJJ
C    -),ISURNM(JJJJ)
      ELSE
      WRITE(7,'(A,A10)')'SCC has no spatial alloc  =',SCCNUM(I)
C 1/11/04, Using nearest SCC allocation factors for version 3 SCCs not
C in version 2, thus having no spatial surrogate assignment
      IEND=9
 16   CONTINUE
      DO II=1,ISCCTOT
      IF(SCCOFSUR(II)(1:IEND).EQ.SCCNUM(I)(1:IEND))THEN
      WRITE(7,'(A,A10)')'Using ',SCCOFSUR(II)
      ISURSCC(I)=ISURGID(ISROFSUR(II))
      WRITE(12,REC=1)ISURSCC
      GOTO 15
      ENDIF
      ENDDO
      WRITE(7,*)'Still no SCC assigned, go 1 SCC character to left'
      IEND=IEND-1 
      GOTO 16
  15  CONTINUE
      ENDIF
      ENDDO
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
      RETURN
      END
      SUBROUTINE SUR2GRD
      include 'commons/parame.h'
      include 'commons/names.h'
      include 'commons/suridex.h'
      include 'commons/tafidex.h'
      CHARACTER*1 CHAR1
      CHARACTER*120 INDRS
      CHARACTER*3 SPRFN
      LOGICAL EXISTS
      DATA ICAPT,II/0,0/
      DATA ISIDO,ICNTYO/0,0/
C Onroad file has 10 character SCC, first 3 characters are 220 or 223,
C all but last character is relevant for surrogate number assignment
C     OPEN(8,FILE='/wrk/d1/stu/d1/nei2005/EPAdata/amgpro.4km_041604.us')
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
      INDRS='/wrk/d1/stu/nei11/EPAdata/spatial_surrogates/CONUS4_2010_v3
     -/'
      ICAPT=0
      II=0
      ISIDO=0
      ICNTYO=0
      LDR=LNBLNK(INDRS)
      DO ISUR=1,ISURNMX
      SURFIL(ISUR)=''
      WRITE(SPRFN,'(I3.3)')ISURNM(ISUR)
C There are no surrogate files for profile 623 - Yuma county CO specific nat. gas trucking/flaring
C  - Use 698 profile instead 11/18/13
      IF(SPRFN.EQ.'623')SPRFN='698'
      SURFIL(ISUR)=INDRS(1:LDR)//'USA_'//SPRFN//'_FILL.txt'
      INQUIRE(FILE=SURFIL(ISUR),EXIST=EXISTS)
      IF(.NOT.EXISTS)THEN
      SURFIL(ISUR)=INDRS(1:LDR)//'USA_'//SPRFN//'_NOFILL.txt'
      INQUIRE(FILE=SURFIL(ISUR),EXIST=EXISTS)
      IF(.NOT.EXISTS)THEN
      WRITE(*,*)'Stop, No 4km surrogate index file, prof=',ISURNM(ISUR)
      ENDIF
      ENDIF
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
      WRITE(*,'(I,2A)')ISUR,' Opening Surr. Index file= ',SURFIL(ISUR)
      WRITE(7,'(I,2A)')ISUR,' Opening Surr. Index file= ',SURFIL(ISUR)
      OPEN(8,FILE=SURFIL(ISUR))
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
C Determine number of header lines, rewind file, read to first line of data
C Determine number of header lines, rewind file, read to first line of data
      IHEAD=0
 98   CONTINUE
      READ(8,'(1A)')CHAR1
      IF(CHAR1.NE.'#')GOTO 99
      IHEAD=IHEAD+1
      GOTO 98
 99   CONTINUE
C     IHEAD=IHEAD+1  ! Title line has no # character
      REWIND(8)
      WRITE(7,*)'IHEAD= ',IHEAD
      CALL FLUSH(7)
      DO I=1,IHEAD
      READ(8,'(1X)')
      ENDDO
C You are now at beginning of first line.
      II=IHEAD  ! Keep track of total records in surrogate file, including headers 11/17/13
      WRITE(*,*)'surr. file read, header num=',IHEAD
 9    CONTINUE
      READ(8,*,END=10)ISURG,ICNTY,IGRD,JGRD,FRC
C     WRITE(*,*)ISURGID(ISURG),ICNTY,IGRD,JGRD,FRC
      IGOOD=0
C Only consider mobile SCC codes picked up in subrout. SCC2SUR here!
      II=II+1
C     IGRDSR(II)=IGRD
C     JGRDSR(II)=JGRD
C     SURFRC(II)=FRC
      IF(ISURGID(ISURG).EQ.0)GOTO 9
      IGOOD=1
      ISID=ISURGID(ISURG)
C     IF(ISID.NE.ISIDO.OR.ICNTY.NE.ICNTYO)THEN  ! 11/18/13, NEI-2011 has a file for each profile, not all combined
      IF(ICNTY.NE.ICNTYO)THEN
       IF(ISIDO.NE.0)THEN
       INUM=IFIPID(ICNTYO)
       ISRGREN(ISIDO,INUM)=II-1
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
C     IF(ICAPT.EQ.0)THEN
      IF(ICNTYO.EQ.8001)THEN
      WRITE(*,'(4(I,1X),A,2I7)')ISIDO,INUM,ISURNM(ISIDO),ICNTYO,' New su
     -rr. county,BEG,END=',ISRGRBG(ISID,INUM),ISRGREN(ISID,INUM)
      WRITE(7,'(4(I,1X),A,2I7)')ISIDO,INUM,ISURNM(ISIDO),ICNTYO,' New su
     -rr. county,BEG,END=',ISRGRBG(ISID,INUM),ISRGREN(ISID,INUM)
      CALL FLUSH(6)
      CALL FLUSH(7)
      ENDIF
       ENDIF
      ICAPT=ICAPT+1
      INUM=IFIPID(ICNTY)
      IF(INUM.LE.0)THEN
      WRITE(*,*)ICNTY,' No County assign in surrogate file, stopping'
      WRITE(7,*)ICNTY,' No County assign in surrogate file, stopping'
      STOP'777'
      ENDIF
      ISRGRBG(ISID,INUM)=II
      ISIDO=ISID
      ICNTYO=ICNTY
      ENDIF
      GOTO 9
 10   CONTINUE
      IF(IGOOD.EQ.1)THEN
      INUM=IFIPID(ICNTYO)
      ISRGREN(ISIDO,INUM)=II
      ENDIF
      WRITE(*,'(2(I,1X),A,2I7)')ISURNM(ISIDO),ICNTYO,' Last sur. county,
     -BEG,END=',ISRGRBG(ISID,INUM),ISRGREN(ISID,INUM)
      WRITE(7,'(2(I,1X),A,2I7)')ISURNM(ISIDO),ICNTYO,' Last sur. county,
     -BEG,END=',ISRGRBG(ISID,INUM),ISRGREN(ISID,INUM)
      CALL FLUSH(6)
      CALL FLUSH(7)
      WRITE(*,*)' Done with surrogate to state/county grid indexing'
      WRITE(7,*)' Different surrogate/location numbers = ',ICAPT
      CLOSE(8)
      ENDDO  ! End of ISUR=1,ISURNMX
C Print out surrogates for specific STATE/COUNTY
C     ICNT=42005
C     DO I=1,ISURNMX
C     IF(ISRGRBG(I,ICNT).NE.0)THEN
C     WRITE(7,*)'I,CNTY,BG,END= ',I,ICNT,ISRGRBG(I,ICNT),ISRGREN(I,ICNT)
C      DO J=ISRGRBG(I,ICNT),ISRGREN(I,ICNT)
C      WRITE(7,*)'I,J,FRAC= ',IGRDSR(J),JGRDSR(J),SURFRC(J)
C      ENDDO
C     ENDIF
C     ENDDO
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
      RETURN
      END
      SUBROUTINE USFIPS
C  Reads state and county codes from EPA file that came with v1platform
C data with the NEI-2011, downloaded 11/9/13
C 11/18/13 - There is a weird Wyoming county 56075 Not in the FIPS file.
C This corresponds to Powder River Gas&Oil operations in Montana, that are
C part of spatial partitioning/Oil and Gas emissions files.  Add one
C extra county to list.
C This subroutine essentially fills the array IFIPNM(IFIPMX)
      include 'commons/parame.h'
      include 'commons/tafidex.h'
      CHARACTER*4 CHAR4
      IFIPNM=-999
      IFIPID=-999
      IFIPNM(1)=0
      NIFIPS=1   ! number of different IFIPS read in
      CLOSE(8)
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
      OPEN(8,FILE='/wrk/d1/stu/nei11/EPAdata/v1platform/ge_dat/costcy_fo
     -r_2007platform_10may2013_v8.txt')
 98   CONTINUE
      READ(8,'(A)')CHAR4
      IF(CHAR4(2:4).NE.'STA')GOTO 98
      DO I=1,72
      READ(8,'(1X,I2)')IFIP
      NIFIPS=NIFIPS+1
      II=IFIP*1000
      IFIPID(II)=NIFIPS
      IFIPNM(NIFIPS)=II
      ENDDO
 99   CONTINUE
      READ(8,'(A)')CHAR4
      IF(CHAR4(2:4).NE.'COU')GOTO 99
      DO I=1,3387
      READ(8,'(26X,I2,I3)')ISTAT,ICOU
      IFIP=1000*ISTAT+ICOU
      NIFIPS=NIFIPS+1  ! Title line has no # character
      IF(NIFIPS.GT.IFIPMX)THEN
      WRITE(7,*)'IFIPMX too small, stopping'
      WRITE(*,*)'IFIPMX too small, stopping'
      CALL FLUSH(7)
      STOP'777'
      ENDIF
      IFIPID(IFIP)=NIFIPS
      IFIPNM(NIFIPS)=IFIP
      ENDDO
      IFIPID(56075)=IFIPMX
      IFIPNM(IFIPMX)=56075
      CLOSE(8)
      RETURN
      END
C ******************************************************************* 
      SUBROUTINE SCC2TAF
C  Reads temporal allocation factors and assigns to appropriate SCC
C 6/13/08 onnonroad processing has species and emission type dependece
      include 'commons/parame.h'
C Parameters for indexing month, week, & day allocation profiles
C 6/13/08 IDMN,IDWK,IDDY are now indexes pointing to first index of FSCMN,FSCWK,FSCDY
      include 'commons/names.h'
      include 'commons/suridex.h'
      include 'commons/tafidex.h'
      DIMENSION FMNSV(IMNMX)
      INTEGER FMN(12),FWK(7),FDY(24)
      INTEGER IMNSV(IMNMX),IWKSV(IWKMX),IDYSV(IDYMX)
      CHARACTER*10 SCC
      CHARACTER*16 POL
      CHARACTER*6 CFIP
      INTEGER FTOT
      DATA ITIMES/0/
      SAVE
      ITIMES=ITIMES+1
      IF(ITIMES.EQ.1)THEN
      WRITE(*,*)'Reading month TAF,assigning to SCC,IMONTH=',IMONTH
      CLOSE(8)
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
      OPEN(8,FILE='/wrk/d1/stu/nei11/EPAdata/v1platform/ge_dat/amptpro_f
     -or_2011_platform_with_carb_mobile_2011CEM_moves_13aug2013_v0')
      DO I=1,20
      READ(8,*)
      ENDDO
      II=0
      DO 90 II=1,IMNMX
      READ(8,'(I5,12I4,I5)')IMN,(FMN(J),J=1,12),FTOT
      RTOT=0.
      DO J=1,12
      RTOT=RTOT+FLOAT(FMN(J))
      ENDDO
      IMNSV(II)=IMN
      IF(RTOT.GT.0.)THEN
      FSCMN(II)=FLOAT(FMN(IMONTH))/RTOT
      ELSE
      WRITE(7,*)' No monthly variation,IMN= ',IMN
      WRITE(*,*)' No monthly variation,IMN= ',IMN
C     STOP777
      ENDIF
  90  CONTINUE
      WRITE(*,*)'Reading week TAF and assigning to SCC'
      READ(8,*)
      READ(8,*)
      DO 91 II=1,IWKMX
      READ(8,'(I5,7I4,I6)')IWK,(FWK(J),J=1,7),FTOT
      IWKSV(II)=IWK
      DO J=1,7
      FSCWK(II,J)=FLOAT(FWK(J))/FLOAT(FTOT)
      ENDDO
C     WRITE(7,*)'II,IWKSV=',II,IWKSV(II)
  91  CONTINUE
      WRITE(*,*)'Reading day TAF and SCC assign,IDYoWK=',IDYoWK
      WRITE(7,*)'Reading day TAF and SCC assign,IDYoWK=',IDYoWK
      IF(IDYoWK.LE.0.OR.IDYoWK.GT.7)THEN
      WRITE(*,*)'IDYoWK= ',IDYoWK,' dont know what to do,stopping'
      STOP777
      ENDIF
C 3/14/15 Fix hourly temporal factor for weekends. Use Monday for weekday
C     ISKIP=2+(IDYoWK-1)*(IDYMX+2)
      IDYskip=1
      IF(IDYoWK.EQ.2)IDYskip=6
      IF(IDYoWK.EQ.3)IDYskip=7
      ISKIP=2+(IDYskip-1)*(IDYMX+2)
      DO I=1,ISKIP
      READ(8,*)
      ENDDO
      DO 92 II=1,IDYMX
      READ(8,'(I5,24I4,I5)')IDY,(FDY(J),J=1,24),FTOT
      RTOT=0.
      DO J=1,24
      RTOT=RTOT+FLOAT(FDY(J))
      ENDDO
      IDYSV(II)=IDY
      DO J=1,24
C     FSCDY(II,J)=FLOAT(FDY(J))/FLOAT(FTOT)
      FSCDY(II,J)=FLOAT(FDY(J))/RTOT
      ENDDO
C     WRITE(7,*)'II,IDYSV=',II,IDYSV(II)
C     CALL FLUSH(7)
  92  CONTINUE
      CLOSE(8)
      ENDIF  ! endof IF(ITIMES.EQ.1)THEN
      WRITE(*,*)'Reading SCC-TAF cross reference, setting up indexing'
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
C 3/13/14 - Following file has temporal profiles not in NEI-11 release
C But it has FIP dependent NH3 emissions
      IF(NAM(1:LLET).EQ.'NH3')THEN
      OPEN(8,FILE='/wrk/d1/stu/nei11/EPAdata/v1platform/ge_dat/Gentpro_T
     -REF_HOURLY_BASH_NH3_agNH3_bash_2011ea_11f_newgent_emf_txt_06sep201
     -3_nf_v4')
      IHEAD=21
      ELSE
      OPEN(8,FILE='/wrk/d1/stu/nei11/EPAdata/v1platform/ge_dat/Gentpro_T
     -REF_DAILY_RWC_RWC_2011_28jun2013_v1')
      IHEAD=6
      ENDIF
      DO I=1,IHEAD
      READ(8,*)
      ENDDO
      II=0
 9    CONTINUE
      IMN=0
      IWK=0
      IDY=0
      POL=''
      IFIP=0
      CFIP=''
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
      READ(8,*,END=10)SCC,IMN,IWK,IDY,POL,CFIP
      IF(CFIP.NE.'')THEN
      READ(CFIP,'(I)')IFIP
      ENDIF
C Kick out Canadian profiles 12/19/08
      IF(IFIP.GT.100000)GOTO 9
      DO 75 I=1,ISCCMX
      ISAV=0
      IF(SCC.EQ.SCCNUM(I))THEN
C A match to emission file SCC was found
      LSPN=LNBLNK(POL)
      IF(POL.EQ.''.OR.(NAM(1:LLET).EQ.POL(1:LSPN)))THEN
      IF(ISAV.EQ.0)ISAV=1 ! Default SCC - independent of species
      ELSEIF(NAM(1:LSPN).EQ.POL(6:6+LSPN-1))THEN ! Species dependent exhaust or evap found
        WRITE(*,*)'Bad TAF -like onnonroad,SCC,POL,NAM=',SCC,POL,NAM
        WRITE(7,*)'Bad TAF -like onnonroad,SCC,POL,NAM=',SCC,POL,NAM
        STOP777
      ENDIF
      LSPN=MAX(1,LSPN)
      ENDIF ! SCC = SCCNUM(I) test
      IF(ISAV.EQ.0)THEN
      GOTO 75
      ELSE
C 12/22/08 - Have I (SCC index number) now determine IFIP index number
C Index number 1 is the default (IFIP in readin = 0 (or not specified))
C Check to make sure IFIP is valid (within IFIPNM)
      DO II=1,IFIPMX
      IF(IFIP.EQ.IFIPNM(II))THEN
      IFIPADD=II
      GOTO 20
      ENDIF
      ENDDO
      WRITE(7,*)'IFIP=',IFIP,' not in IFIPNM, stopping'
      WRITE(*,*)'IFIP=',IFIP,' not in IFIPNM, stopping'
      STOP777
 20   CONTINUE
C Find index numbers to use for this SCC/Emistype
      IDWKDEX=0
      DO II=1,IWKMX
      IF(IWKSV(II).EQ.IWK)THEN
      IDWKDEX=II
      ENDIF
      ENDDO
      IDDYDEX=0
      DO II=1,IDYMX
      IF(IDYSV(II).EQ.IDY)THEN
      IDDYDEX=II
      ENDIF
      ENDDO
      IMONDEX=0
      DO II=1,IMNMX
      IF(IMNSV(II).EQ.IMN)THEN
      IMONDEX=II
C 12/23/08 Agricultural burning of grasses, ground crops set to monthly temporal factor of Ag burning for all types (2801500000)
C Otherwise, there is large summertime crop burning sources for grass, hay, etc.
      IF(SCC(1:8).EQ.'28015001')IMONDEX=14
C 12/23/08
      ENDIF
      ENDDO
       IF(IMONDEX.EQ.0.OR.IDDYDEX.EQ.0.OR.IDWKDEX.EQ.0)THEN
       WRITE(*,*)'TAF Index problem,SCC,POL,NAM=',SCC,POL,NAM
       WRITE(*,*)'IMONDEX,IDDYDEX,IDWKDEX=',IMONDEX,IDDYDEX,IDWKDEX
C      STOP777
       ENDIF
         IDWK(I,IFIPADD)=IDWKDEX
         IDDY(I,IFIPADD)=IDDYDEX
         IDMN(I,IFIPADD)=IMONDEX
      WRITE(7,'(I5,1X,A10,1X,A,A,2I6,A,2I6,A,2I6,A,2I6,A)')
     -I,SCCNUM(I),POL(1:LSPN),' week=(',IDWKDEX,IWKSV(IDWKDEX),') day=('
     -,IDDYDEX,IDYSV(IDDYDEX),') month=(',IMONDEX,IMNSV(IMONDEX),'), IFI
     -PADD,IFIPNM= (',IFIPADD,IFIPNM(IFIPADD),')'
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
      ENDIF ! Endof IF(ISAV.EQ.0) or not IF,ELSE
 75   CONTINUE ! Endof I=1,ISCCMX loop
      GOTO 9
 10   CONTINUE
      CLOSE(8)
C Check for SCCs without TAF assignment
      DO I=1,ISCCMX
      ITES=0
      DO J=1,IFIPMX
      IF(IDMN(I,J).NE.0)ITES=1
      ENDDO
      IF(ITES.EQ.0)THEN
      WRITE(7,'(A,A10)')'Stop: No MNoYR TAF found for SCC= ',SCCNUM(I)
      WRITE(*,'(A,A10)')'Stop: No MNoYR TAF found for SCC= ',SCCNUM(I)
C     STOP777
      IDMN(I,1)=262  ! Apply constant month of year profile if missing NEI-17 monthly TAF
      ENDIF
      ITES=0
      DO J=1,IFIPMX
      IF(IDWK(I,J).NE.0)ITES=1
      ENDDO
      IF(ITES.EQ.0)THEN
      WRITE(7,'(A,A10)')'Stop: No dayoWK TAF found for SCC= ',SCCNUM(I)
      WRITE(*,'(A,A10)')'Stop: No dayoWK TAF found for SCC= ',SCCNUM(I)
C     STOP777
      IDWK(I,1)=7  ! Apply constant day of week profile if missing NEI-17 week TAF
      ENDIF
      ITES=0
      DO J=1,IFIPMX
      IF(IDDY(I,J).NE.0)ITES=1
      ENDDO
      IF(ITES.EQ.0)THEN
      WRITE(7,'(A,A10)')'Stop: No HRoDY TAF found for SCC= ',SCCNUM(I)
      WRITE(*,'(A,A10)')'Stop: No HRoDY TAF found for SCC= ',SCCNUM(I)
C     STOP777
      IDDY(I,1)=24  ! Apply constant hour of day profile if missing NEI-17 week TAF
      ENDIF
      ENDDO
      RETURN
      END
C *******************************************************************
      SUBROUTINE VOCPRFC
      include 'commons/parame.h'
      include 'commons/suridex.h'
      include 'commons/vocidex.h'
      include 'commons/names.h'
      include 'commons/tafidex.h'
C===============================================================================
C
C  This program  converts Speciate 4.3 VOC profile assignments to SAPRAC99 lumped
C  species assignments plus any other species separated out.
C  Matrices  PRFLUMP (matrix assignment of Lumped SAPRAC99 species to speciation code number)
C and ISCCVOC (Profile number in NPRFSV assigned to input SCC codes) are the elements
C needed in subroutine VOCSPEC to accumulate VOC emissions into gridded fields
C The units of speciation file PRFLUMP are in moles per kilogram of VOC emitted.
C===============================================================================
      CHARACTER*80 INDRVOC
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
C     DIMENSION INUMONR(NEMTYPE),IPRFOUT(NEMTYPE)
      CHARACTER*9 CHARP
      CHARACTER*10 CNUM,CDUM,CDUMPNM,CPRFSV,CNUMONR,CPRFOUT
      CHARACTER*9 CDUMSPC
      CHARACTER*6 OGPRF(27),CIFIPN  ! 7/11/20 updated 27 OnG basin specific profiles to speciate 4.5
      DIMENSION CPRFSV(IVOCPMX)
C     SAPRC07T (toxics) Lumped Species Variables in TOGspec_2_SAPRACspec.txt file 8/21/08
C     DATA INDRVOC/'/home/stu/emis/em11/vocspec/'/
C     DATA INDRVOC/'/home/stu/emis/em14/vocspec/'/
      DATA INDRVOC/'/home/stu/emis/em17/vocspec/'/
C Gas composition analysis profiles are an averaged profiles from data provided by producers
C(01) DJFLA - DJ Basin Flashing Gas Composition for Condensate
C(02) DJVNT - DJ Basin Produced Gas Composition
C(03) FLR70 - ?? Basin ??
C(04) FLR88 - ?? Basin ??
C(05) FLR97 - ?? Basin ??
C(06) FLR99 - ?? Basin ??
C(07) PNC01 - Piceance Basin Gas Composition at Conventional Wells
C(08) PNC02 - Piceance Basin Gas Composition at Oil Wells
C(09) PNC03 - Piceance Basin Flashing Gas Composition for Condensate
C(10) PNCDH - Piceance Basin ??
C(11) PRBCB - Powder River Basin Produced Gas Composition for CBM Wells
C(12) PRBCO - Powder River Basin Produced Gas Composition for Conventional Wells
C(13) PRM01 - Permian Basin Produced Gas Composition
C(14) SSJCB - South San Juan Basin Produced Gas Composition for CBM Wells
C(15) SSJCO - South San Juan Basin Produced Gas Composition for Conventional Wells
C(16) SWFLA - SW Wyoming Basin Flash Gas Composition
C(17) SWVNT - SW Wyoming Basin Vented Gas Composition
C(18) UNT01 - Uinta Basin Gas Composition at CBM Wells
C(19) UNT02 - Uinta Basin Gas Composition at Conventional Wells
C(20) UNT03 - Uinta Basin Flashing Gas Composition for Oil
C(21) UNT04 - Uinta Basin Flashing Gas Composition for Condensate
C(22) WRBCO - Wind River Basin Produced Gas Composition for Conventional Wells
C(23) WIL01 - Williston Basin Produced Gas Composition for Conventional Wells
C(24) WIL02 - Williston Basin Produced Gas Composition for Conventional Wells
C(25) WIL03 - Williston Basin Produced Gas Composition for Conventional Wells
C(26) WIL04 - Williston Basin Produced Gas Composition for Conventional Wells
C(27) CMU01 - Central MT Uplift Produced Gas Composition for Conventional Wells
C
C(23) 8750a - Text profile converted to number 9023 6/28/19
C(24) 8751a - Text profile converted to number 9024 6/28/19
C(25) 95087a - Text profile converted to number 9025 6/28/19
C(26) 95109a - Text profile converted to number 9026 6/28/19
C (CSC note: 2487 used for oil SCCs in basins without an oil-specific profile.)
      DATA OGPRF/'DJFLA','DJVNT','FLR70','FLR88','FLR97','FLR99','PNC01'
     -,'PNC02','PNC03','PNCDH','PRBCB','PRBCO','PRM01','SSJCB','SSJCO',
     -'SWFLA','SWVNT','UNT01','UNT02','UNT03','UNT04','WRBCO','WIL01',
     -'WIL02','WIL03','WIL04','UCM01'/
C    -'SWFLA','SWVNT','UNT01','UNT02','UNT03','UNT04','WRBCO','8750a',
C    -'8751a','95087a','95109a'/
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
      SAVE
      WRITE(*,*)'Processing NEI-2017 VOC profiles, SPECIES= ',NAM
      WRITE(7,*)'Processing NEI-2017 VOC profiles, SPECIES= ',NAM
      PRFLUMP=0.
      ISCCVOC=-999
      LBET=LNBLNK(INDRVOC)
C     OPEN(5,FILE=INDRVOC(1:LBET)//'saprc99_VOCprflassign.txt')
C     OPEN(5,FILE=INDRVOC(1:LBET)//'OnG_saprc99_VOCprflassign.txt')
C     OPEN(5,FILE=INDRVOC(1:LBET)//'OnG_sprc11_VOCprfls_XTRA.txt')
      OPEN(5,FILE=INDRVOC(1:LBET)//'SPECT5p0_VOCprfls.txt')
      REWIND(5)
      DO I=1,IVOCPMX
      READ(5,'(A,1X,I2)')CPRFSV(I),JNUM
      WRITE(*,*)I,CPRFSV(I),JNUM
      CALL FLUSH(6)
      DO J=1,JNUM
      READ(5,'(I2,1X,A10,1X,E10.3)')INUM,CDUM,DUM
      PRFLUMP(INUM,I)=DUM
      ENDDO
      ENDDO
      CLOSE(5)
C 10/30/08 Do original way for on/non road - Speciate4.3 SCC to VOC profile assignments only
C gives top 80%, or about 148 entries.  They all have the same value for on/non road categories.
C This differs from SMOKE files on EPA web-site designed for nei2002.  But the EPA SMOKE files
C only have about 140 SCC to VOC profile entries as well.  Go for Speciate4.0 as primary
C info for gas, and diesel vehicles - Onroad in particular.  
C     INDRVOC='/home/stu/emis/em05/EPAdata/'
C     INDRVOC='/wrk/d1/stu/d1/nei2005/EPAdata/ptinv/ancillary/cap/'
C     INDRVOC='/wrk/d1/stu/nei11/EPAdata/v1platform/ge_dat/'
C     INDRVOC='/wrk/d2/stu/nei14/EPAdata/ge_dat/speciation/'
      INDRVOC='/home/stu/emis/em17/EPAdata/'
      LBET=LNBLNK(INDRVOC)
C     OPEN(5,FILE=INDRVOC(1:LBET)//'gsref.SMOKE.cb4p25_wtox.txt')
C 12/9/08 try the gsref file that came with 2002 NEI download - the SMOKE file missed hundreds
C     OPEN(5,FILE=INDRVOC(1:LBET)//'gsref_2002_cb05_cap4_11dec2007_v3.tx
C    -t')
C 11/12/13 try the gsref file that came with NEI11-v1 v1platform ge_dat download
C     OPEN(5,FILE=INDRVOC(1:LBET)//'gsref_cmaq_cb05_soa_2011ec_v6_11f_on
C    -road_06sep2013.txt')
C 6/28/19 try the gsref file that came with NEI4v2
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
C     OPEN(5,FILE=INDRVOC(1:LBET)//'gsref_cmaq_cb6_2014fa_nata_cb6cmaq_1
C    -4j.txt')
C 7/9/20 try the gsref file that came with NEI7v1
      OPEN(5,FILE=INDRVOC(1:LBET)//'gsref_ag_cmaq_cb6ae7_2017gb_17j_nf.t
     -xt')
      REWIND(5)
C     DO I=1,46
C     DO I=1,319
C     DO I=1,296
      DO I=1,194
      READ(5,*)
      ENDDO
      JJ=0
      II=0        ! Keep track of profiles found
 19   CONTINUE
      IFIPN=0
C     READ(5,'(A10,1X,A5,2X,A8)',END=18)CDUM,CDUMPNM,CDUMSPC
C     READ(5,*,END=18)CDUM,CDUMPNM,CDUMSPC,IFIPN
      READ(5,*,END=18)CDUM,CDUMPNM,CDUMSPC,CIFIPN
      READ(CIFIPN,'(I)')IFIPN
C 6/29/19 Ignore Canada/Mexico IFIPS
      IF(IFIPN.GE.100000)GOTO 19
      JJ=JJ+1
      LDUM=LNBLNK(CDUM)
      LDUMPNM=LNBLNK(CDUMPNM)
      LDUMSPC=LNBLNK(CDUMSPC)
      LDST=MAX(1,LDUMSPC-2)
      CNUMONR='-999'
      IF(CDUMSPC(1:3).EQ.'VOC'.OR.CDUMSPC(1:9).EQ.'NONHAPVOC')THEN
C     IF(CDUMSPC(1:3).EQ.'VOC')THEN
C     IF(CDUMSPC(1:9).EQ.'NONHAPVOC')THEN
C     IF(CDUMSPC(1:3).EQ.'VOC'.AND.IFIPN.EQ.0)THEN  ! Ignore county specific stuff for now, 11/14/13
      DO 20 I=1,ISCCMX
      IF(SCCNUM(I).EQ.CDUM(1:LDUM))THEN
      WRITE(7,'(A,A,A,1X,A)')SCCNUM(I),' VOCprfnum,Spc_lbl= ',CDUMPNM,
     -CDUMSPC
      CALL FLUSH(7)
      CNUMONR=CDUMPNM
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
      IF((CDUM(1:4).EQ.'2501'.OR.CDUM(1:4).EQ.'2505'.OR.CDUM(1:4).EQ.'26
     -60'.OR.CDUM(1:4).EQ.'2635').AND.CDUMPNM(1:5).EQ.'COMBO')THEN  ! Ignore COMBO files for gas-can/transport SCCs - used old NEI05 assignment
      CNUMONR='1305'
      WRITE(7,'(A,A,A,1X,A)')SCCNUM(I),' VOCprfnum,Spc_lb2= ',CNUMONR,
     -CDUMSPC
      CALL FLUSH(7)
      ENDIF
      IF(CNUMONR(1:5).EQ.'95531')CNUMONR='95331' ! No 95531 profile, a bug in gsref file, SAM 7/13/20
      CNUM=CNUMONR
C     IF(INUM.EQ.-999)GOTO 23
      IF(trim(CNUM).EQ.'-999')THEN
C 11/19/13 - Punt, no available VOC profile, includes mainly agriculture, fertilizer - which have 0 profile for similar classes.
      WRITE(7,'(2A)')SCCNUM(I),' No assign, Fill to VOCprof 0 '
      CNUM=''
      ENDIF
      II=II+1     ! Keep track of profiles found
      DO 23 J=1,IVOCPMX
C     WRITE(7,*)'J,INUM,NPRFSV=',J,INUM,NPRFSV(J);call flush(7)
      IF(trim(CNUM).EQ.trim(CPRFSV(J)))THEN
      IF(ISCCVOC(I,1).LT.0)THEN  ! Index 1 is entire US for IFIPNM
      DO JJ=1,IFIPMX
      ISCCVOC(I,JJ)=J
      ENDDO
      ELSE ! Below means ISCCVOC(I,1).GE.0
      IF(IFIPN.NE.0)THEN
C Check to make sure IFIP is valid (within IFIPNM)
      DO JJ=1,IFIPMX
      IF(IFIPN.EQ.IFIPNM(JJ))THEN
      IFIPADD=JJ
      GOTO 29
      ENDIF
      ENDDO
      WRITE(7,*)'IFIPN=',IFIPN,' not in IFIPNM VOCPRFC, stopping'
      WRITE(*,*)'IFIPN=',IFIPN,' not in IFIPNM VOCPRFC, stopping'
      DO II=1,IFIPMX
      WRITE(7,*)'II,IFIPNM=',II,IFIPNM(II)
      ENDDO
      CALL FLUSH(7)
      STOP777
 29   CONTINUE
      ISCCVOC(I,JJ)=J
      GOTO 19
      ENDIF ! ENDofIF(IFIPN.NE.0)THEN
C     WRITE(7,*)' Duplct Prfl assgn,SCC,prf= ',SCCNUM(I),NPRFSV(J)
C     WRITE(*,*)' Duplct Prfl assgn,SCC,prf= ',SCCNUM(I),NPRFSV(J)
C     STOP777
      ENDIF  ! ENDofIF(ISCCVOC(I,1).LT.0)THEN/ELSE  ! Index 1 is entire US for IFIPNM
      WRITE(7,'(A10,A,I5)')SCCNUM(I),' VOCprofnum=',J
      GOTO 24
      ENDIF  !ENDofIF(CNUM.EQ.CPRFSV(J))THEN
 23   CONTINUE
      WRITE(*,'(A,A10,1X,A)')'No SCCprfassign match to SCC,INUM= ',
     -SCCNUM(I),CNUM
      WRITE(7,'(A,A10,1X,A)')'No SCCprfassign match to SCC,INUM= ',
     -SCCNUM(I),CNUM
      STOP'777'
 24   CONTINUE
      GOTO 19
      ENDIF  ! End of (SCCNUM(I).EQ.CDUM(1:LDUM)) test
 20   CONTINUE
      GOTO 19
      ENDIF ! End of IF(CDUMSPC(1:3).EQ.'VOC'.OR.CDUMSPC(1:9).EQ.'NONHAPVOC') Test
      GOTO 19
 18   CONTINUE
      WRITE(7,*)JJ,' VOCPRFC Total Profl recs,',II,' total assigns'
      WRITE(*,*)JJ,' VOCPRFC Total Profl recs,',II,' total assigns'
      ITRAK=0
      DO I=1,ISCCMX
      II=0     ! Keep track of profiles found
      CPRFOUT='-999'
      J=ISCCVOC(I,1)
      IF(J.NE.-999)THEN
      II=II+1  ! Keep track of profiles found
      CPRFOUT=CPRFSV(J)
      ENDIF
      IF(II.EQ.0)ITRAK=ITRAK+1
      WRITE(7,*)I,SCCNUM(I),CPRFOUT
      ENDDO
      IF(ITRAK.GT.0)THEN
      WRITE(*,*)ITRAK,' Missing VOC profile assignments, not stopping'
      WRITE(7,*)ITRAK,' Missing VOC profile assignments, not stopping'
C     STOP777
      ENDIF
      WRITE(*,*)'VOC SCC to profile assign done '
      WRITE(7,*)'VOC SCC to profile assign done '
C     ISTOP=1
C     IF(ISTOP.EQ.1)STOP999
      RETURN
      END
C *******************************************************************
      SUBROUTINE VOCSPEC(ISC,IFIP,IFIPTV,II,JJ,ELEMADD,IHRDIF)
      include 'commons/parame.h'
      PARAMETER(IBADMX=5)
      PARAMETER(IHCRECL=4*IVOC*24)
      include 'commons/suridex.h'
      include 'commons/vocidex.h'
      include 'commons/tafidex.h'
      include 'commons/timvari.h'
      include 'commons/names.h'
C===============================================================================
      DIMENSION SCRAT(IX,JX),A(24,IVOC)
C Units of VOC emissions (VOCEM) are moles per (4km) grid square per hour
      CHARACTER*10 SCCBADSV(IBADMX)
      INTEGER STATUS,SYSTEM
      CHARACTER*4 HCFILNM,HRNAM
      CHARACTER*12 OUDIRF
      CHARACTER*20 FIL
      LOGICAL EXISTS
      DATA ITIMS,ISAV/0,0/
      DATA KGPERTON/907.18/
      SAVE
      ITIMS=ITIMS+1
      IF(ITIMS.EQ.1)THEN
      INQUIRE(FILE='VOCspec',EXIST=EXISTS)
      IF(.NOT.EXISTS)THEN
      WRITE(*,*)'VOCspec directory  DOESNT EXIST, making it'
      STATUS=SYSTEM('mkdir VOCspec')
      ENDIF
      IF(ITIMVAR.EQ.1)THEN
      INQUIRE(FILE='tmpdira',EXIST=EXISTS)
      IF(.NOT.EXISTS)THEN
      WRITE(*,*)'tmpdira directory  DOESNT EXIST, making it'
      STATUS=SYSTEM('mkdir tmpdira')
      ELSE  ! erase anything in tmpdira
      WRITE(*,*)'tmpdira directory  EXISTS, erasing VOC file'
      STATUS=SYSTEM('rm -rf tmpdira/HCtv')
      ENDIF
      DO ISP=1,IVOC
      DO I=1,24
      A(I,ISP)=0.
      ENDDO
      ENDDO
      WRITE(HCFILNM,'(A4)')'HCtv'
      OUDIRF='tmpdira/'//HCFILNM
      IUN=11
      OPEN(UNIT=IUN,FILE=OUDIRF,ACCESS='DIRECT',RECL=IHCRECL,
     -FORM='UNFORMATTED')
      N0=0
      DO 2 J=1,JX
      DO 2 I=1,IX
      N0=N0+1
      WRITE(IUN,REC=N0)A
 2    CONTINUE
      WRITE(*,16)OUDIRF,IUN,N0
 16   FORMAT('WRITTEN TO ',A12,' UNIT=',I2,' N=',I7)
      DO IHR=1,24
      WRITE(HRNAM,'(A2,I2.2)')'HR',IHR
      INQUIRE(FILE=HRNAM,EXIST=EXISTS)
      IF(.NOT.EXISTS)THEN
      WRITE(*,*)'Hour directory ',HRNAM,'  DOESNT EXIST, making it'
      STATUS=SYSTEM('mkdir '//HRNAM)
      ENDIF
      ENDDO
      INQUIRE(FILE='dayav',EXIST=EXISTS)
      IF(.NOT.EXISTS)THEN
      WRITE(*,*)'dayav directory DOESNT EXIST, making it'
      STATUS=SYSTEM('mkdir dayav')
      ENDIF
      ENDIF   !IF(ITIMVAR=1)
      ELSEIF(ISC.LT.0)THEN
C
      IF(ITIMVAR.EQ.1)THEN
      WRITE(7,*)' WRITING ',IVOC,' VOC hourly variation file'
      CALL FLUSH(7)
      IUN=11
      DO ISP=1,IVOC
      WRITE(HCFILNM,'(A2,I2.2)')'HC',ISP
C Modify for putting hourly 2-D emission files in subdirectories HR01,HR02,HR03......
      DO 15 IHR=1,24
      WRITE(HRNAM,'(A2,I2.2)')'HR',IHR
      FIL=HRNAM//'/'//HCFILNM
      OPEN(8,FILE=FIL,FORM='FORMATTED')
      ETOT=0.
      EMAX=-1.E30
      IN=0
      DO J=1,JX
      DO I=1,IX
      IN=IN+1
      READ(IUN,REC=IN)A
      SCRAT(I,J)=A(IHR,ISP)
      ETOT=ETOT+SCRAT(I,J)
      IF(SCRAT(I,J).GT.EMAX)THEN
      EMAX=SCRAT(I,J)
      IMAX=I
      JMAX=J
      ENDIF
      ENDDO
      ENDDO
      WRITE(8,'(1P12E9.2)')SCRAT
      CLOSE(8)
      LLET3=LNBLNK(FIL)
      STATUS=SYSTEM('nohup gzip -f '//FIL(1:LLET3)//'&')
      WRITE(7,'(A,I2,1X,A,A,1P,2E11.4,2I5)')'Hr ',IHR-1,NAMVOC(ISP),
     -' Totl,Max,I,J= ',ETOT,EMAX,IMAX,JMAX
 15   CONTINUE
      WRITE(*,'(A,A)')'24hr write= ',NAMVOC(ISP)
      WRITE(7,'(A,A)')'24hr write= ',NAMVOC(ISP)
      FIL='dayav/'//HCFILNM
      LLET3=LNBLNK(FIL)
      OPEN(8,FILE=FIL,FORM='FORMATTED')
C Refill SCRAT with daily average from hourly temp files, units of short ton per day per 4km grid
      SCRAT=0.
      DO IHR=1,24
      IN=0
      DO J=1,JX
      DO I=1,IX
      IN=IN+1
      READ(IUN,REC=IN)A
      SCRAT(I,J)=SCRAT(I,J)+A(IHR,ISP)
      ENDDO
      ENDDO
      ENDDO
      ETOT=0.
      EMAX=-1.E30
      DO I=1,IX
      DO J=1,JX
      ETOT=ETOT+SCRAT(I,J)
      IF(SCRAT(I,J).GT.EMAX)THEN
      EMAX=SCRAT(I,J)
      IMAX=I
      JMAX=J
      ENDIF
      ENDDO
      ENDDO
      WRITE(8,'(1P12E9.2)')SCRAT
      CLOSE(8)
      STATUS=SYSTEM('nohup gzip -f '//FIL(1:LLET3)//'&')
      WRITE(7,'(2A,1P2E10.3,2I5)')NAMVOC(ISP),
     -' Diurn Totl(ton/dy),Max,I,J=',ETOT,EMAX,IMAX,JMAX
      WRITE(*,'(2A,1P2E10.3,2I5)')NAMVOC(ISP),
     -' Diurn Totl(ton/dy),Max,I,J=',ETOT,EMAX,IMAX,JMAX
      ENDDO   !ISP=1,IVOC
      ENDIF   !IF ITIMVAR=1
      CLOSE(IUN)
      RETURN
      ENDIF
      IF(ISCCVOC(ISC,IFIP).EQ.-999)THEN
      IF(ISAV.EQ.0)THEN
      ISAV=1
      SCCBADSV(ISAV)=SCCNUM(ISC)
      WRITE(7,'(A,A10)')'No VOC assign to SCC=',SCCNUM(ISC)
      GOTO 3
      ELSE
      DO I=1,ISAV
      IF(SCCNUM(ISC).EQ.SCCBADSV(I))GOTO 3
      ENDDO
      ISAV=ISAV+1
      IF(ISAV.GT.IBADMX)THEN
      WRITE(*,*)'Bad SCCs-no VOC profile > ',IBADMX,' stopping'
      WRITE(7,*)'Bad SCCs-no VOC profile > ',IBADMX,' stopping'
      STOP777
      ENDIF
      SCCBADSV(ISAV)=SCCNUM(ISC)
      ENDIF
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
      WRITE(7,'(A,A10)')'No VOC assign to SCC=',SCCNUM(ISC)
      ELSE
C Everything OK for updating VOCEM matrices, VOCEM in mole per hr per (4km) grid
      IPRF=ISCCVOC(ISC,IFIP)
      FAC=ELEMADD*KGPERTON/24.
      IUN=11
      JB=JJ-1
      IN=JB*IX+II
      READ(IUN,REC=IN)A
      DO I=1,IVOC
      IF(PRFLUMP(I,IPRF).GT.0.)THEN
      ELEMVOC=PRFLUMP(I,IPRF)*FAC
C     VOCEM(I,II,JJ)=VOCEM(I,II,JJ)+ELEMVOC
C     VOCEM(ISC,I)=VOCEM(ISC,I)+ELEMVOC
C Save hourly emissions if ITIMVAR=1
      IF(ITIMVAR.EQ.1)THEN
      IWKDX=IDWK(ISC,IFIPTV)
      IDYDX=IDDY(ISC,IFIPTV)
      IF(IWKDX.LE.0.OR.IDYDX.LE.0)THEN
      IF(ISAV.EQ.0)THEN
      ISAV=1
      SCCBADSV(ISAV)=SCCNUM(ISC)
      WRITE(7,'(A,A10)')'No taff assign to SCC= ',SCCNUM(ISC)
      GOTO 3
      ELSE
      DO K=1,ISAV
      IF(SCCNUM(ISC).EQ.SCCBADSV(K))GOTO 3
      ENDDO
      ISAV=ISAV+1
      IF(ISAV.GT.IBADMX)THEN
      WRITE(*,*)'Bad SCCs-no July temp profile > ',IBADMX,' stopping'
      STOP777
      ENDIF
      SCCBADSV(ISAV)=SCCNUM(ISC)
      ENDIF
      WRITE(7,'(A,A10)')'No July_taff assign to SCC= ',SCCNUM(ISC)
C Only found 1 SCC=2801500000 in area files that has July TAFF=0, but want
C to keep OSD numbers even though TAFF assign to annual is zero, change ELSE
C to endif to continue
      ENDIF   !IF(IWKDX.LE.0.OR.IDYDX.LE.0)THEN
C VOC Emission ELEMVOC is in mole/hr per 4 km grid square for SSD (summer season day)
      FACDY=1.
      IF(IDYoWK.EQ.1)THEN   !Weekday (M-F) emission
      FACDY=(FSCWK(IWKDX,1)+FSCWK(IWKDX,2)+FSCWK(IWKDX,3)+FSCWK(IWKDX,4)
     -+FSCWK(IWKDX,5))*7./5.
      ELSEIF(IDYoWK.EQ.2)THEN   !Saturday emission
      FACDY=FSCWK(IWKDX,6)*7.
      ELSEIF(IDYoWK.EQ.3)THEN   !Sunday emission
      FACDY=FSCWK(IWKDX,7)*7.
      ENDIF
      DO IHR=1,24
C IHRPLAC= 1 for UTC00-UTC01, =2 for UTC01-UTC02,...etc.
      IHRPLAC=1+MOD(IHR-1+IHRDIF,24)
      A(IHRPLAC,I)=A(IHRPLAC,I)+ELEMVOC*FACDY*FSCDY(IDYDX,IHR)*24.
      ENDDO
      ENDIF   !IF ITIMVAR=1
      ENDIF   !IF (PRFLUMP(I,IPRF).GT.0.)
      ENDDO   !I=1,IVOC
      WRITE(IUN,REC=IN)A
C Hourly VOC emission files - units in moles/hr per 4km grid square
      ENDIF
 3    CONTINUE
      RETURN
      END
      SUBROUTINE PM2PRFC
      include 'commons/parame.h'
      include 'commons/suridex.h'
      include 'commons/pm2idex.h'
      include 'commons/names.h'
C     include 'commons/tafidex.h'
C===============================================================================
C
C  This program  converts PM2.5 profile assignments to SAPRAC99 lumped
C  species assignments plus any other species separated out.
C 2/26/14, Using gspro and gsref files from v1platform that came with NEI-2011
C 2/26/14, rather than Speciate 4.3.
C  Matrices  PRFLPM2 (matrix assignment of EPA PM2.5 species to speciation code number)
C and ISCCPM2 (Profile number in NPRFSV assigned to input SCC codes) are the elements
C needed in subroutine PM2SPEC to accumulate PM25 emissions into gridded fields
C The units of speciation file PRFLPM2 are in fractions of mass assigned to each PM2.5 species
C===============================================================================
      CHARACTER*80 INDRVOC
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
      DIMENSION CPRFSV(IPM2PMX)
C     DIMENSION INUMONR(NEMTYPE),IPRFOUT(NEMTYPE)
      CHARACTER*9 CHARP
      CHARACTER*10 CNUM,CNUMONR
      CHARACTER*10 CDUM,SPNDUM,CPRFSV,CPRFO,CDUMPNM,CDUMSPC
      CHARACTER*1 CHAR1
C     SAPRC07T (toxics) Lumped Species Variables in TOGspec_2_SAPRACspec.txt file 8/21/08
C     DATA INDRVOC/'/wrk/d1/stu/nei11/EPAdata/v1platform/ge_dat/'/
C     DATA INDRVOC/'/wrk/d2/stu/nei14/EPAdata/ge_dat/speciation/'/
      DATA INDRVOC/'/home/stu/emis/em17/EPAdata/'/
      SAVE
      WRITE(*,*)'Processing NEI-2017 PM25 profiles'
      WRITE(7,*)'Processing NEI-2017 PM25 profiles'
      PRFLPM2=0.
      ISCCPM2=-999
      LBET=LNBLNK(INDRVOC)
C     OPEN(5,FILE=INDRVOC(1:LBET)//'gspro_cmaq_cb05_soa_2011ec_v6_11f_be
C    -is_nf.txt')
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
C     OPEN(5,FILE=INDRVOC(1:LBET)//'gspro_cmaq_cb6_2014fa_nata_cb6cmaq_1
C    -4j_criteria.txt')
      OPEN(5,FILE=INDRVOC(1:LBET)//'gspro_cmv_c1c2_12_cmaq_cb6ae7_2017gb
     -_17j_01may2020.txt')
      REWIND(5)
C Determine number of header lines, rewind file, read to first line of data
      IHEAD=0
 98   CONTINUE
      READ(5,'(1A)')CHAR1
      IF(CHAR1.NE.'#')GOTO 99
      IHEAD=IHEAD+1
      GOTO 98
 99   CONTINUE
      IHEAD=IHEAD+1
      REWIND(5)
      WRITE(7,*)'PM2PRFC IHEAD= ',IHEAD
      CALL FLUSH(7)
      DO I=1,IHEAD
      READ(5,'(1X)')
      ENDDO
C You are now at beginning of first line.
      CPRFO=''
      I=0
 9    CONTINUE
      READ(5,*,END=10,ERR=11)CDUM,CDUMSPC,SPNDUM,FRC
C     WRITE(7,*)CDUM,CDUMSPC,SPNDUM,FRC
C     WRITE(*,*)CDUM,CDUMSPC,SPNDUM,FRC
C     CALL FLUSH(7)
C     CALL FLUSH(6)
      IF(CDUMSPC(1:5).EQ.'PM2_5')THEN
      IF(len_trim(CDUM).LT.5)GOTO 9 ! For area files all SCCs have profiles with 5 or more characters
C     READ(CDUM,'(I)',ERR=9)NPRFDUM
      IF(trim(CDUM).NE.trim(CPRFO))THEN
      I=I+1
      CPRFSV(I)=CDUM
      WRITE(7,*)'PM25 prof,I,N=',I,CDUM
      WRITE(*,*)'PM25 prof,I,N=',I,CDUM
      CALL FLUSH(7)
      CALL FLUSH(6)
      CPRFO=CDUM
      ENDIF
      L=LNBLNK(SPNDUM)
      DO II=1,IPM25
      CHARP=NAMPM2(II)
      LP=LNBLNK(CHARP)
      IF(SPNDUM(1:L).EQ.CHARP(1:LP))PRFLPM2(II,I)=FRC
      ENDDO
      ENDIF  ! end of IF(CDUMSPC(1:5).EQ.'PM2_5')
      GOTO 9
 11   WRITE(7,*)'Error reading file in PM2PRFC, stopping'
      STOP'777'
 10   CONTINUE
      CLOSE(5)
      WRITE(7,*)'PM2.5 profile assign done, ',I,' profiles found'
      DO II=1,I
C 9/29/20 Newer PM2.5 profiles have PM_FINE fraction = 0, put this fraction
      PRFLPM2(1,II)=0. ! PM_FINE CALC
      DO III=7,IPM25 ! PM_FINE CALC
      PRFLPM2(1,II)=PRFLPM2(1,II)+PRFLPM2(III,II) ! PM_FINE CALC
      ENDDO  ! PM_FINE CALC
      WRITE(7,'(I4,1X,A,1P,20E9.2)')II,CPRFSV(II),(PRFLPM2(J,II),J=1,IPM
     -25)
      ENDDO
C     STOP'999'
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
C 5/22/08 depending on ITYP (1=Exhaust,2=Evap,3=Tire,4=Brake,5=Refill,6=All )
C     OPEN(5,FILE=INDRVOC(1:LBET)//'gsref_cmaq_cb05_soa_2011ec_v6_11f_on
C    -road_06sep2013.txt')
C     OPEN(5,FILE=INDRVOC(1:LBET)//'gsref_cmaq_cb6_2014fa_nata_cb6cmaq_1
C    -4j.txt')
      OPEN(5,FILE=INDRVOC(1:LBET)//'gsref_ag_cmaq_cb6ae7_2017gb_17j_nf.t
     -xt')
      REWIND(5)
C     DO I=1,319
C     DO I=1,296
      DO I=1,194
      READ(5,*)
      ENDDO
      JJ=0
      II=0        ! Keep track of profiles found
 19   CONTINUE
C     READ(5,'(A10,1X,A5,2X,A8)',END=18)CDUM,CDUMPNM,CDUMSPC
      READ(5,*,END=18)CDUM,CDUMPNM,CDUMSPC
      JJ=JJ+1
      LDUM=LNBLNK(CDUM)
      LDUMPNM=LNBLNK(CDUMPNM)
      LDUMSPC=LNBLNK(CDUMSPC)
      LDST=MAX(1,LDUMSPC-4)
      IF(CDUMSPC(1:5).EQ.'PM2_5')THEN
      CNUMONR='-999'
      DO 20 I=1,ISCCMX
      IF(SCCNUM(I).EQ.CDUM(1:LDUM))THEN
C     IF(CDUMPNM(1:1).EQ.'D')CDUMPNM(1:1)='9'
C     READ(CDUMPNM,'(I)')JPROF
C     WRITE(7,'(A,A,I5,1X,A)')SCCNUM(I),' PM25prfnm,Spc_lbl= ',JPROF,
C    -CDUMSPC
      WRITE(7,'(A,A,1X,A)')SCCNUM(I),' PM25prfnm,Spc_lbl= ',CDUMSPC
      CALL FLUSH(7)
C     INUMONR=JPROF
      II=II+1     ! Keep track of profiles found
C     INUM=INUMONR
C     IF(INUM.EQ.-999)GOTO 24
      DO 23 J=1,IPM2PMX
C     IF(INUM.EQ.NPRFSV(J))THEN
      IF(trim(CDUMPNM).EQ.trim(CPRFSV(J)))THEN
      IF(ISCCPM2(I).LT.0)THEN
      ISCCPM2(I)=J
      ELSE
C     WRITE(7,*)' Duplct Prfl assgn,SCC,prf= ',SCCNUM(I),NPRFSV(J)
C     WRITE(*,*)' Duplct Prfl assgn,SCC,prf= ',SCCNUM(I),NPRFSV(J)
      WRITE(7,*)' Duplct Prfl assgn,SCC,prf= ',SCCNUM(I),CDUMPNM
      WRITE(*,*)' Duplct Prfl assgn,SCC,prf= ',SCCNUM(I),CDUMPNM
      STOP777
      ENDIF
      WRITE(7,'(A10,A,I5)')SCCNUM(I),' PM25profnm=',J
      GOTO 24
      ENDIF
 23   CONTINUE
      WRITE(*,'(A,A10)')'No PM_SCCprfassign match to SCC= ',SCCNUM(I)
      WRITE(7,'(A,A10)')'No PM_SCCprfassign match to SCC= ',SCCNUM(I)
      STOP777
 24   CONTINUE
      GOTO 19
      ENDIF  ! End of (SCCNUM(I).EQ.CDUM(1:LDUM)) test
 20   CONTINUE
      GOTO 19
      ENDIF ! End of (CDUMSPC(LDUMSPC-4:LDUMSPC).EQ.'PM2_5') test
      GOTO 19
 18   CONTINUE
      WRITE(7,*)JJ,' PM2PRFC Total Profl recs,',II,' total assigns'
      WRITE(*,*)JJ,' PM2PRFC Total Profl recs,',II,' total assigns'
      ITRAK=0
      DO I=1,ISCCMX
      II=0     ! Keep track of profiles found
      IPRFOUT=-999
      J=ISCCPM2(I)
      IF(J.NE.-999)THEN
      II=II+1  ! Keep track of profiles found
C     IPRFOUT=NPRFSV(J)
      ENDIF
      IF(II.EQ.0)ITRAK=ITRAK+1
C     WRITE(7,*)I,SCCNUM(I),IPRFOUT
      WRITE(7,*)I,J,SCCNUM(I),CPRFSV(J)
      ENDDO
      IF(ITRAK.GT.0)THEN
      WRITE(*,*)ITRAK,' Missing PM25 profile assignments, not stopping'
      WRITE(7,*)ITRAK,' Missing PM25 profile assignments, not stopping'
C     STOP777
      ENDIF
      WRITE(*,*)'PM2.5 SCC to profile assign done '
      WRITE(7,*)'PM2.5 SCC to profile assign done '
C     ISTOP=1
C     IF(ISTOP.EQ.1)STOP999
      RETURN
      END
      SUBROUTINE PM2SPEC(ISC,IFIP,IFIPTV,II,JJ,ELEMADD,IHRDIF)
      include 'commons/parame.h'
      PARAMETER(IBADMX=5)
      PARAMETER(IHCRECL=4*IPM25*24)
      include 'commons/suridex.h'
      include 'commons/pm2idex.h'
      include 'commons/tafidex.h'
      include 'commons/timvari.h'
      include 'commons/names.h'
C===============================================================================
      DIMENSION SCRAT(IX,JX),A(24,IPM25)
C Units of PM2.5 emissions (PM2EM) are tons per (4km) grid square per day
      CHARACTER*10 SCCBADSV(IBADMX)
      INTEGER STATUS,SYSTEM
      CHARACTER*4 HCFILNM,HRNAM
      CHARACTER*12 OUDIRF
      CHARACTER*20 FIL
      LOGICAL EXISTS
      DATA ITIMS,ISAV/0,0/
      SAVE
      ITIMS=ITIMS+1
      IF(ITIMS.EQ.1)THEN
      IF(ITIMVAR.EQ.1)THEN
      INQUIRE(FILE='tmpdira',EXIST=EXISTS)
      IF(.NOT.EXISTS)THEN
      WRITE(*,*)'tmpdira directory  DOESNT EXIST, making it'
      STATUS=SYSTEM('mkdir tmpdira')
      ELSE  ! erase anything in tmpdira
      WRITE(*,*)'tmpdira directory  EXISTS, erasing PM file'
      STATUS=SYSTEM('rm -rf tmpdira/PMtv')
      ENDIF
      DO ISP=1,IPM25
      DO I=1,24
      A(I,ISP)=0.
      ENDDO
      ENDDO
      WRITE(HCFILNM,'(A4)')'PMtv'
      OUDIRF='tmpdira/'//HCFILNM
      IUN=11
      OPEN(UNIT=IUN,FILE=OUDIRF,ACCESS='DIRECT',RECL=IHCRECL,
     -FORM='UNFORMATTED')
      N0=0
      DO 2 J=1,JX
      DO 2 I=1,IX
      N0=N0+1
      WRITE(IUN,REC=N0)A
 2    CONTINUE
      WRITE(*,16)OUDIRF,IUN,N0
 16   FORMAT('WRITTEN TO ',A12,' UNIT=',I2,' N=',I7)
      DO IHR=1,24
      WRITE(HRNAM,'(A2,I2.2)')'HR',IHR
      INQUIRE(FILE=HRNAM,EXIST=EXISTS)
      IF(.NOT.EXISTS)THEN
      WRITE(*,*)'Hour directory ',HRNAM,'  DOESNT EXIST, making it'
      STATUS=SYSTEM('mkdir '//HRNAM)
      ENDIF
      ENDDO
      INQUIRE(FILE='dayav',EXIST=EXISTS)
      IF(.NOT.EXISTS)THEN
      WRITE(*,*)'dayav directory DOESNT EXIST, making it'
      STATUS=SYSTEM('mkdir dayav')
      ENDIF
      ENDIF   !IF ITIMVAR=1
      ELSEIF(ISC.LT.0)THEN
C Write out hourly emissions if ITIMVAR=1
      IF(ITIMVAR.EQ.1)THEN
      WRITE(7,*)' WRITING ',NAMPM2(ISP),' hourly variation files'
      CALL FLUSH(7)
      IUN=11
      DO ISP=1,IPM25
      WRITE(HCFILNM,'(A2,I2.2)')'PM',ISP
C Modify for putting hourly 2-D emission files in subdirectories HR01,HR02,HR03......
      DO 15 IHR=1,24
      WRITE(HRNAM,'(A2,I2.2)')'HR',IHR
      FIL=HRNAM//'/'//HCFILNM
      OPEN(8,FILE=FIL,FORM='FORMATTED')
      ETOT=0.
      EMAX=-1.E30
      IN=0
      DO J=1,JX
      DO I=1,IX
      IN=IN+1
      READ(IUN,REC=IN)A
      SCRAT(I,J)=A(IHR,ISP)
      ETOT=ETOT+SCRAT(I,J)
      IF(SCRAT(I,J).GT.EMAX)THEN
      EMAX=SCRAT(I,J)
      IMAX=I
      JMAX=J
      ENDIF
      ENDDO
      ENDDO
      WRITE(8,'(1P12E9.2)')SCRAT
      CLOSE(8)
      LLET3=LNBLNK(FIL)
      STATUS=SYSTEM('nohup gzip -f '//FIL(1:LLET3)//'&')
      WRITE(7,'(A,I2,1X,A,A,1P,2E11.4,2I5)')'Hr ',IHR-1,NAMPM2(ISP),
     -' Totl,Max,I,J= ',ETOT,EMAX,IMAX,JMAX
 15   CONTINUE
      WRITE(*,'(A,A)')'24hr write= ',NAMPM2(ISP)
      WRITE(7,'(A,A)')'24hr write= ',NAMPM2(ISP)
      FIL='dayav/'//HCFILNM
      LLET3=LNBLNK(FIL)
      OPEN(8,FILE=FIL,FORM='FORMATTED')
C Refill SCRAT with daily average from hourly temp files, units of short ton per day per 4km grid
      SCRAT=0.
      DO IHR=1,24
      IN=0
      DO J=1,JX
      DO I=1,IX
      IN=IN+1
      READ(IUN,REC=IN)A
      SCRAT(I,J)=SCRAT(I,J)+A(IHR,ISP)
      ENDDO
      ENDDO
      ENDDO
      ETOT=0.
      EMAX=-1.E30
      DO I=1,IX
      DO J=1,JX
      ETOT=ETOT+SCRAT(I,J)
      IF(SCRAT(I,J).GT.EMAX)THEN
      EMAX=SCRAT(I,J)
      IMAX=I
      JMAX=J
      ENDIF
      ENDDO
      ENDDO
      WRITE(8,'(1P12E9.2)')SCRAT
      CLOSE(8)
      STATUS=SYSTEM('nohup gzip -f '//FIL(1:LLET3)//'&')
      WRITE(7,'(2A,1P2E10.3,2I5)')NAMPM2(ISP),
     -' Diurn Totl(ton/dy),Max,I,J=',ETOT,EMAX,IMAX,JMAX
      WRITE(*,'(2A,1P2E10.3,2I5)')NAMPM2(ISP),
     -' Diurn Totl(ton/dy),Max,I,J=',ETOT,EMAX,IMAX,JMAX
      ENDDO   !ISP=1,IPM25
      ENDIF   !IF ITIMVAR=1
      CLOSE(IUN)
      RETURN
      ENDIF
      IF(ISCCPM2(ISC).EQ.-999)THEN
      IF(ISAV.EQ.0)THEN
      ISAV=1
      SCCBADSV(ISAV)=SCCNUM(ISC)
      WRITE(7,'(A,A10)')'No PM25 assgn to SCC=',SCCNUM(ISC)
      GOTO 3
      ELSE
      DO I=1,ISAV
      IF(SCCNUM(ISC).EQ.SCCBADSV(I))GOTO 3
      ENDDO
      ISAV=ISAV+1
      IF(ISAV.GT.IBADMX)THEN
      WRITE(*,*)'Bad SCCs-no PM2.5 profile > ',IBADMX,' stopping'
      WRITE(7,*)'Bad SCCs-no PM2.5 profile > ',IBADMX,' stopping'
      STOP777
      ENDIF
      SCCBADSV(ISAV)=SCCNUM(ISC)
      ENDIF
      WRITE(7,'(A,A10)')'No PM2.5 assign to SCC= ',SCCNUM(ISC)
      ELSE
C Everything OK for updating PM2EM matrices, PM2EM,ELEMPM2 in ton per day per (4km) grid
      IPRF=ISCCPM2(ISC)
      IUN=11
      JB=JJ-1
      IN=JB*IX+II
      READ(IUN,REC=IN)A
      DO I=1,IPM25
      IF(PRFLPM2(I,IPRF).GT.0.)THEN
      ELEMPM2=PRFLPM2(I,IPRF)*ELEMADD
C     PM2EM(I,II,JJ)=PM2EM(I,II,JJ)+ELEMPM2
C     PM2EM(ISC,I)=PM2EM(ISC,I)+ELEMPM2
C Save hourly emissions if ITIMVAR=1
      IF(ITIMVAR.EQ.1)THEN
      IWKDX=IDWK(ISC,IFIPTV)
      IDYDX=IDDY(ISC,IFIPTV)
      IF(IWKDX.LE.0.OR.IDYDX.LE.0)THEN
      IF(ISAV.EQ.0)THEN
      ISAV=1
      SCCBADSV(ISAV)=SCCNUM(ISC)
      WRITE(7,'(A,A10)')'No taff assign to SCC= ',SCCNUM(ISC)
      GOTO 3
      ELSE
      DO K=1,ISAV
      IF(SCCNUM(ISC).EQ.SCCBADSV(K))GOTO 3
      ENDDO
      ISAV=ISAV+1
      IF(ISAV.GT.IBADMX)THEN
      WRITE(*,*)'Bad SCCs-no July temp profile > ',IBADMX,' stopping'
      STOP777
      ENDIF
      SCCBADSV(ISAV)=SCCNUM(ISC)
      ENDIF
      WRITE(7,'(A,A10)')'No July_taff assign to SCC= ',SCCNUM(ISC)
C Only found 1 SCC=2801500000 in area files that has July TAFF=0, but want
C to keep OSD numbers even though TAFF assign to annual is zero, change ELSE
C to endif to continue
      ENDIF   !IF(IWKDX.LE.0.OR.IDYDX.LE.0)THEN
      FACDY=1.
      IF(IDYoWK.EQ.1)THEN   !Weekday (M-F) emission
      FACDY=(FSCWK(IWKDX,1)+FSCWK(IWKDX,2)+FSCWK(IWKDX,3)+FSCWK(IWKDX,4)
     -+FSCWK(IWKDX,5))*7./5.
      ELSEIF(IDYoWK.EQ.2)THEN   !Saturday emission
      FACDY=FSCWK(IWKDX,6)*7.
      ELSEIF(IDYoWK.EQ.3)THEN   !Sunday emission
      FACDY=FSCWK(IWKDX,7)*7.
      ENDIF
      IF(IPRN.EQ.1)THEN
      WRITE(7,'(A,I8,I5,1P,6E11.4)')'A read-I,IN,A=',
     -I,IN,(A(I,IPRF),I=1,IPM25)
      CALL FLUSH(7)
      ENDIF
      DO 20 IHR=1,24
C IHRPLAC= 1 for UTC00-UTC01, =2 for UTC01-UTC02,...etc.
      IHRPLAC=1+MOD(IHR-1+IHRDIF,24)
 20   A(IHRPLAC,I)=A(IHRPLAC,I)+ELEMPM2*FACDY*FSCDY(IDYDX,IHR)
      ENDIF   !IF ITIMVAR=1
      ENDIF   !IF (PRFLPM2(I,IPRF).GT.0.)THEN
      ENDDO   !I=1,IPM25
      WRITE(IUN,REC=IN)A
C Hourly PM2.5 emission files - units in tons/hr per 4km grid square
      ENDIF
 3    CONTINUE
      RETURN
      END
C *******************************************************************
      SUBROUTINE TIMVAR(ISC,IFIP,II,JJ,ELEMADD,IHRDIF)
      include 'commons/parame.h'
      PARAMETER(IBADMX=5)
      include 'commons/suridex.h'
      include 'commons/tafidex.h'
      include 'commons/timvari.h'
      include 'commons/names.h'
C===============================================================================
      DIMENSION SCRAT(IX,JX)
      CHARACTER*10 SCCBADSV(IBADMX)
      CHARACTER*4 HRNAM
      CHARACTER*20 FIL
      INTEGER STATUS,SYSTEM
      LOGICAL EXISTS
      DATA ITIMS,ISAV/0,0/
      SAVE
      ITIMS=ITIMS+1
      IF(ITIMS.EQ.1)THEN
      WRITE(TVDIRNM,'(A5)')'tvar/'
      INQUIRE(FILE='tvar',EXIST=EXISTS)
      IF(.NOT.EXISTS)THEN
      WRITE(*,*)'TIMEvariation directories DONT EXIST, making them'
      STATUS=SYSTEM('mkdir tvar')
      ENDIF
      ELSEIF(ISC.LT.0)THEN
      WRITE(7,*)' WRITING ',NAM,' hourly variation file'
      CALL FLUSH(7)
C     OPEN(8,FILE=TVDIRNM//NAM,FORM='UNFORMATTED')
C     WRITE(8)EM
C     CLOSE(8)
C Modify for putting hourly 2-D emission files in subdirectories HR01,HR02,HR03......
      DO 15 IHR=1,24
      WRITE(HRNAM,'(A2,I2.2)')'HR',IHR
      INQUIRE(FILE=HRNAM,EXIST=EXISTS)
      IF(.NOT.EXISTS)THEN
      WRITE(*,*)'Hour directory ',HRNAM,'  DOESNT EXIST, making it'
      STATUS=SYSTEM('mkdir '//HRNAM)
      ENDIF
      FIL=HRNAM//'/'//INARG(1:LLET)
      OPEN(8,FILE=FIL,FORM='FORMATTED')
      ETOT=0.
      EMAX=-1.E30
      DO J=1,JX
      DO I=1,IX
      SCRAT(I,J)=EM(IHR,I,J)
      ETOT=ETOT+SCRAT(I,J)
      IF(SCRAT(I,J).GT.EMAX)THEN
      EMAX=SCRAT(I,J)
      IMAX=I
      JMAX=J
      ENDIF
      ENDDO
      ENDDO
      WRITE(8,'(1P12E9.2)')SCRAT
      CLOSE(8)
      LLET3=LNBLNK(FIL)
      STATUS=SYSTEM('nohup gzip -f '//FIL(1:LLET3)//'&')
      WRITE(7,'(A,I2,1X,A,A,1P,2E11.4,2I5)')'Hr ',IHR-1,INARG(1:LLET),
     -' Totl,Max,I,J= ',ETOT,EMAX,IMAX,JMAX
 15   CONTINUE
      WRITE(*,'(A,A)')'24hr write= ',INARG(1:LLET)
      WRITE(7,'(A,A)')'24hr write= ',INARG(1:LLET)
      INQUIRE(FILE='dayav',EXIST=EXISTS)
      IF(.NOT.EXISTS)THEN
      WRITE(*,*)'dayav directory DOESNT EXIST, making it'
      STATUS=SYSTEM('mkdir dayav')
      ENDIF
      FIL='dayav/'//INARG(1:LLET)
      LLET3=LNBLNK(FIL)
      OPEN(8,FILE=FIL,FORM='FORMATTED')
C Refill SCRAT with daily average from hourly temp files, units of short ton per day per 4km grid
      SCRAT=0.
      DO IHR=1,24
      DO I=1,IX
      DO J=1,JX
      SCRAT(I,J)=SCRAT(I,J)+EM(IHR,I,J)
      ENDDO
      ENDDO
      ENDDO
      ETOT=0.
      EMAX=-1.E30
      DO I=1,IX
      DO J=1,JX
      ETOT=ETOT+SCRAT(I,J)
      IF(SCRAT(I,J).GT.EMAX)THEN
      EMAX=SCRAT(I,J)
      IMAX=I
      JMAX=J
      ENDIF
      ENDDO
      ENDDO
      WRITE(8,'(1P12E9.2)')SCRAT
      CLOSE(8)
      STATUS=SYSTEM('nohup gzip -f '//FIL(1:LLET3)//'&')
      WRITE(7,'(2A,1P2E10.3,2I5)')INARG(1:LLET),
     -' Diurn Totl(ton/dy),Max,I,J=',ETOT,EMAX,IMAX,JMAX
      WRITE(*,'(2A,1P2E10.3,2I5)')INARG(1:LLET),
     -' Diurn Totl(ton/dy),Max,I,J=',ETOT,EMAX,IMAX,JMAX
      RETURN
      ENDIF ! Endo of ISC < or = to 0 test
C     PARAMETER(IMNMX=1500,IWKMX=50,IDYMX=339)
C     COMMON /SC2TAF/IDMN(ISCCMX,3),IDWK(ISCCMX,3),IDDY(ISCCMX,3),
C    - FSCWK(IWKMX,7),FSCDY(IDYMX,24)
C     IF(FSCMN(ISC,7).LE.0.)THEN
      IWKDX=IDWK(ISC,IFIP)
      IDYDX=IDDY(ISC,IFIP)
      IF(IWKDX.LE.0.OR.IDYDX.LE.0)THEN
      IF(ISAV.EQ.0)THEN
      ISAV=1
      SCCBADSV(ISAV)=SCCNUM(ISC)
      WRITE(7,'(A,A10)')'No taff assign to SCC= ',SCCNUM(ISC)
      GOTO 3
      ELSE
      DO I=1,ISAV
      IF(SCCNUM(ISC).EQ.SCCBADSV(I))GOTO 3
      ENDDO
      ISAV=ISAV+1
      IF(ISAV.GT.IBADMX)THEN
      WRITE(*,*)'Bad SCCs-no July temp profile > ',IBADMX,' stopping'
      STOP777
      ENDIF
      SCCBADSV(ISAV)=SCCNUM(ISC)
      ENDIF
      WRITE(7,'(A,A10)')'No July_taff assign to SCC= ',SCCNUM(ISC)
C Only found 1 SCC=2801500000 in area files that has July TAFF=0, but want
C to keep OSD numbers even though TAFF assign to annual is zero, change ELSE
C to endif to continue
      ENDIF   !IF(IWKDX.LE.0.OR.IDYDX.LE.0)THEN
C     ELSE
C Emission ELEMADD is in ton/dy per 4 km grid square for SSD (summer season day)
      FACDY=1.
      IF(IDYoWK.EQ.1)THEN   !Weekday (M-F) emission
      FACDY=(FSCWK(IWKDX,1)+FSCWK(IWKDX,2)+FSCWK(IWKDX,3)+FSCWK(IWKDX,4)
     -+FSCWK(IWKDX,5))*7./5.
      ELSEIF(IDYoWK.EQ.2)THEN   !Saturday emission
      FACDY=FSCWK(IWKDX,6)*7.
      ELSEIF(IDYoWK.EQ.3)THEN   !Sunday emission
      FACDY=FSCWK(IWKDX,7)*7.
      ENDIF
      HRSUM=0.
      DO I=1,24
C IHRPLAC= 1 for UTC00-UTC01, =2 for UTC01-UTC02,...etc.
      IHRPLAC=1+MOD(I-1+IHRDIF,24)
      EM(IHRPLAC,II,JJ)=EM(IHRPLAC,II,JJ)+ELEMADD*FACDY*FSCDY(IDYDX,I)
      HRSUM=HRSUM+FSCDY(IDYDX,I)
C Hourly emission files - units in ton/hr per 4km grid square
      ENDDO
      IF(HRSUM.GT.1.1.OR.HRSUM.LT.0.9)THEN
      WRITE(7,*)'IDYDX,IWKDX,FACDY,HRSUM=',IDYDX,IWKDX,FACDY,HRSUM
      WRITE(7,*)'II,JJ,ISC,ITY,IDYoWK=',II,JJ,ISC,ITY,IDYoWK
      STOP777
      ENDIF
 3    CONTINUE
      RETURN
      END
C ******************************************************************* 
      SUBROUTINE TIMZON(ICOUN,IHRDIF)
C     SUBROUTINE TIMZON(ISTAT,ICOU,IHRDIF)
C  THIS SUBROUTINE TAKES FIPS CODE OF STATE AND COUNTY AND RETURNS
C  THE HOURLY DIFFERENCE IN TIME BETWEEN UNIVERSAL TIME AND LOCAL
C  TIME IN THAT PARTICULAR STATE AND COUNTY.  STU MCKEEN 2/4/04
C  SPECIFY IF DAYLIGHT SAVINGS TIME (IDAYLT=1) IN THIS SUBROUTINE.
C 11/20/13 Add in time zones for STATE CODES = 75 (US water off
C canadian provinces), 78 (US Virgin Islands), 85 (coastal waters)
C 88 (Tribal Lands) 98 (Non-US SECA) and 99 (Gulf of Mexico)
C     PARAMETER(ITOT=99,IDAYLT=1)
      PARAMETER(ITOT=99,IDAYLT=0) ! January, no daylight time
      PARAMETER(IID=9,IIN=10,IKS=4,IKY=42,IMI=4,INB=18,IND=13,
     -IOR=1,ISD=18,ITN=28,ITX=2)
      DIMENSION ISTDAT(ITOT),JID(IID),JIN(IIN),JKS(IKS),JKY(IKY),
     -JMI(IMI),JNB(INB),JND(IND),JOR(IOR),JSD(ISD),JTN(ITN),JTX(ITX)
C INDLKP are counties in Indiana, in Eastern Time Zone, that observe daylight savings time
      DIMENSION INDLKP(5)
C     DATA ISTDAT/6,9,11,7,6,8,0,7,5,5,5,5,5,-10,9,7,6,5,6,6,5,6,5,
C    -5,5,5,6,6,6,7,6,8,5,5,7,5,5,6,5,6,8,5,4,5,5,6,6,6,7,5,5,4,8,5,6,7/
      DATA ISTDAT/6,9,11,7,6,8,0,7,5,5,5,5,5,-10,9,7,6,5,6,6,5,6,5,
     -5,5,5,6,6,6,7,6,8,5,5,7,5,5,6,5,6,8,5,4,5,5,6,6,6,7,5,5,4,8,5,6,7,
     -0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,5,0,0,0,0,0,0,5,0,0,7,0,
     -0,0,0,0,0,0,0,0,8,5/
      DATA JID/9,17,21,35,49,55,57,69,79/
      DATA JIN/51,73,89,91,111,127,129,147,163,173/
      DATA INDLKP/19,29,43,61,115/
      DATA JKS/71,75,181,199/
      DATA JKY/7,39,185,75,35,83,157,145,139,55,225,101,233,33,107,143,
     -221,219,47,177,149,59,91,27,183,85,31,99,61,227,213,3,141,87,169,
     -1,207,57,231,53,171,9/
      DATA JMI/43,53,71,109/
      DATA JNB/91,75,5,101,135,29,57,49,33,105,7,157,165,45,161,69,123,
     -13/
      DATA JND/25,57,85,59,37,65,89,41,1,11,87,33,7/
      DATA JOR/45/
      DATA JSD/63,105,31,41,137,117,55,95,119,7,113,47,33,103,71,93,19,
     -81/
      DATA JTN/151,13,25,57,93,1,129,89,155,9,123,107,139,65,11,143,
     -145,105,121,67,73,59,29,179,19,91,163,171/
      DATA JTX/141,229/
      SAVE
      ISTAT=ICOUN/1000
      ICOU=ICOUN-1000*ISTAT
      IF(ISTAT.GT.ITOT.OR.ISTAT.LT.1)THEN
      WRITE(6,*)' BAD STATE IN TIMZON, ISTAT= ',ISTAT,' ICOU= ',ICOU
C     RETURN
      STOP
      ENDIF
C Daylight savings time ignored in AZ, HI, and 77 counties in Indiana
C The Indiana counties that DO observe daylight savings time are the
C 10 counties in the Central time zone in JIN below, and 5 counties
C in two eastern portions of IN, Dearborn, Ohio counties (new Cincinnati, OH)
C and Clark, Floyd and Harrison counties (near Louiville, KT).
C IDYIGN=0 if normal county - observes daylight savings time
C IDYIGN=1 if ignorant county - ignores daylight savings time
      IDYIGN=0
      IHRDIF=ISTDAT(ISTAT)
      IF(ISTAT.EQ.16)THEN
C   IDAHO - PACIFIC TIME ZONE COUNTIES
      DO 1 I=1,IID
 1    IF(ICOU.EQ.JID(I))IHRDIF=8
      ELSEIF(ISTAT.EQ.18)THEN
      IDYIGN=1
      DO I=1,5
      IF(ICOU.EQ.INDLKP(I))IDYIGN=0
      ENDDO
C   INDIANA - CENTRAL TIME ZONE COUNTIES
      DO 2 I=1,IIN
      IF(ICOU.EQ.JIN(I))THEN
      IHRDIF=6
      IDYIGN=0
      ENDIF
 2    CONTINUE
      ELSEIF(ISTAT.EQ.20)THEN
C   KANSAS - MOUNTAIN TIME ZONE COUNTIES
      DO 3 I=1,IKS
 3    IF(ICOU.EQ.JKS(I))IHRDIF=7
      ELSEIF(ISTAT.EQ.21)THEN
C   KENTUCKY - CENTRAL TIME ZONE COUNTIES
      DO 4 I=1,IKY
 4    IF(ICOU.EQ.JKY(I))IHRDIF=6
      ELSEIF(ISTAT.EQ.26)THEN
C   MICHIGAN - CENTRAL TIME ZONE COUNTIES
      DO 5 I=1,IMI
 5    IF(ICOU.EQ.JMI(I))IHRDIF=6
      ELSEIF(ISTAT.EQ.31)THEN
C   NEBRASKA - MOUNTAIN TIME ZONE COUNTIES
      DO 6 I=1,INB
 6    IF(ICOU.EQ.JNB(I))IHRDIF=7
      ELSEIF(ISTAT.EQ.38)THEN
C   NORTH DAKOTA - MOUNTAIN TIME ZONE COUNTIES
      DO 7 I=1,IND
 7    IF(ICOU.EQ.JND(I))IHRDIF=7
      ELSEIF(ISTAT.EQ.41)THEN
C   OREGON - MOUNTAIN TIME ZONE COUNTIES
      IF(ICOU.EQ.JOR(1))IHRDIF=7
      ELSEIF(ISTAT.EQ.46)THEN
C   SOUTH DAKOTA - MOUNTAIN TIME ZONE COUNTIES
      DO 8 I=1,ISD
 8    IF(ICOU.EQ.JSD(I))IHRDIF=7
      ELSEIF(ISTAT.EQ.47)THEN
C   TENNESSEE - EASTERN TIME ZONE COUNTIES
      DO 9 I=1,ITN
 9    IF(ICOU.EQ.JTN(I))IHRDIF=5
      ELSEIF(ISTAT.EQ.48)THEN
C   TEXAS - MOUNTAIN TIME ZONE COUNTIES
      DO 10 I=1,ITX
 10   IF(ICOU.EQ.JTX(I))IHRDIF=7
C US coastal waters
      ELSEIF(ISTAT.EQ.85)THEN
      IF(ICOU.EQ.1.OR.ICOU.EQ.2)IHRDIF=8
      IF(ICOU.EQ.3)IHRDIF=6
      IF(ICOU.EQ.5)IHRDIF=9  ! Alaska time zone
      IF(ICOU.EQ.5)IHRDIF=-10 ! Hawaii time zone
C Tribal Lands
      ELSEIF(ISTAT.EQ.88)THEN
      IF(ICOU.EQ.1.OR.ICOU.EQ.18.OR.ICOU.EQ.108)IHRDIF=5
      IF(ICOU.GE.380.AND.ICOU.LE.482.OR.ICOU.GE.862)IHRDIF=6
      IF(ICOU.EQ.101.OR.ICOU.EQ.124.OR.ICOU.EQ.143.OR.ICOU.EQ.181.OR.
     -ICOU.EQ.549.OR.ICOU.EQ.568.OR.ICOU.EQ.577.OR.ICOU.EQ.672)IHRDIF=7
      ELSEIF(ISTAT.EQ.4.OR.ISTAT.EQ.15)THEN
      IDYIGN=1
      ENDIF
      IF(IDAYLT.EQ.1.AND.IDYIGN.EQ.0)IHRDIF=IHRDIF-1
      RETURN
      END
      SUBROUTINE MAPSMP(FLD,IYY,JXX,IA,IB,INY,JA,JB,JNX,CONST,
     1                  ICHOS,NAME)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C                                                                     C
C                                                                     C
C     THIS SUBROUTINE PRINTS A SAMPLE OF A TWO-DIMENSIONAL DATA FIELD C
C     ON THE LINE PRINTER WITH 5 SIGNIFICANT DIGITS.                  C
C                                                                     C
C     *** NOTE *** THE VALUES OF FLD(I,J) SHOULD BE LIMITED WITHIN    C
C                  1.E30 --- 1.E-30. IF THE VALUE OUTSIDE THIS        C
C                  RANGE IS DESIRED, THE PROGRAM SHOULD BE CHANGED    C
C                  ACCORDINGLY (IN DO LOOP 20).                       C
C                                                                     C
C                                                                     C
C     FLD    : A TWO-DIMENSIONAL ARRAY TO HOLD THE DATA FIELD TO BE   C
C              SAMPLED AND PRINTED. FLD COULD BE A HORIZONTAL SLICE,  C
C              FLD(I,J), OR A VERTICAL SLICE FLD(K,I) OR FLD(K,J).    C
C                                                                     C
C     IYY    : THE FIRST DIMENSION OF FLD.                            C
C              FOR THE HORIZONTAL SLICE, IYY IS THE DIMENSION IN THE  C
C                                        Y DIRECTION.                 C
C              FOR THE VERTICAL SLICE, IYY IS THE DIMENSION IN THE    C
C                                      Z DIRECTION.                   C
C                                                                     C
C     JXX    : THE SECOND DIMENSION OF FLD.                           C
C              FOR THE HORIZONTAL SLICE, JXX IS THE DIMENSION IN THE  C
C                                        X DIRECTION.                 C
C              FOR THE VERTICAL SLICE, JXX IS THE DIMENSION IN EITHER C
C                                      THE X OR Y DIRECTION.          C
C                                                                     C
C     IA     : INITIAL SAMPLING POINT IN THE FIRST DIMENSION.         C
C                                                                     C
C     IB     : FINAL SAMPLING POINT IN THE FIRST DIMENSION.           C
C                                                                     C
C     INY    : SAMPLING INTERVAL IN THE FIRST DIMENSION.              C
C                                                                     C
C     JA     : INITIAL SAMPLING POINT IN THE SECOND DIMENSION.        C
C                                                                     C
C     JB     : FINAL SAMPLING POINT IN THE SECOND DIMENSION.          C
C                                                                     C
C     JNX    : SAMPLING INTERVAL IN THE SECOND DIMENSION.             C
C                                                                     C
C     CONST  : CONSTANT USED TO BE SUBTRACTED FROM FLD.               C
C                                                                     C
C     ICHOS > 0 : FOR HORIZONTAL ARRAY FLD(Y,X)                       C
C           < 0 : FOR VERTICAL CROSS SECTION FLD(Z,Y) OR FLD(Z,X)     C
C                                                                     C
C                                                                     C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
      DIMENSION FLD(JXX,IYY)
      CHARACTER*21 IFMT1,IFMT2
      CHARACTER*10 NAME
      DIMENSION JM(60)
      DATA KSIGT/5/ 
      N=7 
      K1=KSIGT+2
      K2=124/K1
      K3=KSIGT/2-1
      K4=KSIGT-K3-1
C
      DO 10 I=IA,IB,INY
      DO 10 J=JA,JB,JNX
   10 FLD(J,I)=FLD(J,I)-CONST 
C
      FLDMAX=FLD(JA,IA)
      FLDMIN=FLD(JA,IA)
      FLDU=10.**KSIGT
      FLDL=10.**(KSIGT-1)
      DO 20 J=JA,JB,JNX
      DO 20 I=IA,IB,INY
      IF(ABS(FLD(J,I)) .GT. 1.E30 .OR. ABS(FLD(J,I)) .LT. 1.E-30)
     1  GO TO 20
      IF (ABS(FLD(J,I)) .GT. FLDMAX) FLDMAX=ABS(FLD(J,I))
      IF (ABS(FLD(J,I)) .LT. FLDMIN) FLDMIN=ABS(FLD(J,I))
   20 CONTINUE
      IF (FLDMAX .EQ. FLDMIN) GO TO 150 
      IEXP=0
      DO 50 N1=1,500
      IF(FLDMAX .GE. FLDU) GO TO 30
      IF(FLDMAX .LT. FLDL) GO TO 40
      IF(FLDMAX .LT. FLDU .AND. FLDMAX .GE. FLDL) GO TO 60
   30 FLDMAX=FLDMAX/10.
      IEXP=IEXP-1
      GO TO 50
   40 FLDMAX=FLDMAX*10.
      IEXP=IEXP+1
   50 CONTINUE
   60 CONTINUE
      DO 70 I=IA,IB,INY
      DO 70 J=JA,JB,JNX
   70 FLD(J,I)=FLD(J,I)*10.**IEXP
      JX=JB-JA+1
      IY=IB-IA+1
      JN=K2*JNX
      JN1=JN-1
      WRITE(N,80) NAME,IEXP
   80 FORMAT(////' DIURN AVERAGE EMIS ',A10,'  ,SCALED BY  1.E',I3)
      DO 130 J1=JA,JB,JN
      JL=MIN0(J1+JN1,JB)
      JT=JL-J1+1
      JTN=(JT-1)/JNX+1
      J2N=0
      DO 90 J2=1,JT,JNX
      J2N=J2N+1
   90 JM(J2N)=J1+J2-1
      WRITE(IFMT1,100) JTN,K4,K3
  100 FORMAT(5H(/5X,,I2,1H(,I2,5HX,I3,,I2,4HX)/))
      WRITE(N,IFMT1) (JM(JJ),JJ=1,J2N)
      WRITE(IFMT2,110) JTN,K1
  110 FORMAT(4H(I3,,I2,1HF,I2,9H.0,1X,I3))
      IT=(IY-1)/INY 
      IR=IY-IT*INY
      DO 120 I2=IA,IB,INY
      I1=IB+IA-I2-IR+1
      IF (ICHOS .LT. 0) I1=I2 
      WRITE(N,IFMT2) I1,(FLD(J3,I1),J3=J1,JL,JNX),I1
  120 CONTINUE
  130 WRITE(N,IFMT1) (JM(JJ),JJ=1,J2N)
      DO 140 I=IA,IB,INY
      DO 140 J=JA,JB,JNX
  140 FLD(J,I)=FLD(J,I)/(10.**IEXP)+CONST
      GO TO 180
C
  150 CONTINUE
      DO 160 I=IA,IB,INY
      DO 160 J=JA,JB,JNX
  160 FLD(J,I)=FLD(J,I)+CONST 
      WRITE(N,170) NAME,FLDMAX
  170 FORMAT(/'   ALL OF THE VALUES OF ',A10,' ARE EQUAL TO ',E15.5)
  180 CONTINUE
      RETURN
      END 
C ******************************************************************* 
      SUBROUTINE LAMBC (XLAT,XLON,XI,YJ)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C                                                                     C
C                                                                     C
C     THIS SUBROUTINE COMPUTES THE MODEL INDEXES OF A POINT FROM      C
C     LATITUDE AND LONGITUDE.                                         C
C                                                                     C
C     INPUT :                                                         C
C                                                                     C
C        XLAT : LATITUDE OF THE POINT.                                C
C                                                                     C
C        XLON : LONGITUDE OF THE POINT.                               C
C                                                                     C
C     OUTPUT :                                                        C
C                                                                     C
C        XI : X COORDINATE OF THE POINT IN MODEL INDEX.               C
C                                                                     C
C        YJ : Y COORDINATE OF THE POINT IN MODEL INDEX.               C
C                                                                     C
C     INFORMATION NEEDED:                                             C
C                                                                     C
C        XLATC : LATITUDE OF THE CENTER POINT OF THE MODEL DOMAIN.    C
C                                                                     C
C        XLONC : LONGITUDE OF THE CENTER POINT OF THE MODEL DOMAIN.   C
C                                                                     C
C        DX    : GRID SIZE IN METERS.                                 C
C                                                                     C
C        IL    : X DIMENSION FOR THE MODEL DOT-POINT DOMAIN.          C
C                                                                     C
C        JL    : Y DIMENSION FOR THE MODEL DOT-POINT DOMAIN.          C
C                                                                     C
C        PLM1  : LATITUDE OF THE LOW-LEFT CORNER OF THE MAP.          C
C                                                                     C
C        PLM2  : LONGITUDE OF THE LOW-LEFT CORNER OF THE MAP.         C
C                                                                     C
C        PLM3  : LATITUDE OF THE UPPER-RIGHT CORNER OF THE MAP.       C
C                                                                     C
C        PLM4  : LONGITUDE OF THE UPPER-RIGHT CORNER OF THE MAP.      C
C                                                                     C
C        IPROJ : MAP PROJECTION,                                      C
C                FOR LAMBERT CONFORMAL PROJECTION ONLY                C
C                                                                     C
C     NOTE ***                                                        C
C                                                                     C
C     A WEST LONGITUDE IS GIVEN BY A NEGATIVE NUMBER; POSITIVE        C
C     ANGLES DENOTE EAST LONGITUDE.                                   C
C                                                                     C
C     A NORTH LATITUDE IS GIVEN BY A POSITIVE NUMBER, AND A NEGATIVE  C
C     NUMBER FOR A SOUTH LATITUDE.                                    C
C                                                                     C
C                                                                     C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
      include 'commons/mappar.h'
C
C-----------------------------------------------------------------------
      DATA POLE,CONV / 90.,57.29578 /
      DATA A,PH1D / 6370.997,30. /
      DATA ICLAMB / 0 /
      DATA XN / 1.000 /
C
      IF (ICLAMB.EQ.0) THEN
         DS = DXBIGDO/1000.
C  9/5/03 Modified for more general Lambert Conformal with 2 standard parallels,CLAT1,CLAT2
      IF (IPROJ.EQ.1)THEN
C     XN = 0.716 IF CLAT1=30 deg, CLAT2=60 deg
      FRTY5D=ATAN(1.)
      CONV=45./FRTY5D
      RLAT1=CLAT1/CONV
      RLAT2=CLAT2/CONV
C     XN=ALOG(SIN(RLAT1)/SIN(RLAT2))/ALOG(TAN(.5*RLAT1)/TAN(.5*RLAT2))
      XN=ALOG(COS(RLAT1)/COS(RLAT2))/ALOG(TAN(FRTY5D+.5*RLAT2)/
     -TAN(FRTY5D+.5*RLAT1))
      PH1D=CLAT1
      ENDIF
C     WRITE(7,*)'LAMBC,IPROJ, XN,PH1D= ',IPROJ,XN,PH1D
C        * COMPUTE LONGITUDE OF X AXIS (C1), ASSUMING ORIGIN AT NORTH POLE.
         C1 = -XLONC-POLE/XN
C        * COMPUTE DISTANCE BETWEEN NORTH POLE AND CENTER OF DOMAIN.
         PH1R = PH1D/CONV
         CELL = A*SIN(PH1R)/XN
         PHCR = (POLE-XLATC)/CONV
         CELL2 = CELL/(TAN(PH1R/2.)**XN)
         C2 =  CELL2 * (TAN(PHCR/2.)**XN)
      ENDIF
C
C     * COMPUTE DISTANCE BETWEEN POINT AND NORTH POLE.
      XXL = XN*(XLON+C1)/CONV 
      PHI2 = (POLE-XLAT)/CONV 
      RR = CELL2 *TAN(PHI2/2.)**XN
      XX = RR*COS(XXL)
      YY = RR*SIN(XXL)+C2
      XI = FLOAT(IL+1)/2.+XX/DS
      YJ = FLOAT(JL+1)/2.+YY/DS
      IF(INEST1.EQ.1)THEN
      XI=1.+(XI-XNESSTR)*DXBIGDO/DX
      YJ=1.+(YJ-YNESSTR)*DXBIGDO/DX
      ENDIF
      ICLAMB = 1
C
C
      RETURN
      END 
      SUBROUTINE MAPCF (XI,YJ,XLAT,XLON)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C                                                                     C
C                                                                     C
C     THIS SUBROUTINE COMPUTES THE LATITUDE AND LONGITUDE FROM MODEL  C
C     INDEXES OF A POINT.                                             C
C                                                                     C
C     INPUT :                                                         C
C                                                                     C
C        XI : X COORDINATE OF THE POINT IN MODEL INDEX.               C
C                                                                     C
C        YJ : Y COORDINATE OF THE POINT IN MODEL INDEX.               C
C                                                                     C
C     OUTPUT :                                                        C
C                                                                     C
C        XLAT : LATITUDE OF THE POINT.                                C
C                                                                     C
C        XLON : LONGITUDE OF THE POINT.                               C
C                                                                     C
C     INFORMATION NEEDED:                                             C
C                                                                     C
C        XLATC : LATITUDE OF THE CENTER POINT OF THE MODEL DOMAIN.    C
C                                                                     C
C        XLONC : LONGITUDE OF THE CENTER POINT OF THE MODEL DOMAIN.   C
C                                                                     C
C        DX    : GRID SIZE IN METERS.                                 C
C                                                                     C
C        IL    : X DIMENSION FOR THE MODEL DOT-POINT DOMAIN.          C
C                                                                     C
C        JL    : Y DIMENSION FOR THE MODEL DOT-POINT DOMAIN.          C
C                                                                     C
C        PLM1  : LATITUDE OF THE LOW-LEFT CORNER OF THE MAP.          C
C                                                                     C
C        PLM2  : LONGITUDE OF THE LOW-LEFT CORNER OF THE MAP.         C
C                                                                     C
C        PLM3  : LATITUDE OF THE UPPER-RIGHT CORNER OF THE MAP.       C
C                                                                     C
C        PLM4  : LONGITUDE OF THE UPPER-RIGHT CORNER OF THE MAP.      C
C                                                                     C
C        IPROJ : MAP PROJECTION,                                      C
C                = 1 : LAMBERT CONFORMAL                              C
C                = 2 : POLAR STEREOGRAPHIC                            C
C                = 3 : MERCATOR                                       C
C                                                                     C
C     NOTE ***                                                        C
C                                                                     C
C     A WEST LONGITUDE IS GIVEN BY A NEGATIVE NUMBER; POSITIVE        C
C     ANGLES DENOTE EAST LONGITUDE.                                   C
C                                                                     C
C     A NORTH LATITUDE IS GIVEN BY A POSITIVE NUMBER, AND A NEGATIVE  C
C     NUMBER FOR A SOUTH LATITUDE.                                    C
C                                                                     C
C                                                                     C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
      include 'commons/mappar.h'
C
C-----------------------------------------------------------------------
C
      DATA POLE,CONV / 90.,57.29578 /
      DATA A,PSI1 / 6370.997,30. /
      XN = -1.E36
C  9/5/03 Modified for more general Lambert Conformal with 2 standard parallels,CLAT1,CLAT2
      IF (IPROJ.EQ.1)THEN
C     XN = 0.716 IF CLAT1=30 deg, CLAT2=60 deg
      FRTY5D=ATAN(1.)
      CONV=45./FRTY5D
      RLAT1=CLAT1/CONV
      RLAT2=CLAT2/CONV
C     XN=ALOG(SIN(RLAT1)/SIN(RLAT2))/ALOG(TAN(.5*RLAT1)/TAN(.5*RLAT2))
C23456789 123456789 123456789 123456789 123456789 123456789 123456789 12
      XN=ALOG(COS(RLAT1)/COS(RLAT2))/ALOG(TAN(FRTY5D+.5*RLAT2)/
     -TAN(FRTY5D+.5*RLAT1))
      PSI1=CLAT1
C     WRITE(7,*)'IPROJ=1, XN,PSI1= ',XN,PSI1
      ENDIF
      IF (IPROJ.EQ.2) XN = 1.0
C
C     WRITE (6,1000) XLATC,XLONC
      KOUNT = 0
C
C-----DS IS GRID SPACING IN METERS
C-----PSI1 IS COLATITUDE OF LAT WHERE CONE OR PLANE INTERSECTS EARTH
C
      IF (IPROJ.EQ.2) PSI1 = 50.0
      IF (IPROJ.NE.3) PSI1 = PSI1/CONV
      IF (XLATC.LT.0.) THEN
         PSI1 = -30.
         POLE = -90.
         PSI1 = PSI1/CONV
      ENDIF
C
C-----A IS RADIUS OF EARTH IN KM
C     SUBTRACT XROT  DEGREES TO ROTATE LAMBERT CONFORMAL PROJECTION
C     CALCULATE R
C
      IF (IPROJ.NE.3) THEN
         PSX = (POLE-XLATC)/CONV
         IF (IPROJ.EQ.1) THEN
            CELL = A*SIN(PSI1)/XN
            CELL2 = (TAN(PSX/2.))/(TAN(PSI1/2.))
         ENDIF
         IF (IPROJ.EQ.2) THEN
            CELL = A*SIN(PSX)/XN
            CELL2 = (1.+COS(PSI1))/(1.+COS(PSX))
         ENDIF
         R = CELL*(CELL2)**XN
         XCNTR = 0.0
         YCNTR = -R
      ENDIF
C
C-----FOR MERCATOR PROJECTION, THE PROJECTION IS TRUE AT LATITUDE AT PHI1
C
      IF (IPROJ.EQ.3) THEN
         PHI1 = 0.0
         PHI1 = PHI1/CONV
         C2 = A*COS(PHI1)
         XCNTR = 0.0
         PHICTR = XLATC/CONV
         CELL = COS(PHICTR)/(1.0+SIN(PHICTR))
         YCNTR = -C2*ALOG(CELL)
      ENDIF
C     WRITE (6,1010) XCNTR,YCNTR
C
C-----CALCULATE X AND Y POSITIONS OF GRID
C
      CNTRJ = (JL+1)/2.
      CNTRI = (IL+1)/2.
      IF(INEST1.EQ.1)THEN
      XIBD=XNESSTR+(XI-1)*DX/DXBIGDO
      YJBD=YNESSTR+(YJ-1)*DX/DXBIGDO
      ELSE
      XIBD=XI
      YJBD=YJ
      ENDIF
      X = XCNTR+(XIBD-CNTRI)*DXBIGDO/1000.
      Y = YCNTR+(YJBD-CNTRJ)*DXBIGDO/1000.
C     WRITE (6,1020) X,Y
C
C-----NOW CALC LAT AND LONG OF THIS POINT
C
      IF (IPROJ.NE.3) THEN
         IF (XLATC.LT.0.0) THEN
            FLP = ATAN2(X,Y)
         ELSE
            FLP = ATAN2(X,-Y)
         ENDIF
C     write(6,*)' flp= ',FLP,' XN= ',XN,' conv= ',CONV,' XLONC= ',XLONC
         FLPP = (FLP/XN)*CONV+XLONC
C     write(6,*)' flpp= ',FLPP
         IF (FLPP.LT.-180.) FLPP = FLPP+360.
         IF (FLPP.GT.180.) FLPP = FLPP-360.
         XLON = FLPP
C     write(6,*)' xlon= ', xlon
C
C-----NOW SOLVE FOR LATITUDE
C
      ZZZZ=X*X+Y*Y
C     write(6,*)' r(square)= ',zzzz
         R = SQRT(X*X+Y*Y)
         IF (XLATC.LT.0.0) R = -R
         IF (IPROJ.EQ.1) THEN
C     write(6,*)' psi1= ',PSI1
            CELL = (R*XN)/(A*SIN(PSI1))
            RXN = 1.0/XN
            CEL1 = TAN(PSI1/2.)*(CELL)**RXN
C      write(6,*)' r=',R,' xn= ',XN,' cel1= ',CEL1
         ENDIF
         IF (IPROJ.EQ.2) THEN
            CELL = R/A
         CEL1 = CELL/(1.0+COS(PSI1))
         ENDIF
         CEL2 = ATAN(CEL1)
         PSX = 2.*CEL2*CONV
C     write(6,*)' pole= ',POLE,' psx= ',PSX
         XLAT = POLE-PSX
      ENDIF
C
C     CALCULATIONS FOR MERCATOR LAT, LONG AND MAP SCALES...
C
      IF (IPROJ.EQ.3) THEN
         XLON = -XLONC-((X-XCNTR)/C2)*CONV
         CELL = EXP(Y/C2)
         XLAT = 2.0*(CONV*ATAN(CELL))-90.0
      ENDIF
      RETURN
C
C
 1000 FORMAT (1X,'LATITUDE AND LONGITUDE OF CENTER OF GRID = ',F8.3,'N',
     *   F8.3,'W')
 1010 FORMAT (1X,'X COORD GRID CNTR = ',F8.1,' Y COORD = ',F8.1)
 1020 FORMAT (1X,'X INDEX = ',F8.1,' Y INDEX = ',F8.1)
C
      END
C--------0---------0---------0---------0---------0--------0---------0--
      SUBROUTINE FRAC(X1,X2,X3,X4,Y1,Y2,Y3,Y4)
      include 'commons/parame.h'
      COMMON/LONGI/ILONG
      COMMON/PRNT/ILON,ILAT,XLON,XLAT
      COMMON/FRC/I1,I2,I3,I4,J1,J2,J3,J4,FR1,FR2,FR3,FR4,TAR
      EX(XX1,XX2,YY1,YY2,Y)=(XX2-XX1)*(Y-YY1)/(YY2-YY1)+XX1 
      EY(XX1,XX2,YY1,YY2,X)=(YY2-YY1)*(X-XX1)/(XX2-XX1)+YY1 
      TRI(I,A1,B1,A2,B2,A3,B3)=.5*ABS(A1*B2+A2*B3+A3*B1-B1*A2-B2*A3
     --B3*A1)*I
      QUAD(A1,A2,A3,A4,B1,B2,B3,B4)=.5*ABS(A1*B2+A2*B3+A3*B4+A4*B1-
     -B1*A2-B2*A3-B3*A4-B4*A1)
      XCN=0.
      YCN=0.
      XLF=0.
      XRT=0.
      YBT=0.
      YTP=0.
      I1=X1
      II2=X2
      II3=X3
      II4=X4
      J1=Y1
      JJ2=Y2
      JJ3=Y3
      JJ4=Y4
      ICN=1
      I2=I1+1
      I3=I1
      I4=I2
      J2=J1
      J3=J1+1
      J4=J3
      FR1=0.
      FR2=0.
      FR3=0.
      FR4=0.
      TAR=QUAD(X1,X3,X4,X2,Y1,Y3,Y4,Y2) 
      NV=JJ2+JJ3+JJ4-3*J1
      NH=II2+II3+II4-3*I1
      NV5=1+NV
      V1=0.
      V2=0.
      GOTO(10,20,30,40)NV5
C  NV=-1
      YCN=FLOAT(J1) 
      XLF=EX(X1,X2,Y1,Y2,YCN) 
      XRT=EX(X2,X4,Y2,Y4,YCN) 
      V2=TRI(ICN,X2,Y2,XLF,YCN,XRT,YCN) 
      V1=TAR-V2
      J3=J1-1
      J4=J1-1
      GOTO 50
 10   CONTINUE
C  NV=0
      V1=TAR
      GOTO 50
 20   CONTINUE
C  NV=1
      YCN=FLOAT(J1+1)
      IF(ILONG.EQ.-1)THEN
      XLF=EX(X1,X3,Y1,Y3,YCN) 
      XRT=EX(X3,X4,Y3,Y4,YCN) 
      V2=TRI(ICN,X3,Y3,XLF,YCN,XRT,YCN) 
      ELSE
      XLF=EX(X3,X4,Y3,Y4,YCN) 
      XRT=EX(X2,X4,Y2,Y4,YCN) 
      V2=TRI(ICN,X4,Y4,XLF,YCN,XRT,YCN) 
      ENDIF
      V1=TAR-V2
      GOTO 50
 30   CONTINUE
C  NV=2
      YCN=FLOAT(J1+1)
      XLF=EX(X1,X3,Y1,Y3,YCN) 
      XRT=EX(X2,X4,Y2,Y4,YCN) 
C     WRITE(6,4)XLF,XRT,YCN
C4    FORMAT(1X,'XLF,XRT,YCN',3F10.6)
      V1=QUAD(X1,XLF,XRT,X2,Y1,YCN,YCN,Y2)
      V2=TAR-V1
      GOTO 50
 40   CONTINUE
C  NV=3
      YCN=FLOAT(J1+1)
      XLF=EX(X1,X3,Y1,Y3,YCN) 
      XRT=EX(X1,X2,Y1,Y2,YCN) 
      V1=TRI(ICN,X1,Y1,XLF,YCN,XRT,YCN) 
      V2=TAR-V1
 50   CONTINUE
      NH5=NH+1
      H1=0
      H2=0
      GOTO(11,21,31,41)NH5
C  NH=-1
      I2=I1-1
      I3=I1-1
      I4=I1
      XCN=FLOAT(I1) 
      YBT=EY(X1,X3,Y1,Y3,XCN) 
      YTP=EY(X3,X4,Y3,Y4,XCN) 
      H2=TRI(ICN,X3,Y3,XCN,YBT,XCN,YTP) 
      H1=TAR-H2
      GOTO 51
 11   CONTINUE
C  NH=0
      H1=TAR
      GOTO 51
 21   CONTINUE
C  NH=1
      XCN=FLOAT(I1+1)
      IF(ILONG.EQ.-1)THEN
      YBT=EY(X2,X4,Y2,Y4,XCN) 
      YTP=EY(X3,X4,Y3,Y4,XCN) 
      H2=TRI(ICN,X4,Y4,XCN,YBT,XCN,YTP) 
      ELSE
      YBT=EY(X1,X2,Y1,Y2,XCN) 
      YTP=EY(X2,X4,Y2,Y4,XCN) 
      H2=TRI(ICN,X2,Y2,XCN,YBT,XCN,YTP) 
      ENDIF
      H1=TAR-H2
      GOTO 51
 31   CONTINUE
C  NH=2
      XCN=FLOAT(I1+1)
      YBT=EY(X1,X2,Y1,Y2,XCN) 
      YTP=EY(X3,X4,Y3,Y4,XCN) 
      H1=QUAD(X1,X3,XCN,XCN,Y1,Y3,YTP,YBT)
      H2=TAR-H1
      GOTO 51
 41   CONTINUE
C  NH=3
      XCN=FLOAT(I1+1)
      YBT=EY(X1,X2,Y1,Y2,XCN) 
      YTP=EY(X1,X3,Y1,Y3,XCN) 
      H1=TRI(ICN,X1,Y1,XCN,YTP,XCN,YBT) 
      H2=TAR-H1
 51   CONTINUE
      NVNH=NV*NH
      IF(NVNH.EQ.0)THEN
C     WRITE(6,3)TAR,V1,V2,H1,H2
C3    FORMAT(1X,'TAR,V1,V2,H1,H2',1P5E9.2)
      ONTAR=1./TAR**2
      FR1=V1*H1*ONTAR
      FR2=V1*H2*ONTAR
      FR3=V2*H1*ONTAR
      GOTO 100
      ELSEIF(NVNH.EQ.4)THEN
      TAR1=QUAD(X1,XLF,XCN,XCN,Y1,YCN,YCN,YBT)
      FR1=TAR1/TAR
      FR2=(V1-TAR1)/TAR
      FR3=(H1-TAR1)/TAR
      FR4=1.-FR1-FR2-FR3
      GOTO 100
      ELSE
C  CORNER POINT NOT 4 QUADRANGLES
      IF(XLF.GE.XCN.OR.XRT.LE.XCN)ICN=0 
      IF(ILONG.EQ.1)THEN
      IF(NH.EQ.-1.AND.NV.NE.1)THEN
      TAX=TRI(ICN,XCN,YCN,XLF,YCN,XCN,YBT)
      FR2=TAX/TAR
      FR1=(V1-TAX)/TAR
      FR3=(H2-TAX)/TAR
      FR4=1.-FR1-FR2-FR3
      GOTO 100
      ELSEIF(NV.EQ.1.AND.NH.EQ.-1)THEN
      TAX=TRI(ICN,XCN,YCN,XLF,YCN,XCN,YTP)
      FR3=TAX/TAR
      FR2=(H2-TAX)/TAR
      FR4=(V2-TAX)/TAR
      FR1=1.-FR2-FR3-FR4
      GOTO 100
      ELSEIF(NV.EQ.1.AND.NH.NE.1)THEN
      TAX=TRI(ICN,XCN,YCN,XLF,YCN,XCN,YTP)
      FR3=TAX/TAR
      FR4=(V2-TAX)/TAR
      FR1=(H1-TAX)/TAR
      FR2=1.-FR1-FR3-FR4
      GOTO 100
      ELSEIF(NH.EQ.1.AND.NV.NE.3)THEN
      TAX=TRI(ICN,XCN,YCN,XRT,YCN,XCN,YTP)
      FR4=TAX/TAR
      FR3=(V2-TAX)/TAR
      FR2=(H2-TAX)/TAR
      FR1=1.-FR4-FR3-FR2
      GOTO 100
      ELSE
      TAX=TRI(ICN,XCN,YCN,XRT,YCN,XCN,YBT)
      FR2=TAX/TAR
      FR1=(V1-TAX)/TAR
      FR4=(H2-TAX)/TAR
      FR3=1.-FR1-FR2-FR4
      GOTO 100
      ENDIF
      ELSE
C  LONGITUDE LESS THAN -109.
      IF(NV.EQ.-1.AND.NH.NE.1)THEN
      TAX=TRI(ICN,XCN,YCN,XLF,YCN,XCN,YBT)
      FR3=TAX/TAR
      FR4=(V2-TAX)/TAR
      FR1=(H1-TAX)/TAR
      FR2=1.-FR1-FR3-FR4
      GOTO 100
      ELSEIF(NV.EQ.-1.AND.NH.EQ.1)THEN
      TAX=TRI(ICN,XCN,YCN,XRT,YCN,XCN,YBT)
      FR4=TAX/TAR
      FR3=(V2-TAX)/TAR
      FR2=(H2-TAX)/TAR
      FR1=1.-FR2-FR3-FR4
      GOTO 100
      ELSEIF(NH.EQ.1.AND.NV.NE.1)THEN
      TAX=TRI(ICN,XCN,YCN,XRT,YCN,XCN,YBT)
      FR2=TAX/TAR
      FR1=(V1-TAX)/TAR
      FR4=(H2-TAX)/TAR
      FR3=1.-FR1-FR2-FR4
      GOTO 100
      ELSEIF(NV.EQ.1.AND.NH.NE.3)THEN
      TAX=TRI(ICN,XCN,YCN,XRT,YCN,XCN,YTP)
      FR4=TAX/TAR
      FR3=(V2-TAX)/TAR
      FR2=(H2-TAX)/TAR
      FR1=1.-FR2-FR3-FR4
      GOTO 100
      ELSE
      TAX=TRI(ICN,XCN,YCN,XLF,YCN,XCN,YTP)
      FR3=TAX/TAR
      FR1=(H1-TAX)/TAR
      FR4=(V2-TAX)/TAR
      FR2=1.-FR1-FR3-FR4
      GOTO 100
      ENDIF
      ENDIF
      ENDIF
 100  CONTINUE
      FRT=FR1+FR2+FR3+FR4
      FRM=AMIN1(FR1,FR2,FR3,FR4)
      FRX=AMAX1(FR1,FR2,FR3,FR4)
CSAM WRITE OUT ALL FRAC VARIABLES HERE BY ELIMINATING IF-THEN-STOP-ENDIF
      IF(FRT.LT..999999.OR.FRT.GT.1.000001.OR.FRM.LT.0..OR.FRX.GT.1.) 
     -THEN
      WRITE(6,112)ILON,ILAT,XLON,XLAT,X1,Y1,X2,Y2,X3,Y3,X4,Y4,NV,NH
      WRITE(6,113)TAR,V1,V2,H1,H2,FR1,FR2,FR3,FR4 
      WRITE(6,114)XCN,YCN,XLF,XRT,YBT,YTP
 114  FORMAT(1X,'XCN,YCN,XLF,XRT,YBT,YTP',/,1X,6F10.6)
 113  FORMAT(1X,'TAR,V1,V2,H1,H2,FR1,FR2,FR3,FR4',/,1X,1P5E12.5,/,1X, 
     -0P4F11.7)
 112  FORMAT(1X,'COL,ROW,LONG,LAT,X1,Y1,X2,Y2,X3,Y3,X4,Y4,NV,NH',/,
     -1X,2I3,1X,2F9.4,/,1X,8F9.5,/,1X,2I3)
C     STOP
      ENDIF
      IF(I1.LT.1.OR.J1.LT.1.OR.I1.GT.IP.OR.J1.GT.JP)FR1=0.
      IF(I2.LT.1.OR.J2.LT.1.OR.I2.GT.IP.OR.J2.GT.JP)FR2=0.
      IF(I3.LT.1.OR.J3.LT.1.OR.I3.GT.IP.OR.J3.GT.JP)FR3=0.
      IF(I4.LT.1.OR.J4.LT.1.OR.I4.GT.IP.OR.J4.GT.JP)FR4=0.
C     WRITE(6,105)ILON,ILAT,I1,J1,FR1,I2,J2,FR2,I3,J3,FR3,I4,J4,FR4
 105  FORMAT(1X,2I4,4(1X,I2,1X,I2,1X,F9.6))
      RETURN
      END 
C **********************************************************************
EOFB
rm -f fort.2
cat >fort.2<< EOFA
2302003000 Industrial Processes|Commercial Cooking - Frying|Food and Kindred Products: SIC 20|
2501060052 Storage and Transport|Gasoline Service Stations|Petroleum and Petroleum Product Storage|B
2401200000 Solvent Utilization|Other Special Purpose Coatings|Surface Coating|
2601020000 Waste Disposal, Treatment, and Recovery|Commercial/Institutional|On-site Incineration|
2104004000 Stationary Source Fuel Combustion|Distillate Oil|Residential|
2104007000 Stationary Source Fuel Combustion|Liquified Petroleum Gas (LPG)|Residential|
2325000000 Industrial Processes|All Processes|Mining and Quarrying: SIC 14|
2311030000 Industrial Processes|Road Construction|Construction: SIC 15 - 17|B3A
2810060100 Miscellaneous Area Sources|Cremation|Other Combustion|
2294000000 Mobile Sources|All Paved Roads|Paved Roads|A
2104011000 Stationary Source Fuel Combustion|Kerosene|Residential|
2302003200 Industrial Processes|Commercial Cooking - Frying|Food and Kindred Products: SIC 20|
2302002200 Industrial Processes|Commercial Cooking - Charbroiling|Food and Kindred Products: SIC 20|
2501012014 Storage and Transport|Commercial Portable Gas Cans|Petroleum and Petroleum Product Storage|B
2501011012 Storage and Transport|Residential Portable Gas Cans|Petroleum and Petroleum Product Storage|B
2296000000 Mobile Sources|All Unpaved Roads|Unpaved Roads|A
2501012015 Storage and Transport|Commercial Portable Gas Cans|Petroleum and Petroleum Product Storage|B
2102006000 Stationary Source Fuel Combustion|Natural Gas|Industrial|
2311020000 Industrial Processes|Industrial/Commercial/Institutional|Construction: SIC 15 - 17|B2A
2401045000 Solvent Utilization|Metal Coils: SIC 3498|Surface Coating|
2861000010 Miscellaneous Area Sources|Recycling Related Emissions|Fluorescent Lamp Breakage|
2501011015 Storage and Transport|Residential Portable Gas Cans|Petroleum and Petroleum Product Storage|B
2460200000 Solvent Utilization|All Household Products|Miscellaneous Non-industrial: Consumer and Commercial|B2A
2501012012 Storage and Transport|Commercial Portable Gas Cans|Petroleum and Petroleum Product Storage|B
2461022000 Solvent Utilization|Emulsified Asphalt|Miscellaneous Non-industrial: Commercial|
2810030000 Miscellaneous Area Sources|Structure Fires|Other Combustion|
2103006000 Stationary Source Fuel Combustion|Natural Gas|Commercial/Institutional|
2851001000 Miscellaneous Area Sources|Bench Scale Reagents|Laboratories|
2401055000 Solvent Utilization|Machinery and Equipment: SIC 35|Surface Coating|
2401090000 Solvent Utilization|Miscellaneous Manufacturing|Surface Coating|
2505040120 Storage and Transport|Pipeline|Petroleum and Petroleum Product Transport|B4B
2102008000 Stationary Source Fuel Combustion|Wood|Industrial|
2850001000 Miscellaneous Area Sources|Dental Alloy Production|Health Services|
2501011011 Storage and Transport|Residential Portable Gas Cans|Petroleum and Petroleum Product Storage|B
2302002100 Industrial Processes|Commercial Cooking - Charbroiling|Food and Kindred Products: SIC 20|
2501060201 Storage and Transport|Gasoline Service Stations|Petroleum and Petroleum Product Storage|B
2401100000 Solvent Utilization|Industrial Maintenance Coatings|Surface Coating|
2461850000 Solvent Utilization|Pesticide Application: Agricultural|Miscellaneous Non-industrial: Commercial|B7A
2460400000 Solvent Utilization|All Automotive Aftermarket Products|Miscellaneous Non-industrial: Consumer and C
2810025000 Miscellaneous Area Sources|Residential Grilling (see 23-02-002-xxx for Commercial)|Other Combustion|
2104006000 Stationary Source Fuel Combustion|Natural Gas|Residential|
2103002000 Stationary Source Fuel Combustion|Bituminous/Subbituminous Coal|Commercial/Institutional|
2104008610 Stationary Source Fuel Combustion|Wood|Residential|B
2801700099 Miscellaneous Area Sources|Fertilizer Application|Agriculture Production - Crops|
2861000000 Miscellaneous Area Sources|Non-recycling Related Emissions|Fluorescent Lamp Breakage|
2501011013 Storage and Transport|Residential Portable Gas Cans|Petroleum and Petroleum Product Storage|B
2104008330 Stationary Source Fuel Combustion|Wood|Residential|B
2810060200 Miscellaneous Area Sources|Cremation|Other Combustion|
2505030120 Storage and Transport|Truck|Petroleum and Petroleum Product Transport|B3B
2103005000 Stationary Source Fuel Combustion|Residual Oil|Commercial/Institutional|
2415000000 Solvent Utilization|All Processes/All Industries|Degreasing|
2103011000 Stationary Source Fuel Combustion|Kerosene|Commercial/Institutional|A
2302050000 Industrial Processes|Bakery Products|Food and Kindred Products: SIC 20|
2501050120 Storage and Transport|Bulk Terminals: All Evaporative Losses|Petroleum and Petroleum Product Storage
2302003100 Industrial Processes|Commercial Cooking - Frying|Food and Kindred Products: SIC 20|
2401060000 Solvent Utilization|Large Appliances: SIC 363|Surface Coating|
2505020120 Storage and Transport|Marine Vessel|Petroleum and Petroleum Product Transport|B2B
2501060053 Storage and Transport|Gasoline Service Stations|Petroleum and Petroleum Product Storage|B
2401008000 Solvent Utilization|Traffic Markings|Surface Coating|
2801000003 Miscellaneous Area Sources|Agriculture - Crops|Agriculture Production - Crops|
2102002000 Stationary Source Fuel Combustion|Bituminous/Subbituminous Coal|Industrial|
2501055120 Storage and Transport|Bulk Plants: All Evaporative Losses|Petroleum and Petroleum Product Storage|
2501011014 Storage and Transport|Residential Portable Gas Cans|Petroleum and Petroleum Product Storage|B
2401080000 Solvent Utilization|Marine: SIC 373|Surface Coating|
2501080100 Storage and Transport|Airports : Aviation Gasoline|Petroleum and Petroleum Product Storage|
2401005000 Solvent Utilization|Auto Refinishing: SIC 7532|Surface Coating|
2805001000 Miscellaneous Area Sources|Beef cattle - finishing operations on feedlots (drylots)|Agriculture Prod
2501012011 Storage and Transport|Commercial Portable Gas Cans|Petroleum and Petroleum Product Storage|B
2104008100 Stationary Source Fuel Combustion|Wood|Residential|A
2501012013 Storage and Transport|Commercial Portable Gas Cans|Petroleum and Petroleum Product Storage|B
2460900000 Solvent Utilization|Miscellaneous Products (Not Otherwise Covered)|Miscellaneous Non-industrial: Con
2104008700 Stationary Source Fuel Combustion|Wood|Residential|
2102007000 Stationary Source Fuel Combustion|Liquified Petroleum Gas (LPG)|Industrial|
2425000000 Solvent Utilization|All Processes|Graphic Arts|
2103004001 Stationary Source Fuel Combustion|Distillate Oil|Commercial/Institutional|
2102005000 Stationary Source Fuel Combustion|Residual Oil|Industrial|
2401065000 Solvent Utilization|Electronic and Other Electrical: SIC 36 - 363|Surface Coating|
2102004002 Stationary Source Fuel Combustion|Distillate Oil|Industrial|
2104001000 Stationary Source Fuel Combustion|Anthracite Coal|Residential|
2104008220 Stationary Source Fuel Combustion|Wood|Residential|B
2401070000 Solvent Utilization|Motor Vehicles: SIC 371|Surface Coating|
2102011000 Stationary Source Fuel Combustion|Kerosene|Industrial|
2103004002 Stationary Source Fuel Combustion|Distillate Oil|Commercial/Institutional|
2401020000 Solvent Utilization|Wood Furniture: SIC 25|Surface Coating|
2103007000 Stationary Source Fuel Combustion|Liquified Petroleum Gas (LPG)|Commercial/Institutional|
2104009000 Stationary Source Fuel Combustion|Firelog|Residential|
2104002000 Stationary Source Fuel Combustion|Bituminous/Subbituminous Coal|Residential|
2401015000 Solvent Utilization|Factory Finished Wood: SIC 2426 thru 242|Surface Coating|
2501060051 Storage and Transport|Gasoline Service Stations|Petroleum and Petroleum Product Storage|B
2401075000 Solvent Utilization|Aircraft: SIC 372|Surface Coating|
2302070005 Industrial Processes|Fermentation/Beverages|Food and Kindred Products: SIC 20|
2460800000 Solvent Utilization|All FIFRA Related Products|Miscellaneous Non-industrial: Consumer and Commercial
2460600000 Solvent Utilization|All Adhesives and Sealants|Miscellaneous Non-industrial: Consumer and Commercial
2104008510 Stationary Source Fuel Combustion|Wood|Residential|B
2104008310 Stationary Source Fuel Combustion|Wood|Residential|B
2102004001 Stationary Source Fuel Combustion|Distillate Oil|Industrial|
2302002000 Industrial Processes|Commercial Cooking - Charbroiling|Food and Kindred Products: SIC 20|
2104008210 Stationary Source Fuel Combustion|Wood|Residential|B
2801000005 Miscellaneous Area Sources|Agriculture - Crops|Agriculture Production - Crops|
2401040000 Solvent Utilization|Metal Cans: SIC 341|Surface Coating|
2104008400 Stationary Source Fuel Combustion|Wood|Residential|A
2801500000 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2310010100 Industrial Processes|Crude Petroleum|Oil and Gas Exploration and Production|
2310000660 Industrial Processes|All Processes|Oil and Gas Exploration and Production|
2801500141 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2310023300 Industrial Processes|Coal Bed Methane Natural Gas|Oil and Gas Exploration and Production|
2310021501 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|B
2310121401 Industrial Processes|On-Shore Gas Exploration|Oil and Gas Exploration and Production|
2310021400 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|B
2501080050 Storage and Transport|Airports : Aviation Gasoline|Petroleum and Petroleum Product Storage|
2103008000 Stationary Source Fuel Combustion|Wood|Commercial/Institutional|
2310023251 Industrial Processes|Coal Bed Methane Natural Gas|Oil and Gas Exploration and Production|
2310021102 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2310021030 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2801500250 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2801500160 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2801500264 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2801500150 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2420000000 Solvent Utilization|All Processes|Dry Cleaning|A
2801500170 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2310021202 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2610000400 Waste Disposal, Treatment, and Recovery|All Categories|Open Burning|
2310023102 Industrial Processes|Coal Bed Methane Natural Gas|Oil and Gas Exploration and Production|
2310121700 Industrial Processes|On-Shore Gas Exploration|Oil and Gas Exploration and Production|
2310021505 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|B
2650000002 Waste Disposal, Treatment, and Recovery|Scrap and Waste Materials|Scrap and Waste Materials|
2310023513 Industrial Processes|Coal Bed Methane Natural Gas|Oil and Gas Exploration and Production|B
2310021302 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2801500262 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2310011503 Industrial Processes|On-Shore Oil Production|Oil and Gas Exploration and Production|B
2801500220 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2310023351 Industrial Processes|Coal Bed Methane Natural Gas|Oil and Gas Exploration and Production|
2801500152 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2620030000 Waste Disposal, Treatment, and Recovery|Municipal|Landfills|
2620030001 Waste Disposal, Treatment, and Recovery|Municipal|Landfills|
2310023400 Industrial Processes|Coal Bed Methane Natural Gas|Oil and Gas Exploration and Production|
2310111100 Industrial Processes|On-Shore Oil Exploration|Oil and Gas Exploration and Production|
2310023603 Industrial Processes|Coal Bed Methane Natural Gas|Oil and Gas Exploration and Production|
2310021351 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2310023511 Industrial Processes|Coal Bed Methane Natural Gas|Oil and Gas Exploration and Production|B
2310121100 Industrial Processes|On-Shore Gas Exploration|Oil and Gas Exploration and Production|
2310021300 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2310021010 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|B
2104008230 Stationary Source Fuel Combustion|Wood|Residential|B
2610030000 Waste Disposal, Treatment, and Recovery|Residential|Open Burning|
2311010000 Industrial Processes|Residential|Construction: SIC 15 - 17|B1A
2610000500 Waste Disposal, Treatment, and Recovery|All Categories|Open Burning|
2805040000 Miscellaneous Area Sources|Sheep and Lambs Waste Emissions|Agriculture Production - Livestock|
2640000000 Waste Disposal, Treatment, and Recovery|All TSDF Types|TSDFs|
2103001000 Stationary Source Fuel Combustion|Anthracite Coal|Commercial/Institutional|
2401025000 Solvent Utilization|Metal Furniture: SIC 25|Surface Coating|
2805010100 Miscellaneous Area Sources|Poultry production - turkeys|Agriculture Production - Livestock|B3B
2401001000 Solvent Utilization|Architectural Coatings|Surface Coating|
2401085000 Solvent Utilization|Railroad: SIC 374|Surface Coating|
2401030000 Solvent Utilization|Paper: SIC 26|Surface Coating|
2460500000 Solvent Utilization|All Coatings and Related Products|Miscellaneous Non-industrial: Consumer and Com
2460100000 Solvent Utilization|All Personal Care Products|Miscellaneous Non-industrial: Consumer and Commercial
2805008100 Miscellaneous Area Sources|Poultry production - layers with wet manure management systems|Agricultur
2862000000 Miscellaneous Area Sources|Total (Commercial, Residential, Public)|Swimming Pools|
2805007300 Miscellaneous Area Sources|Poultry production - layers with dry manure management systems|Agricultur
2805003100 Miscellaneous Area Sources|Beef cattle - finishing operations on pasture/range|Agriculture Productio
2805001200 Miscellaneous Area Sources|Beef cattle - finishing operations on feedlots (drylots)|Agriculture Prod
2805010300 Miscellaneous Area Sources|Poultry production - turkeys|Agriculture Production - Livestock|B3B
2805007100 Miscellaneous Area Sources|Poultry production - layers with dry manure management systems|Agricultur
2805008300 Miscellaneous Area Sources|Poultry production - layers with wet manure management systems|Agricultur
2805019300 Miscellaneous Area Sources|Dairy cattle - flush dairy|Agriculture Production - Livestock|B1B
2102001000 Stationary Source Fuel Combustion|Anthracite Coal|Industrial|
2805030008 Miscellaneous Area Sources|Poultry Waste Emissions|Agriculture Production - Livestock|B7A
2805023100 Miscellaneous Area Sources|Dairy cattle - drylot/pasture dairy|Agriculture Production - Livestock|B1
2805035000 Miscellaneous Area Sources|Horses and Ponies Waste Emissions|Agriculture Production - Livestock|
2285002008 Mobile Sources|Diesel|Railroad Equipment|
2310011501 Industrial Processes|On-Shore Oil Production|Oil and Gas Exploration and Production|B
2310021506 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|B
2805045000 Miscellaneous Area Sources|Goats Waste Emissions|Agriculture Production - Livestock|A
2805025000 Miscellaneous Area Sources|Swine production composite|Agriculture Production - Livestock|
2805018000 Miscellaneous Area Sources|Dairy cattle composite|Agriculture Production - Livestock|B1B
2805009100 Miscellaneous Area Sources|Poultry production - broilers|Agriculture Production - Livestock|B2B
2805002000 Miscellaneous Area Sources|Beef cattle production composite|Agriculture Production - Livestock|B2B
2310010200 Industrial Processes|Crude Petroleum|Oil and Gas Exploration and Production|
2310111700 Industrial Processes|On-Shore Oil Exploration|Oil and Gas Exploration and Production|
2440000000 Solvent Utilization|All Processes|Miscellaneous Industrial|
2610000100 Waste Disposal, Treatment, and Recovery|All Categories|Open Burning|A
2630020000 Waste Disposal, Treatment, and Recovery|Public Owned|Wastewater Treatment|B2A
2310021509 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|A
2310021603 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|B
2310011201 Industrial Processes|On-Shore Oil Production|Oil and Gas Exploration and Production|
2310011505 Industrial Processes|On-Shore Oil Production|Oil and Gas Exploration and Production|B
2461021000 Solvent Utilization|Cutback Asphalt|Miscellaneous Non-industrial: Commercial|
2285002006 Mobile Sources|Diesel|Railroad Equipment|
2801500410 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2801500320 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2461800002 Solvent Utilization|Pesticide Application: All Processes|Miscellaneous Non-industrial: Commercial|B6
2461800001 Solvent Utilization|Pesticide Application: All Processes|Miscellaneous Non-industrial: Commercial|B6
2310011500 Industrial Processes|On-Shore Oil Production|Oil and Gas Exploration and Production|A
2310023509 Industrial Processes|Coal Bed Methane Natural Gas|Oil and Gas Exploration and Production|A
2310321010 Industrial Processes|On-Shore Gas Production - Conventional|Oil and Gas Exploration and Production|A
2310321603 Industrial Processes|On-Shore Gas Production - Conventional|Oil and Gas Exploration and Production|A
2310021502 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|B
2680003000 Waste Disposal, Treatment, and Recovery|100% Green Waste (e.g., residential or municipal yard wastes
2310022410 Industrial Processes|Off-Shore Gas Production|Oil and Gas Exploration and Production|
2310012000 Industrial Processes|Off-Shore Oil Production|Oil and Gas Exploration and Production|
2310002411 Industrial Processes|Off-Shore Oil And Gas Production|Oil and Gas Exploration and Production|
2104008320 Stationary Source Fuel Combustion|Wood|Residential|B
2310012521 Industrial Processes|Off-Shore Oil Production|Oil and Gas Exploration and Production|
2310012516 Industrial Processes|Off-Shore Oil Production|Oil and Gas Exploration and Production|
2310012511 Industrial Processes|Off-Shore Oil Production|Oil and Gas Exploration and Production|
2310002421 Industrial Processes|Off-Shore Oil And Gas Production|Oil and Gas Exploration and Production|
2310022090 Industrial Processes|Off-Shore Gas Production|Oil and Gas Exploration and Production|
2310012515 Industrial Processes|Off-Shore Oil Production|Oil and Gas Exploration and Production|
2310012020 Industrial Processes|Off-Shore Oil Production|Oil and Gas Exploration and Production|
2310022000 Industrial Processes|Off-Shore Gas Production|Oil and Gas Exploration and Production|
2310022105 Industrial Processes|Off-Shore Gas Production|Oil and Gas Exploration and Production|
2310321400 Industrial Processes|On-Shore Gas Production - Conventional|Oil and Gas Exploration and Production|A
2310022502 Industrial Processes|Off-Shore Gas Production|Oil and Gas Exploration and Production|
2310012526 Industrial Processes|Off-Shore Oil Production|Oil and Gas Exploration and Production|
2310002301 Industrial Processes|Off-Shore Oil And Gas Production|Oil and Gas Exploration and Production|
2310022010 Industrial Processes|Off-Shore Gas Production|Oil and Gas Exploration and Production|
2310012512 Industrial Processes|Off-Shore Oil Production|Oil and Gas Exploration and Production|
2501070053 Storage and Transport|Diesel Service Stations|Petroleum and Petroleum Product Storage|
2285002007 Mobile Sources|Diesel|Railroad Equipment|
2310010300 Industrial Processes|Crude Petroleum|Oil and Gas Exploration and Production|
2701200000 Natural Sources|Vegetation|Biogenic|
2701220000 Natural Sources|Vegetation/Agriculture|Biogenic|
2461023000 Solvent Utilization|Asphalt Roofing|Miscellaneous Non-industrial: Commercial|B1B
2401035000 Solvent Utilization|Plastic Products: SIC 308|Surface Coating|
2310021251 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2310021503 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|B
2310111401 Industrial Processes|On-Shore Oil Exploration|Oil and Gas Exploration and Production|
2310023516 Industrial Processes|Coal Bed Methane Natural Gas|Oil and Gas Exploration and Production|B
2310011502 Industrial Processes|On-Shore Oil Production|Oil and Gas Exploration and Production|B
2805030000 Miscellaneous Area Sources|Poultry Waste Emissions|Agriculture Production - Livestock|B1B
2801500171 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2310021100 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|B
2310002401 Industrial Processes|Off-Shore Oil And Gas Production|Oil and Gas Exploration and Production|
2310022420 Industrial Processes|Off-Shore Gas Production|Oil and Gas Exploration and Production|
2310022051 Industrial Processes|Off-Shore Gas Production|Oil and Gas Exploration and Production|
2310022505 Industrial Processes|Off-Shore Gas Production|Oil and Gas Exploration and Production|
2310112401 Industrial Processes|Off-Shore Oil Exploration|Oil and Gas Exploration and Production|
2810050000 Miscellaneous Area Sources|Motor Vehicle Fires|Other Combustion|
2302080000 Industrial Processes|Miscellaneous Food and Kindred Products|Food and Kindred Products: SIC 20|
2310002305 Industrial Processes|Off-Shore Oil And Gas Production|Oil and Gas Exploration and Production|
2310022506 Industrial Processes|Off-Shore Gas Production|Oil and Gas Exploration and Production|
2310122100 Industrial Processes|Off-Shore Gas Exploration|Oil and Gas Exploration and Production|
2310012522 Industrial Processes|Off-Shore Oil Production|Oil and Gas Exploration and Production|
2310022501 Industrial Processes|Off-Shore Gas Production|Oil and Gas Exploration and Production|
2401010000 Solvent Utilization|Textile Products: SIC 22|Surface Coating|
2310023100 Industrial Processes|Coal Bed Methane Natural Gas|Oil and Gas Exploration and Production|
2310023302 Industrial Processes|Coal Bed Methane Natural Gas|Oil and Gas Exploration and Production|
2310000220 Industrial Processes|All Processes|Oil and Gas Exploration and Production|B
2104008300 Stationary Source Fuel Combustion|Wood|Residential|A
2501995120 Storage and Transport|All Storage Types: Working Loss|Petroleum and Petroleum Product Storage|
2310023010 Industrial Processes|Coal Bed Methane Natural Gas|Oil and Gas Exploration and Production|
2310023515 Industrial Processes|Coal Bed Methane Natural Gas|Oil and Gas Exploration and Production|B
2310023030 Industrial Processes|Coal Bed Methane Natural Gas|Oil and Gas Exploration and Production|
2310023600 Industrial Processes|Coal Bed Methane Natural Gas|Oil and Gas Exploration and Production|
2310023606 Industrial Processes|Coal Bed Methane Natural Gas|Oil and Gas Exploration and Production|
2401050000 Solvent Utilization|Miscellaneous Finished Metals: SIC 34 - (341 + 3498)|Surface Coating|
2505010000 Storage and Transport|Rail Tank Car|Petroleum and Petroleum Product Transport|B1A
2650000000 Waste Disposal, Treatment, and Recovery|Scrap and Waste Materials|Scrap and Waste Materials|
2310023512 Industrial Processes|Coal Bed Methane Natural Gas|Oil and Gas Exploration and Production|B
2310023202 Industrial Processes|Coal Bed Methane Natural Gas|Oil and Gas Exploration and Production|
2310023310 Industrial Processes|Coal Bed Methane Natural Gas|Oil and Gas Exploration and Production|
2310021201 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2310021504 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|B
2310021303 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2310021203 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2310021301 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2310011504 Industrial Processes|On-Shore Oil Production|Oil and Gas Exploration and Production|B
2310011506 Industrial Processes|On-Shore Oil Production|Oil and Gas Exploration and Production|B
2310011450 Industrial Processes|On-Shore Oil Production|Oil and Gas Exploration and Production|
2610000300 Waste Disposal, Treatment, and Recovery|All Categories|Open Burning|
2805039300 Miscellaneous Area Sources|Swine production - operations with lagoons (unspecified animal age)|Agric
2801600000 Miscellaneous Area Sources|Country Grain Elevators|Agriculture Production - Crops|
2660000000 Waste Disposal, Treatment, and Recovery|Leaking Underground Storage Tanks|Leaking Underground Storag
2102004000 Stationary Source Fuel Combustion|Distillate Oil|Industrial|
2440020000 Solvent Utilization|Adhesive (Industrial) Application|Miscellaneous Industrial|
2310030300 Industrial Processes|Natural Gas Liquids|Oil and Gas Exploration and Production|
2310010700 Industrial Processes|Crude Petroleum|Oil and Gas Exploration and Production|
2310021103 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2801500300 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2310002000 Industrial Processes|Off-Shore Oil And Gas Production|Oil and Gas Exploration and Production|
2310021402 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2310021403 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2310021101 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2801500330 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2801500390 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2505020150 Storage and Transport|Marine Vessel|Petroleum and Petroleum Product Transport|B2B
2505020180 Storage and Transport|Marine Vessel|Petroleum and Petroleum Product Transport|B2B
2601000000 Waste Disposal, Treatment, and Recovery|All Categories|On-site Incineration|
2302070010 Industrial Processes|Fermentation/Beverages|Food and Kindred Products: SIC 20|
2805010200 Miscellaneous Area Sources|Poultry production - turkeys|Agriculture Production - Livestock|B3B
2505020030 Storage and Transport|Marine Vessel|Petroleum and Petroleum Product Transport|B2B
2505020060 Storage and Transport|Marine Vessel|Petroleum and Petroleum Product Transport|B2B
2399000000 Industrial Processes|Industrial Processes: NEC|Industrial Processes: NEC|
2801500263 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2425020000 Solvent Utilization|Letterpress|Graphic Arts|
2307000000 Industrial Processes|All Processes|Wood Products: SIC 24|
2304000000 Industrial Processes|All Processes|Secondary Metal Production: SIC 33|
2805008200 Miscellaneous Area Sources|Poultry production - layers with wet manure management systems|Agricultur
2805022200 Miscellaneous Area Sources|Dairy cattle - deep pit dairy|Agriculture Production - Livestock|B1B
2805022100 Miscellaneous Area Sources|Dairy cattle - deep pit dairy|Agriculture Production - Livestock|B1B
2805021200 Miscellaneous Area Sources|Dairy cattle - scrape dairy|Agriculture Production - Livestock|B1B
2805053100 Miscellaneous Area Sources|Swine production - outdoor operations (unspecified animal age)|Agricultur
2310421010 Industrial Processes|On-Shore Gas Production - Unconventional|Oil and Gas Exploration and Production
2805023200 Miscellaneous Area Sources|Dairy cattle - drylot/pasture dairy|Agriculture Production - Livestock|B1
2505020000 Storage and Transport|Marine Vessel|Petroleum and Petroleum Product Transport|B2A
2805039100 Miscellaneous Area Sources|Swine production - operations with lagoons (unspecified animal age)|Agric
2285002009 Mobile Sources|Diesel|Railroad Equipment|
2310321100 Industrial Processes|On-Shore Gas Production - Conventional|Oil and Gas Exploration and Production|A
2525000000 Storage and Transport|All Transport Types|Inorganic Chemical Transport|
2680001000 Waste Disposal, Treatment, and Recovery|100% Biosolids (e.g., sewage sludge, manure, mixtures of the
2806015000 Miscellaneous Area Sources|Dogs|Domestic Animals Waste Emissions|
2810040000 Miscellaneous Area Sources|Aircraft/Rocket Engine Firing and Testing|Other Combustion|
2801500420 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2310020600 Industrial Processes|Natural Gas|Oil and Gas Exploration and Production|
2805047300 Miscellaneous Area Sources|Swine production - deep-pit house operations (unspecified animal age)|Agr
2310021401 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2805030007 Miscellaneous Area Sources|Poultry Waste Emissions|Agriculture Production - Livestock|B6A
2805019100 Miscellaneous Area Sources|Dairy cattle - flush dairy|Agriculture Production - Livestock|B1B
2805021300 Miscellaneous Area Sources|Dairy cattle - scrape dairy|Agriculture Production - Livestock|B1B
2801500500 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2805039200 Miscellaneous Area Sources|Swine production - operations with lagoons (unspecified animal age)|Agric
2103004000 Stationary Source Fuel Combustion|Distillate Oil|Commercial/Institutional|
2301020000 Industrial Processes|Process Emissions from Synthetic Fibers Manuf (NAPAP cat. 107)|Chemical Manufac
2461900000 Solvent Utilization|Miscellaneous Products: NEC|Miscellaneous Non-industrial: Commercial|B7B
2310021310 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2285002010 Mobile Sources|Diesel|Railroad Equipment|
2805001100 Miscellaneous Area Sources|Beef cattle - finishing operations on feedlots (drylots)|Agriculture Prod
2805009200 Miscellaneous Area Sources|Poultry production - broilers|Agriculture Production - Livestock|B2B
2805021100 Miscellaneous Area Sources|Dairy cattle - scrape dairy|Agriculture Production - Livestock|B1B
2810003000 Miscellaneous Area Sources|Cigarette Smoke|Other Combustion|
2601010000 Waste Disposal, Treatment, and Recovery|Industrial|On-site Incineration|
2460000000 Solvent Utilization|All Processes|Miscellaneous Non-industrial: Consumer and Commercial|A
2801500430 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2801500151 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2305000000 Industrial Processes|All Processes|Mineral Processes: SIC 32|
2425010000 Solvent Utilization|Lithography|Graphic Arts|
2805019200 Miscellaneous Area Sources|Dairy cattle - flush dairy|Agriculture Production - Livestock|B1B
2399010000 Industrial Processes|Refrigerant Losses|Industrial Refrigeration|
2425040000 Solvent Utilization|Flexography|Graphic Arts|
2801500350 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2275087000 Mobile Sources|In-flight (non-Landing-Takeoff cycle)|Aircraft|
2420000055 Solvent Utilization|All Processes|Dry Cleaning|B
2310020000 Industrial Processes|Natural Gas|Oil and Gas Exploration and Production|
2801520000 Miscellaneous Area Sources|Orchard Heaters|Agriculture Production - Crops|
2310001000 Industrial Processes|All Processes : On-shore|Oil and Gas Exploration and Production|
2801500600 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2306010000 Industrial Processes|Asphalt Paving/Roofing Materials|Petroleum Refining: SIC 29|
2805001300 Miscellaneous Area Sources|Beef cattle - finishing operations on feedlots (drylots)|Agriculture Prod
2805023300 Miscellaneous Area Sources|Dairy cattle - drylot/pasture dairy|Agriculture Production - Livestock|B1
2830000000 Miscellaneous Area Sources|All Catastrophic/Accidential Releases|Catastrophic/Accidental Releases|
2308000000 Industrial Processes|All Processes|Rubber/Plastics: SIC 30|
2310021700 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2461020000 Solvent Utilization|Asphalt Application: All Processes|Miscellaneous Non-industrial: Commercial|
2310021500 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2805022300 Miscellaneous Area Sources|Dairy cattle - deep pit dairy|Agriculture Production - Livestock|B1B
2505020090 Storage and Transport|Marine Vessel|Petroleum and Petroleum Product Transport|B2B
2807025000 Miscellaneous Area Sources|Elk|Wild Animals Waste Emissions|
2302070001 Industrial Processes|Fermentation/Beverages|Food and Kindred Products: SIC 20|
2302000000 Industrial Processes|All Processes|Food and Kindred Products: SIC 20|
2810005001 Miscellaneous Area Sources|Managed Burning, Slash (Logging Debris)|Other Combustion|
2805047100 Miscellaneous Area Sources|Swine production - deep-pit house operations (unspecified animal age)|Agr
2302070000 Industrial Processes|Fermentation/Beverages|Food and Kindred Products: SIC 20|
2325030000 Industrial Processes|Sand and Gravel|Mining and Quarrying: SIC 14|
2807030000 Miscellaneous Area Sources|Deer|Wild Animals Waste Emissions|
2310421100 Industrial Processes|On-Shore Gas Production - Unconventional|Oil and Gas Exploration and Production
2310421603 Industrial Processes|On-Shore Gas Production - Unconventional|Oil and Gas Exploration and Production
2302010000 Industrial Processes|Meat Products|Food and Kindred Products: SIC 20|
2805009300 Miscellaneous Area Sources|Poultry production - broilers|Agriculture Production - Livestock|B2B
2501080201 Storage and Transport|Airports : Aviation Gasoline|Petroleum and Petroleum Product Storage|
2630010000 Waste Disposal, Treatment, and Recovery|Industrial|Wastewater Treatment|B1A
2310421400 Industrial Processes|On-Shore Gas Production - Unconventional|Oil and Gas Exploration and Production
2425030000 Solvent Utilization|Rotogravure|Graphic Arts|
2806010000 Miscellaneous Area Sources|Cats|Domestic Animals Waste Emissions|
2810010000 Miscellaneous Area Sources|Human Perspiration and Respiration|Other Combustion|
2325060000 Industrial Processes|Lead Ore Mining and Milling|Mining and Quarrying: SIC 10|
2810005000 Miscellaneous Area Sources|Managed Burning, Slash (Logging Debris)|Other Combustion|
2520010000 Storage and Transport|Commercial/Industrial: Breathing Loss|Inorganic Chemical Storage|
2840000000 Miscellaneous Area Sources|Automotive Repair Shops|Automotive Repair Shops|
2620000000 Waste Disposal, Treatment, and Recovery|All Categories|Landfills|
2309000000 Industrial Processes|All Processes|Fabricated Metals: SIC 34|
2510000000 Storage and Transport|All Storage Types: Breathing Loss|Organic Chemical Storage|
2810035000 Miscellaneous Area Sources|Firefighting Training|Other Combustion|
2801000008 Miscellaneous Area Sources|Agriculture - Crops|Agriculture Production - Crops|
2830001000 Miscellaneous Area Sources|Industrial Accidents|Catastrophic/Accidental Releases|
2805020002 Miscellaneous Area Sources|Cattle and Calves Waste Emissions|Agriculture Production - Livestock|B2A
2302040000 Industrial Processes|Grain Mill Products|Food and Kindred Products: SIC 20|
2301000000 Industrial Processes|All Processes|Chemical Manufacturing: SIC 28|
2312000000 Industrial Processes|All Processes|Machinery: SIC 35|A
2301030000 Industrial Processes|Process Emissions from Pharmaceutical Manuf (NAPAP cat. 106)|Chemical Manufactu
2801000000 Miscellaneous Area Sources|Agriculture - Crops|Agriculture Production - Crops|
2310400220 Industrial Processes|All Processes - Unconventional|Oil and Gas Exploration and Production|A
2635000000 Waste Disposal, Treatment, and Recovery|All Categories|Soil and Groundwater Remediation|
2302080002 Industrial Processes|Miscellaneous Food and Kindred Products|Food and Kindred Products: SIC 20|
2310011100 Industrial Processes|On-Shore Oil Production|Oil and Gas Exploration and Production|
2310011600 Industrial Processes|On-Shore Oil Production|Oil and Gas Exploration and Production|
2310000230 Industrial Processes|All Processes|Oil and Gas Exploration and Production|
2310011020 Industrial Processes|On-Shore Oil Production|Oil and Gas Exploration and Production|
2680002000 Waste Disposal, Treatment, and Recovery|Mixed Waste (e.g., a 50:50 mixture of biosolids and green wa
2280002104 Mobile Sources|Diesel|Marine Vessels, Commercial|
2310000552 Industrial Processes|All Processes|Oil and Gas Exploration and Production|
2310021450 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2310000553 Industrial Processes|All Processes|Oil and Gas Exploration and Production|
2301010000 Industrial Processes|Industrial Inorganic Chemical Manufacturing|Chemical Manufacturing: SIC 28|
2401005700 Solvent Utilization|Auto Refinishing: SIC 7532|Surface Coating|
2420000999 Solvent Utilization|All Processes|Dry Cleaning|
2805001050 Miscellaneous Area Sources|Turkeys|Agriculture Production - Livestock|
2805001010 Miscellaneous Area Sources|Dairy Cattle|Agriculture Production - Livestock|
2805001020 Miscellaneous Area Sources|Broilers|Agriculture Production - Livestock|
2805001030 Miscellaneous Area Sources|Layers|Agriculture Production - Livestock|
2805001040 Miscellaneous Area Sources|Swine|Agriculture Production - Livestock|
2801500161 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2801500142 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2280002201 Mobile Sources|Diesel|Marine Vessels, Commercial|
2280002203 Mobile Sources|Diesel|Marine Vessels, Commercial|
2280002101 Mobile Sources|Diesel|Marine Vessels, Commercial|
2620010000 Waste Disposal, Treatment, and Recovery|Industrial|Landfills|
2310023000 Industrial Processes|Coal Bed Methane Natural Gas|Oil and Gas Exploration and Production|
2310000551 Industrial Processes|All Processes|Oil and Gas Exploration and Production|
2310011001 Industrial Processes|On-Shore Oil Production|Oil and Gas Exploration and Production|
2310021109 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2310021209 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2310021309 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2801500112 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2801500182 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2280002202 Mobile Sources|Diesel|Marine Vessels, Commercial|
2280002204 Mobile Sources|Diesel|Marine Vessels, Commercial|
2306010100 Industrial Processes|Asphalt Mixing Plants|Petroleum Refining: SIC 29|
2310021602 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2461100000 Solvent Utilization|Solvent Reclamation: All Processes|Miscellaneous Non-industrial: Commercial|B3A
2310021600 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2801500130 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2801500202 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2801500192 Miscellaneous Area Sources|Agricultural Field Burning - whole field set on fire|Agriculture Producti
2310021412 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2325020000 Industrial Processes|Crushed and Broken Stone|Mining and Quarrying: SIC 14|
2310021802 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2310021803 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2310021801 Industrial Processes|On-Shore Gas Production|Oil and Gas Exploration and Production|
2310023401 Industrial Processes|Coal Bed Methane Natural Gas|Oil and Gas Exploration and Production|
2310030400 Industrial Processes|Natural Gas Liquids|Oil and Gas Exploration and Production|
2310111701 Industrial Processes|On-Shore Oil Exploration|Oil and Gas Exploration and Production|
2310030220 Industrial Processes|Natural Gas Liquids|Oil and Gas Exploration and Production|
2104008530 Stationary Source Fuel Combustion|Wood|Residential|A
2104008620 Stationary Source Fuel Combustion|Wood|Residential|B
2104008630 Stationary Source Fuel Combustion|Wood|Residential|B
2801700000 Miscellaneous Area Sources|Fertilizer Application|Agriculture Production - Crops|
2102010000 Stationary Source Fuel Combustion|Process Gas|Industrial|
2310300220 Industrial Processes|All Processes - Conventional|Oil and Gas Exploration and Production|A
2280002102 Mobile Sources|Diesel|Marine Vessels, Commercial|
2280002103 Mobile Sources|Diesel|Marine Vessels, Commercial|
2280003203 Mobile Sources|Residual|Marine Vessels, Commercial|
2280003204 Mobile Sources|Residual|Marine Vessels, Commercial|
2280003103 Mobile Sources|Residual|Marine Vessels, Commercial|
2280003104 Mobile Sources|Residual|Marine Vessels, Commercial|
EOFA
#
#rm -f *.da  # remove all direct access files (spatial surrogate county/SCC assigns)
if ( -e area17v1.x ) rm area17v1.x
pgf90 -O3 -o area17v1.x area17v1.f  # For mamma or lagoon compile
#pgf90 -g -C -o area17v1.x area17v1.f  # For mamma or lagoon compile
#pgf90 -O2 -o area17v1.x area17v1.f  # For mamma or lagoon compile
#f90 -O3 -o area17v1.x area17v1.f
#
area17v1.x NOX
area17v1.x VOC
area17v1.x CO
area17v1.x NH3
area17v1.x SO2
area17v1.x PM10-PRI
area17v1.x PM25-PRI 
#area17v1.x CO2
date
time
rm *.da
#
#rm o3plt.*
if ($ENVIRONMENT == "BATCH") then
   exit (0)
#else if ($ENVIRONMENT == "INTERACTIVE") then
#   ictrans gmeta
endif
